// Code generated by weaver. DO NOT EDIT.
// source: semconv/model/host/registry.yaml

package semconv

import "go.opentelemetry.io/otel/attribute"

// Host Attributes
const (
	// HostArchKey is the OTel attribute key for host.arch.
	// Hardware architecture of the host.
	HostArchKey = attribute.Key("host.arch")
	// HostNameKey is the OTel attribute key for host.name.
	// Hostname of the system.
	HostNameKey = attribute.Key("host.name")
)

// HostArch returns an attribute KeyValue for host.arch.
func HostArch(val string) attribute.KeyValue {
	return HostArchKey.String(val)
}

// HostName returns an attribute KeyValue for host.name.
func HostName(val string) attribute.KeyValue {
	return HostNameKey.String(val)
}

