// Code generated by weaver. DO NOT EDIT.
// source: semconv/model/osa/registry.yaml

package semconv

import "go.opentelemetry.io/otel/attribute"

// Osa Attributes
const (
	// OsaDurationMsKey is the OTel attribute key for osa.duration_ms.
	// Wall-clock duration in milliseconds for the provider call.
	OsaDurationMsKey = attribute.Key("osa.duration_ms")
	// OsaModelKey is the OTel attribute key for osa.model.
	// Model identifier used for this chat completion.
	OsaModelKey = attribute.Key("osa.model")
	// OsaProviderKey is the OTel attribute key for osa.provider.
	// LLM provider used for this chat completion.
	OsaProviderKey = attribute.Key("osa.provider")
)

// OsaDurationMs returns an attribute KeyValue for osa.duration_ms.
func OsaDurationMs(val int64) attribute.KeyValue {
	return OsaDurationMsKey.Int64(val)
}

// OsaModel returns an attribute KeyValue for osa.model.
func OsaModel(val string) attribute.KeyValue {
	return OsaModelKey.String(val)
}

// OsaProvider returns an attribute KeyValue for osa.provider.
func OsaProvider(val string) attribute.KeyValue {
	return OsaProviderKey.String(val)
}

// OsaProviderValues contains the known enum values for osa.provider.
var OsaProviderValues = struct {
	Anthropic string
	Ollama string
	Cohere string
	Google string
	Replicate string
	Openai string
}{
	Anthropic: "anthropic",
	Ollama: "ollama",
	Cohere: "cohere",
	Google: "google",
	Replicate: "replicate",
	Openai: "openai",
}

