-- Migration: 042_osa_integration.sql
-- Description: OSA-5 Integration - App metadata, workspaces, and sync tracking
-- Created: 2026-01-09
-- Phase: 2 (Core Integration) & 3 (Data Sync)

-- =============================================================================
-- OSA MODULES REGISTRY
-- Tracks all OSA-generated modules and applications
-- =============================================================================
CREATE TABLE IF NOT EXISTS osa_modules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Identification
    name VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    description TEXT,
    module_type VARCHAR(50) NOT NULL, -- 'builtin', 'generated', 'custom'

    -- Schema definitions (JSONB for flexibility)
    schema_definition JSONB, -- Database schema (tables, fields, relations)
    api_definition JSONB,    -- API endpoints (REST routes, params, responses)
    ui_definition JSONB,     -- Frontend components (Svelte files, routes)

    -- Ownership and tracking
    created_by VARCHAR(255) REFERENCES "user"(id) ON DELETE SET NULL,
    workspace_id UUID, -- Links to osa_workspaces (added below)

    -- Status
    status VARCHAR(50) DEFAULT 'draft', -- 'draft', 'active', 'archived', 'failed'
    version VARCHAR(50) DEFAULT '1.0.0',

    -- Metadata
    metadata JSONB DEFAULT '{}',
    tags TEXT[], -- For categorization and search

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deployed_at TIMESTAMPTZ,

    -- Indexes
    CONSTRAINT osa_modules_name_workspace_unique UNIQUE(name, workspace_id)
);

CREATE INDEX idx_osa_modules_workspace ON osa_modules(workspace_id);
CREATE INDEX idx_osa_modules_created_by ON osa_modules(created_by);
CREATE INDEX idx_osa_modules_status ON osa_modules(status);
CREATE INDEX idx_osa_modules_type ON osa_modules(module_type);
CREATE INDEX idx_osa_modules_tags ON osa_modules USING GIN(tags);

-- =============================================================================
-- OSA WORKSPACES
-- User workspaces with 2D/3D configuration
-- =============================================================================
CREATE TABLE IF NOT EXISTS osa_workspaces (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Ownership
    user_id VARCHAR(255) NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,

    -- Display mode
    mode VARCHAR(20) DEFAULT '2d', -- '2d', '3d', 'hybrid'

    -- Layout configuration (panel positions, connections)
    layout JSONB DEFAULT '{}',

    -- Active modules (array of module IDs)
    active_modules UUID[] DEFAULT '{}',

    -- Template type
    template_type VARCHAR(50) DEFAULT 'business_os', -- 'business_os', 'agency_os', 'content_os', 'sales_os', 'custom_os'

    -- Settings
    settings JSONB DEFAULT '{}',

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_accessed_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT osa_workspaces_user_name_unique UNIQUE(user_id, name)
);

CREATE INDEX idx_osa_workspaces_user ON osa_workspaces(user_id);
CREATE INDEX idx_osa_workspaces_template ON osa_workspaces(template_type);
CREATE INDEX idx_osa_workspaces_mode ON osa_workspaces(mode);

-- Add workspace_id foreign key to osa_modules now that table exists
ALTER TABLE osa_modules
ADD CONSTRAINT fk_osa_modules_workspace
FOREIGN KEY (workspace_id)
REFERENCES osa_workspaces(id)
ON DELETE CASCADE;

-- =============================================================================
-- OSA GENERATED APPS
-- Tracks full-stack applications generated by OSA-5
-- =============================================================================
CREATE TABLE IF NOT EXISTS osa_generated_apps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Association
    workspace_id UUID NOT NULL REFERENCES osa_workspaces(id) ON DELETE CASCADE,
    module_id UUID REFERENCES osa_modules(id) ON DELETE SET NULL,

    -- App details
    name VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    description TEXT,

    -- OSA-5 workflow information
    osa_workflow_id VARCHAR(255), -- OSA-5 workflow ID
    osa_sandbox_id VARCHAR(255),  -- E2B sandbox ID

    -- Code storage
    code_repository TEXT, -- Git repo URL or file path
    deployment_url TEXT,  -- Live deployment URL

    -- Status tracking
    status VARCHAR(50) DEFAULT 'generated', -- 'generating', 'generated', 'deploying', 'deployed', 'running', 'stopped', 'failed'

    -- Generation results
    files_created INTEGER DEFAULT 0,
    tests_passed BOOLEAN DEFAULT false,
    build_status VARCHAR(50), -- 'success', 'failed', 'pending'

    -- Metadata from OSA-5
    metadata JSONB DEFAULT '{}',

    -- Error tracking
    error_message TEXT,
    error_stack TEXT,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    generated_at TIMESTAMPTZ,
    deployed_at TIMESTAMPTZ,
    last_build_at TIMESTAMPTZ
);

CREATE INDEX idx_osa_apps_workspace ON osa_generated_apps(workspace_id);
CREATE INDEX idx_osa_apps_module ON osa_generated_apps(module_id);
CREATE INDEX idx_osa_apps_status ON osa_generated_apps(status);
CREATE INDEX idx_osa_apps_workflow ON osa_generated_apps(osa_workflow_id);

-- =============================================================================
-- OSA EXECUTION HISTORY
-- Tracks all code executions via terminal
-- =============================================================================
CREATE TABLE IF NOT EXISTS osa_execution_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Association
    user_id VARCHAR(255) NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    app_id UUID REFERENCES osa_generated_apps(id) ON DELETE SET NULL,
    workspace_id UUID REFERENCES osa_workspaces(id) ON DELETE CASCADE,

    -- Execution details
    command TEXT NOT NULL,
    working_directory TEXT,
    environment_vars JSONB DEFAULT '{}',

    -- Results
    output TEXT,
    error_output TEXT,
    exit_code INTEGER,

    -- Performance
    duration_ms INTEGER,

    -- Context
    triggered_by VARCHAR(50), -- 'user', 'agent', 'workflow', 'cron'
    metadata JSONB DEFAULT '{}',

    -- Timestamp
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_osa_exec_user ON osa_execution_history(user_id);
CREATE INDEX idx_osa_exec_app ON osa_execution_history(app_id);
CREATE INDEX idx_osa_exec_workspace ON osa_execution_history(workspace_id);
CREATE INDEX idx_osa_exec_created ON osa_execution_history(created_at DESC);

-- =============================================================================
-- OSA SYNC STATUS
-- Tracks sync state between BusinessOS and OSA-5
-- =============================================================================
CREATE TABLE IF NOT EXISTS osa_sync_status (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Sync target
    entity_type VARCHAR(50) NOT NULL, -- 'user', 'workspace', 'app', 'module'
    entity_id UUID NOT NULL,

    -- OSA-5 reference
    osa_entity_id VARCHAR(255), -- ID in OSA-5 system
    osa_entity_type VARCHAR(50), -- 'project', 'workspace', 'user'

    -- Sync state
    sync_status VARCHAR(50) DEFAULT 'pending', -- 'pending', 'syncing', 'synced', 'failed', 'conflict'
    last_sync_at TIMESTAMPTZ,
    next_sync_at TIMESTAMPTZ,

    -- Sync direction
    sync_direction VARCHAR(50) DEFAULT 'bidirectional', -- 'to_osa', 'from_osa', 'bidirectional'

    -- Error tracking
    error_count INTEGER DEFAULT 0,
    last_error TEXT,

    -- Data snapshot (for conflict resolution)
    local_snapshot JSONB,
    remote_snapshot JSONB,

    -- Metadata
    metadata JSONB DEFAULT '{}',

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT osa_sync_entity_unique UNIQUE(entity_type, entity_id)
);

CREATE INDEX idx_osa_sync_entity ON osa_sync_status(entity_type, entity_id);
CREATE INDEX idx_osa_sync_status ON osa_sync_status(sync_status);
CREATE INDEX idx_osa_sync_next ON osa_sync_status(next_sync_at);

-- =============================================================================
-- OSA BUILD EVENTS
-- Real-time build/deployment events from OSA-5
-- =============================================================================
CREATE TABLE IF NOT EXISTS osa_build_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Association
    app_id UUID NOT NULL REFERENCES osa_generated_apps(id) ON DELETE CASCADE,
    workspace_id UUID REFERENCES osa_workspaces(id) ON DELETE SET NULL,

    -- Event details
    event_type VARCHAR(50) NOT NULL, -- 'build_started', 'build_progress', 'build_completed', 'build_failed', 'test_started', 'test_completed', 'deploy_started', 'deploy_completed'
    event_data JSONB DEFAULT '{}',

    -- Build context
    build_id VARCHAR(255),
    phase VARCHAR(50), -- 'planning', 'generation', 'testing', 'deployment'

    -- Progress tracking
    progress_percent INTEGER DEFAULT 0,
    status_message TEXT,

    -- Timestamp
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_osa_build_app ON osa_build_events(app_id);
CREATE INDEX idx_osa_build_workspace ON osa_build_events(workspace_id);
CREATE INDEX idx_osa_build_type ON osa_build_events(event_type);
CREATE INDEX idx_osa_build_created ON osa_build_events(created_at DESC);
CREATE INDEX idx_osa_build_build_id ON osa_build_events(build_id);

-- =============================================================================
-- OSA WEBHOOKS
-- Webhook endpoints for OSA-5 callbacks
-- =============================================================================
CREATE TABLE IF NOT EXISTS osa_webhooks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Target
    workspace_id UUID REFERENCES osa_workspaces(id) ON DELETE CASCADE,
    app_id UUID REFERENCES osa_generated_apps(id) ON DELETE CASCADE,

    -- Webhook config
    event_type VARCHAR(50) NOT NULL, -- 'app.generated', 'app.deployed', 'build.completed', 'build.failed'
    webhook_url TEXT NOT NULL,
    secret_key VARCHAR(255), -- For HMAC verification

    -- Status
    enabled BOOLEAN DEFAULT true,
    last_triggered_at TIMESTAMPTZ,
    success_count INTEGER DEFAULT 0,
    failure_count INTEGER DEFAULT 0,

    -- Metadata
    metadata JSONB DEFAULT '{}',

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_osa_webhooks_workspace ON osa_webhooks(workspace_id);
CREATE INDEX idx_osa_webhooks_app ON osa_webhooks(app_id);
CREATE INDEX idx_osa_webhooks_event ON osa_webhooks(event_type);
CREATE INDEX idx_osa_webhooks_enabled ON osa_webhooks(enabled);

-- =============================================================================
-- UPDATE TRIGGERS
-- Auto-update updated_at timestamps
-- =============================================================================

-- osa_modules updated_at trigger
CREATE OR REPLACE FUNCTION update_osa_modules_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_osa_modules_updated_at
    BEFORE UPDATE ON osa_modules
    FOR EACH ROW
    EXECUTE FUNCTION update_osa_modules_updated_at();

-- osa_workspaces updated_at trigger
CREATE OR REPLACE FUNCTION update_osa_workspaces_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_osa_workspaces_updated_at
    BEFORE UPDATE ON osa_workspaces
    FOR EACH ROW
    EXECUTE FUNCTION update_osa_workspaces_updated_at();

-- osa_generated_apps updated_at trigger
CREATE OR REPLACE FUNCTION update_osa_generated_apps_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_osa_generated_apps_updated_at
    BEFORE UPDATE ON osa_generated_apps
    FOR EACH ROW
    EXECUTE FUNCTION update_osa_generated_apps_updated_at();

-- osa_sync_status updated_at trigger
CREATE OR REPLACE FUNCTION update_osa_sync_status_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_osa_sync_status_updated_at
    BEFORE UPDATE ON osa_sync_status
    FOR EACH ROW
    EXECUTE FUNCTION update_osa_sync_status_updated_at();

-- osa_webhooks updated_at trigger
CREATE OR REPLACE FUNCTION update_osa_webhooks_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_osa_webhooks_updated_at
    BEFORE UPDATE ON osa_webhooks
    FOR EACH ROW
    EXECUTE FUNCTION update_osa_webhooks_updated_at();

-- =============================================================================
-- COMMENTS FOR DOCUMENTATION
-- =============================================================================

COMMENT ON TABLE osa_modules IS 'Registry of OSA-generated modules and applications';
COMMENT ON TABLE osa_workspaces IS 'User workspaces with 2D/3D layout configuration';
COMMENT ON TABLE osa_generated_apps IS 'Full-stack applications generated by OSA-5';
COMMENT ON TABLE osa_execution_history IS 'Terminal execution history for OSA apps';
COMMENT ON TABLE osa_sync_status IS 'Sync state between BusinessOS and OSA-5';
COMMENT ON TABLE osa_build_events IS 'Real-time build and deployment events';
COMMENT ON TABLE osa_webhooks IS 'Webhook configurations for OSA-5 callbacks';

-- =============================================================================
-- SEED DATA (Optional - for development)
-- =============================================================================

-- Insert default workspace template for first user (if exists)
-- This is commented out - run manually in development if needed
/*
INSERT INTO osa_workspaces (user_id, name, template_type, mode)
SELECT id, 'My Workspace', 'business_os', '2d'
FROM users
LIMIT 1
ON CONFLICT DO NOTHING;
*/
