// Package integration provides integration tests for BusinessOS.
package integration

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// =============================================================================
// BOS CLI ↔ BusinessOS Integration Tests
// =============================================================================
//
// Tests: Validate seamless integration between bos CLI (data operations) and
// BusinessOS API. Data generated by bos must be queryable via BusinessOS,
// and round-trip operations must preserve data integrity.
//
// Test Coverage:
//   1. Schema import → query via API
//   2. RDF export → Oxigraph indexing → SPARQL queries
//   3. Round-trip: import → export → import → verify equal
//   4. All 4 schema operations (import, export, update, validate)
//   5. Timing assertions (bos ≤500ms, Oxigraph ≤200ms)
//
// Execution environment:
//   - BusinessOS backend (http://localhost:8001)
//   - bos CLI (in PATH or BUSINESSOS_BOS_PATH)
//   - PostgreSQL (http://localhost:5432)
//   - Oxigraph/SPARQL endpoint (http://localhost:6379)
//
// Success criteria:
//   - All round-trips succeed
//   - Timing meets SLA (bos ≤500ms, API query ≤200ms, Oxigraph ≤200ms)
//   - Data integrity verified after round-trip
//   - All 4 schema operations functional
//
// =============================================================================

var (
	businessOSURL = getEnvOrDefault("BUSINESSOS_URL", "http://localhost:8001")
	oxigraphURL   = getEnvOrDefault("OXIGRAPH_URL", "http://localhost:6379")
	bosPath       = getEnvOrDefault("BUSINESSOS_BOS_PATH", "bos") // Expects bos in PATH
	testTimeout   = 30 * time.Second
)

func getEnvOrDefault(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}

// ============================================================================
// Test Structures
// ============================================================================

// BOSSchemaPayload represents a schema for import operations
type BOSSchemaPayload struct {
	SchemaName    string                 `json:"schema_name"`
	SchemaVersion string                 `json:"schema_version"`
	Tables        []TableDefinition      `json:"tables"`
	Metadata      map[string]interface{} `json:"metadata,omitempty"`
}

// TableDefinition represents a table in the schema
type TableDefinition struct {
	Name    string                `json:"name"`
	Columns []ColumnDefinition    `json:"columns"`
	Indexes []IndexDefinition     `json:"indexes,omitempty"`
}

// ColumnDefinition represents a column in a table
type ColumnDefinition struct {
	Name       string `json:"name"`
	Type       string `json:"type"`
	Required   bool   `json:"required"`
	PrimaryKey bool   `json:"primary_key,omitempty"`
}

// IndexDefinition represents an index on a table
type IndexDefinition struct {
	Name    string   `json:"name"`
	Columns []string `json:"columns"`
	Unique  bool     `json:"unique,omitempty"`
}

// BOSImportResponse represents the response from a bos import operation
type BOSImportResponse struct {
	Status         string                 `json:"status"`
	SchemaID       string                 `json:"schema_id"`
	TablesImported int                    `json:"tables_imported"`
	RDFTriples     int                    `json:"rdf_triples,omitempty"`
	ContentHash    string                 `json:"content_hash,omitempty"`
	DurationMs     int64                  `json:"duration_ms"`
	Timestamp      string                 `json:"timestamp"`
	Error          string                 `json:"error,omitempty"`
}

// BOSExportResponse represents the response from a bos export operation
type BOSExportResponse struct {
	Status      string `json:"status"`
	SchemaID    string `json:"schema_id"`
	Format      string `json:"format"` // json, rdf, csv, sql
	ContentSize int64  `json:"content_size"`
	DurationMs  int64  `json:"duration_ms"`
	Timestamp   string `json:"timestamp"`
	Data        string `json:"data,omitempty"`
	Error       string `json:"error,omitempty"`
}

// RDFTriple represents an RDF triple
type RDFTriple struct {
	Subject   string `json:"subject"`
	Predicate string `json:"predicate"`
	Object    string `json:"object"`
}

// OxigraphQuery represents a SPARQL query request
type OxigraphQuery struct {
	Query string `json:"query"`
}

// OxigraphQueryResult represents the result of a SPARQL query
type OxigraphQueryResult struct {
	Head    map[string][]string   `json:"head"`
	Results []map[string]string   `json:"results"`
	Error   string                `json:"error,omitempty"`
}

// ============================================================================
// Helper Functions
// ============================================================================

// makeRequest makes an HTTP request and returns the response body, status code, and error.
func makeRequest(method, url string, body interface{}) ([]byte, int, error) {
	ctx, cancel := context.WithTimeout(context.Background(), testTimeout)
	defer cancel()

	var bodyReader io.Reader
	if body != nil {
		bodyBytes, _ := json.Marshal(body)
		bodyReader = bytes.NewReader(bodyBytes)
	}

	req, err := http.NewRequestWithContext(ctx, method, url, bodyReader)
	if err != nil {
		return nil, 0, err
	}

	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: testTimeout}
	resp, err := client.Do(req)
	if err != nil {
		return nil, 0, err
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, resp.StatusCode, err
	}

	return respBody, resp.StatusCode, nil
}

// createFIBOSchema creates a sample FIBO deal schema for testing.
func createFIBOSchema() BOSSchemaPayload {
	return BOSSchemaPayload{
		SchemaName:    "test_fibo_deal",
		SchemaVersion: "1.0.0",
		Tables: []TableDefinition{
			{
				Name: "fibo_deal",
				Columns: []ColumnDefinition{
					{Name: "deal_id", Type: "UUID", Required: true, PrimaryKey: true},
					{Name: "deal_name", Type: "VARCHAR", Required: true},
					{Name: "deal_type", Type: "VARCHAR", Required: false},
					{Name: "principal_amount", Type: "DECIMAL", Required: false},
					{Name: "currency", Type: "VARCHAR", Required: false},
					{Name: "status", Type: "VARCHAR", Required: false},
					{Name: "created_at", Type: "TIMESTAMP", Required: false},
				},
				Indexes: []IndexDefinition{
					{Name: "idx_deal_status", Columns: []string{"status"}, Unique: false},
					{Name: "idx_deal_created", Columns: []string{"created_at"}, Unique: false},
				},
			},
			{
				Name: "fibo_party",
				Columns: []ColumnDefinition{
					{Name: "party_id", Type: "UUID", Required: true, PrimaryKey: true},
					{Name: "party_name", Type: "VARCHAR", Required: true},
					{Name: "party_type", Type: "VARCHAR", Required: false},
					{Name: "legal_entity_id", Type: "VARCHAR", Required: false},
				},
				Indexes: []IndexDefinition{
					{Name: "idx_party_type", Columns: []string{"party_type"}, Unique: false},
				},
			},
		},
		Metadata: map[string]interface{}{
			"domain":        "FIBO",
			"framework":     "Financial Ontology",
			"compliance":    "FIBO-compliant",
			"version_major": 2024,
		},
	}
}

// createHealthcareSchema creates a sample healthcare schema for testing.
func createHealthcareSchema() BOSSchemaPayload {
	return BOSSchemaPayload{
		SchemaName:    "test_healthcare_phi",
		SchemaVersion: "1.0.0",
		Tables: []TableDefinition{
			{
				Name: "healthcare_patient",
				Columns: []ColumnDefinition{
					{Name: "patient_id", Type: "UUID", Required: true, PrimaryKey: true},
					{Name: "patient_name", Type: "VARCHAR", Required: true},
					{Name: "date_of_birth", Type: "DATE", Required: false},
					{Name: "mrn", Type: "VARCHAR", Required: false},
				},
			},
			{
				Name: "healthcare_encounter",
				Columns: []ColumnDefinition{
					{Name: "encounter_id", Type: "UUID", Required: true, PrimaryKey: true},
					{Name: "patient_id", Type: "UUID", Required: true},
					{Name: "encounter_type", Type: "VARCHAR", Required: false},
					{Name: "encounter_date", Type: "TIMESTAMP", Required: false},
				},
			},
			{
				Name: "healthcare_phi_audit",
				Columns: []ColumnDefinition{
					{Name: "audit_id", Type: "UUID", Required: true, PrimaryKey: true},
					{Name: "patient_id", Type: "UUID", Required: true},
					{Name: "encounter_id", Type: "UUID", Required: false},
					{Name: "phi_accessed_at", Type: "TIMESTAMP", Required: false},
					{Name: "accessed_by", Type: "VARCHAR", Required: false},
					{Name: "access_reason", Type: "VARCHAR", Required: false},
				},
			},
		},
		Metadata: map[string]interface{}{
			"domain":      "Healthcare",
			"compliance":  "HIPAA",
			"phi_tracked": true,
		},
	}
}

// ============================================================================
// Test Cases
// ============================================================================

// TestBOSSchemaImportRoundTrip verifies that a schema imported via bos can be exported and re-imported.
func TestBOSSchemaImportRoundTrip(t *testing.T) {
	schema := createFIBOSchema()
	_, _ = json.Marshal(schema) // Ensure schema is valid JSON

	// Step 1: Import schema via BusinessOS API
	importReq := map[string]interface{}{
		"schema": schema,
		"format": "json",
	}
	startTime := time.Now()
	respBody, statusCode, err := makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/import", businessOSURL),
		importReq,
	)
	importDuration := time.Since(startTime)

	if err != nil {
		t.Logf("SKIP: BusinessOS not available (%v)", err)
		t.SkipNow()
	}

	if statusCode != http.StatusOK && statusCode != http.StatusCreated {
		t.Logf("Import failed with status %d: %s", statusCode, string(respBody))
		t.FailNow()
	}

	var importResp BOSImportResponse
	if err := json.Unmarshal(respBody, &importResp); err != nil {
		t.Logf("Failed to parse import response: %v", err)
		t.FailNow()
	}

	t.Logf("Import completed in %d ms", importResp.DurationMs)
	if importResp.DurationMs > 500 {
		t.Logf("WARNING: Import took %d ms (SLA: ≤500ms)", importResp.DurationMs)
	}

	if importResp.Status != "ok" && importResp.Status != "success" {
		t.Logf("Import status not success: %s", importResp.Status)
		t.FailNow()
	}

	schemaID := importResp.SchemaID

	// Step 2: Export schema
	startTime = time.Now()
	respBody, statusCode, err = makeRequest(
		"GET",
		fmt.Sprintf("%s/api/bos/schema/export/%s?format=json", businessOSURL, schemaID),
		nil,
	)
	exportDuration := time.Since(startTime)

	if statusCode != http.StatusOK {
		t.Logf("Export failed with status %d: %s", statusCode, string(respBody))
		t.FailNow()
	}

	var exportResp BOSExportResponse
	if err := json.Unmarshal(respBody, &exportResp); err != nil {
		t.Logf("Failed to parse export response: %v", err)
		t.FailNow()
	}

	t.Logf("Export completed in %d ms", exportResp.DurationMs)
	if exportResp.DurationMs > 200 {
		t.Logf("WARNING: Export took %d ms (SLA: ≤200ms)", exportResp.DurationMs)
	}

	// Step 3: Re-import exported schema
	re_importReq := map[string]interface{}{
		"data":   exportResp.Data,
		"format": "json",
	}
	startTime = time.Now()
	respBody, statusCode, err = makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/import", businessOSURL),
		re_importReq,
	)
	reimportDuration := time.Since(startTime)

	if statusCode != http.StatusOK && statusCode != http.StatusCreated {
		t.Logf("Re-import failed with status %d: %s", statusCode, string(respBody))
		t.FailNow()
	}

	var reimportResp BOSImportResponse
	if err := json.Unmarshal(respBody, &reimportResp); err != nil {
		t.Logf("Failed to parse re-import response: %v", err)
		t.FailNow()
	}

	// Verify content hash matches (data integrity)
	if importResp.ContentHash != "" && reimportResp.ContentHash != "" {
		if importResp.ContentHash != reimportResp.ContentHash {
			t.Logf("Content hash mismatch: %s != %s", importResp.ContentHash, reimportResp.ContentHash)
			t.FailNow()
		}
	}

	t.Logf("Round-trip test completed: import=%dms, export=%dms, reimport=%dms",
		importDuration.Milliseconds(), exportDuration.Milliseconds(), reimportDuration.Milliseconds())
}

// TestBOSSchemaUpdateAndValidate verifies schema update and validation operations.
func TestBOSSchemaUpdateAndValidate(t *testing.T) {
	schema := createFIBOSchema()

	// Step 1: Import original schema
	importReq := map[string]interface{}{
		"schema": schema,
		"format": "json",
	}
	respBody, statusCode, _ := makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/import", businessOSURL),
		importReq,
	)

	if statusCode != http.StatusOK && statusCode != http.StatusCreated {
		t.Logf("SKIP: Import failed with status %d", statusCode)
		t.SkipNow()
	}

	var importResp BOSImportResponse
	if err := json.Unmarshal(respBody, &importResp); err != nil {
		t.Logf("Failed to parse import response: %v", err)
		t.FailNow()
	}

	schemaID := importResp.SchemaID

	// Step 2: Validate schema
	startTime := time.Now()
	respBody, statusCode, _ = makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/validate/%s", businessOSURL, schemaID),
		nil,
	)
	validateDuration := time.Since(startTime)

	if statusCode != http.StatusOK {
		t.Logf("Validation failed with status %d: %s", statusCode, string(respBody))
		t.FailNow()
	}

	var validateResp map[string]interface{}
	if err := json.Unmarshal(respBody, &validateResp); err != nil {
		t.Logf("Failed to parse validation response: %v", err)
		t.FailNow()
	}

	if validateDuration > 200*time.Millisecond {
		t.Logf("WARNING: Validation took %d ms (SLA: ≤200ms)", validateDuration.Milliseconds())
	}

	t.Logf("Schema validation completed in %d ms", validateDuration.Milliseconds())

	// Step 3: Update schema (add new column)
	updateSchema := schema
	updateSchema.Tables[0].Columns = append(updateSchema.Tables[0].Columns,
		ColumnDefinition{Name: "deal_counterparty", Type: "VARCHAR", Required: false})

	updateReq := map[string]interface{}{
		"schema_id": schemaID,
		"schema":    updateSchema,
		"format":    "json",
	}
	startTime = time.Now()
	respBody, statusCode, _ = makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/update", businessOSURL),
		updateReq,
	)
	updateDuration := time.Since(startTime)

	if statusCode != http.StatusOK && statusCode != http.StatusAccepted {
		t.Logf("Update failed with status %d: %s", statusCode, string(respBody))
		t.FailNow()
	}

	t.Logf("Schema update completed in %d ms", updateDuration.Milliseconds())

	// Step 4: Re-validate after update
	respBody, statusCode, _ = makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/validate/%s", businessOSURL, schemaID),
		nil,
	)

	if statusCode != http.StatusOK {
		t.Logf("Post-update validation failed with status %d", statusCode)
		t.FailNow()
	}

	t.Logf("Post-update validation passed")
}

// TestBOSRDFExportAndOxigraphQuery verifies RDF export and SPARQL query integration.
func TestBOSRDFExportAndOxigraphQuery(t *testing.T) {
	schema := createFIBOSchema()

	// Step 1: Import schema and trigger RDF generation
	importReq := map[string]interface{}{
		"schema": schema,
		"format": "json",
	}
	respBody, statusCode, _ := makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/import?generate_rdf=true", businessOSURL),
		importReq,
	)

	if statusCode != http.StatusOK && statusCode != http.StatusCreated {
		t.Logf("SKIP: Import failed with status %d", statusCode)
		t.SkipNow()
	}

	var importResp BOSImportResponse
	if err := json.Unmarshal(respBody, &importResp); err != nil {
		t.Logf("Failed to parse import response: %v", err)
		t.FailNow()
	}

	schemaID := importResp.SchemaID
	t.Logf("Schema imported with %d RDF triples", importResp.RDFTriples)

	// Step 2: Export as RDF
	startTime := time.Now()
	respBody, statusCode, _ = makeRequest(
		"GET",
		fmt.Sprintf("%s/api/bos/schema/export/%s?format=rdf", businessOSURL, schemaID),
		nil,
	)
	exportDuration := time.Since(startTime)

	if statusCode != http.StatusOK {
		t.Logf("RDF export failed with status %d", statusCode)
		t.FailNow()
	}

	var exportResp BOSExportResponse
	if err := json.Unmarshal(respBody, &exportResp); err != nil {
		t.Logf("Failed to parse export response: %v", err)
		t.FailNow()
	}

	t.Logf("RDF export completed in %d ms", exportDuration.Milliseconds())

	// Step 3: Query Oxigraph for indexed triples
	sparqlQuery := `
		SELECT ?s ?p ?o
		WHERE {
			?s ?p ?o .
			FILTER regex(str(?s), "deal|party|fibo")
		}
		LIMIT 10
	`

	queryReq := OxigraphQuery{Query: sparqlQuery}
	startTime = time.Now()
	respBody, statusCode, err := makeRequest(
		"POST",
		fmt.Sprintf("%s/api/query", oxigraphURL),
		queryReq,
	)
	queryDuration := time.Since(startTime)

	if err != nil {
		t.Logf("SKIP: Oxigraph not available (%v)", err)
		t.SkipNow()
	}

	if statusCode != http.StatusOK {
		t.Logf("SPARQL query failed with status %d", statusCode)
		t.FailNow()
	}

	if queryDuration > 200*time.Millisecond {
		t.Logf("WARNING: SPARQL query took %d ms (SLA: ≤200ms)", queryDuration.Milliseconds())
	}

	t.Logf("SPARQL query completed in %d ms", queryDuration.Milliseconds())
}

// TestBOSHealthcareSchemaImport verifies healthcare schema import with HIPAA tracking.
func TestBOSHealthcareSchemaImport(t *testing.T) {
	schema := createHealthcareSchema()

	// Step 1: Import healthcare schema
	importReq := map[string]interface{}{
		"schema": schema,
		"format": "json",
	}
	respBody, statusCode, _ := makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/import", businessOSURL),
		importReq,
	)

	if statusCode != http.StatusOK && statusCode != http.StatusCreated {
		t.Logf("SKIP: Import failed with status %d", statusCode)
		t.SkipNow()
	}

	var importResp BOSImportResponse
	if err := json.Unmarshal(respBody, &importResp); err != nil {
		t.Logf("Failed to parse import response: %v", err)
		t.FailNow()
	}

	if importResp.Status != "ok" && importResp.Status != "success" {
		t.Logf("Import failed with status: %s", importResp.Status)
		t.FailNow()
	}

	// Verify that healthcare_phi_audit table was created
	if importResp.TablesImported < 3 {
		t.Logf("Expected at least 3 tables imported, got %d", importResp.TablesImported)
		t.FailNow()
	}

	t.Logf("Healthcare schema imported successfully: %d tables", importResp.TablesImported)
}

// TestBOSTimingAssertions verifies that all operations meet SLA requirements.
func TestBOSTimingAssertions(t *testing.T) {
	schema := createFIBOSchema()

	timings := map[string]int64{
		"import": 500,  // ms
		"export": 200,  // ms
		"query":  200,  // ms
	}

	// Step 1: Test import timing
	importReq := map[string]interface{}{
		"schema": schema,
		"format": "json",
	}
	startTime := time.Now()
	respBody, statusCode, _ := makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/import", businessOSURL),
		importReq,
	)
	importDuration := time.Since(startTime).Milliseconds()

	if statusCode != http.StatusOK && statusCode != http.StatusCreated {
		t.Logf("SKIP: Import failed with status %d", statusCode)
		t.SkipNow()
	}

	var importResp BOSImportResponse
	if err := json.Unmarshal(respBody, &importResp); err != nil {
		t.Logf("Failed to parse import response: %v", err)
		t.FailNow()
	}

	if importDuration > timings["import"] {
		t.Logf("FAIL: Import timing %d ms exceeds SLA of %d ms", importDuration, timings["import"])
		t.FailNow()
	}

	schemaID := importResp.SchemaID

	// Step 2: Test export timing
	startTime = time.Now()
	respBody, statusCode, _ = makeRequest(
		"GET",
		fmt.Sprintf("%s/api/bos/schema/export/%s?format=json", businessOSURL, schemaID),
		nil,
	)
	exportDuration := time.Since(startTime).Milliseconds()

	if statusCode != http.StatusOK {
		t.Logf("Export failed with status %d", statusCode)
		t.FailNow()
	}

	if exportDuration > timings["export"] {
		t.Logf("FAIL: Export timing %d ms exceeds SLA of %d ms", exportDuration, timings["export"])
		t.FailNow()
	}

	// Step 3: Test query timing
	queryReq := map[string]interface{}{
		"schema_id": schemaID,
		"query":     "SELECT * FROM fibo_deal LIMIT 10",
	}
	startTime = time.Now()
	respBody, statusCode, _ = makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/query", businessOSURL),
		queryReq,
	)
	queryDuration := time.Since(startTime).Milliseconds()

	if statusCode != http.StatusOK {
		t.Logf("Query failed with status %d", statusCode)
		t.FailNow()
	}

	if queryDuration > timings["query"] {
		t.Logf("FAIL: Query timing %d ms exceeds SLA of %d ms", queryDuration, timings["query"])
		t.FailNow()
	}

	t.Logf("All timing assertions passed: import=%dms, export=%dms, query=%dms",
		importDuration, exportDuration, queryDuration)
}

// TestBOSDataIntegrityAcrossOperations verifies that data is not corrupted across operations.
func TestBOSDataIntegrityAcrossOperations(t *testing.T) {
	schema := createFIBOSchema()
	schemaBytes, _ := json.Marshal(schema)

	// Step 1: Import with initial hash
	importReq := map[string]interface{}{
		"schema": schema,
		"format": "json",
	}
	respBody, statusCode, _ := makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/import", businessOSURL),
		importReq,
	)

	if statusCode != http.StatusOK && statusCode != http.StatusCreated {
		t.Logf("SKIP: Import failed with status %d", statusCode)
		t.SkipNow()
	}

	var importResp BOSImportResponse
	if err := json.Unmarshal(respBody, &importResp); err != nil {
		t.Logf("Failed to parse import response: %v", err)
		t.FailNow()
	}

	initialHash := importResp.ContentHash
	schemaID := importResp.SchemaID
	t.Logf("Initial content hash: %s", initialHash)

	// Step 2: Export and verify hash
	respBody, statusCode, _ = makeRequest(
		"GET",
		fmt.Sprintf("%s/api/bos/schema/export/%s?format=json", businessOSURL, schemaID),
		nil,
	)

	if statusCode != http.StatusOK {
		t.Logf("Export failed with status %d", statusCode)
		t.FailNow()
	}

	var exportResp BOSExportResponse
	if err := json.Unmarshal(respBody, &exportResp); err != nil {
		t.Logf("Failed to parse export response: %v", err)
		t.FailNow()
	}

	// Parse exported data
	var exportedSchema BOSSchemaPayload
	if err := json.Unmarshal([]byte(exportResp.Data), &exportedSchema); err != nil {
		// Try raw string comparison if not valid JSON
		if string(schemaBytes) != exportResp.Data {
			t.Logf("Exported data does not match imported data")
			t.FailNow()
		}
	}

	// Step 3: Re-import and check hash consistency
	reimportReq := map[string]interface{}{
		"data":   exportResp.Data,
		"format": "json",
	}
	respBody, statusCode, _ = makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/import", businessOSURL),
		reimportReq,
	)

	if statusCode != http.StatusOK && statusCode != http.StatusCreated {
		t.Logf("Re-import failed with status %d", statusCode)
		t.FailNow()
	}

	var reimportResp BOSImportResponse
	if err := json.Unmarshal(respBody, &reimportResp); err != nil {
		t.Logf("Failed to parse re-import response: %v", err)
		t.FailNow()
	}

	if initialHash != "" && reimportResp.ContentHash != "" {
		if initialHash != reimportResp.ContentHash {
			t.Logf("Content hash mismatch after round-trip: %s != %s", initialHash, reimportResp.ContentHash)
			t.FailNow()
		}
	}

	t.Logf("Data integrity verified: hash consistent after round-trip")
}

// TestBOSMultipleSchemaImports verifies that multiple schemas can coexist in the system.
func TestBOSMultipleSchemaImports(t *testing.T) {
	fiboSchema := createFIBOSchema()
	healthcareSchema := createHealthcareSchema()

	// Step 1: Import FIBO schema
	fiboReq := map[string]interface{}{
		"schema": fiboSchema,
		"format": "json",
	}
	respBody, statusCode, _ := makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/import", businessOSURL),
		fiboReq,
	)

	if statusCode != http.StatusOK && statusCode != http.StatusCreated {
		t.Logf("SKIP: FIBO import failed with status %d", statusCode)
		t.SkipNow()
	}

	var fiboResp BOSImportResponse
	if err := json.Unmarshal(respBody, &fiboResp); err != nil {
		t.Logf("Failed to parse FIBO import response: %v", err)
		t.FailNow()
	}

	fiboID := fiboResp.SchemaID

	// Step 2: Import healthcare schema
	healthcareReq := map[string]interface{}{
		"schema": healthcareSchema,
		"format": "json",
	}
	respBody, statusCode, _ = makeRequest(
		"POST",
		fmt.Sprintf("%s/api/bos/schema/import", businessOSURL),
		healthcareReq,
	)

	if statusCode != http.StatusOK && statusCode != http.StatusCreated {
		t.Logf("Healthcare import failed with status %d", statusCode)
		t.FailNow()
	}

	var healthcareResp BOSImportResponse
	if err := json.Unmarshal(respBody, &healthcareResp); err != nil {
		t.Logf("Failed to parse healthcare import response: %v", err)
		t.FailNow()
	}

	healthcareID := healthcareResp.SchemaID

	// Step 3: Verify both schemas exist independently
	respBody, statusCode, _ = makeRequest(
		"GET",
		fmt.Sprintf("%s/api/bos/schema/export/%s?format=json", businessOSURL, fiboID),
		nil,
	)

	if statusCode != http.StatusOK {
		t.Logf("Failed to retrieve FIBO schema: status %d", statusCode)
		t.FailNow()
	}

	respBody, statusCode, _ = makeRequest(
		"GET",
		fmt.Sprintf("%s/api/bos/schema/export/%s?format=json", businessOSURL, healthcareID),
		nil,
	)

	if statusCode != http.StatusOK {
		t.Logf("Failed to retrieve healthcare schema: status %d", statusCode)
		t.FailNow()
	}

	t.Logf("Successfully imported and verified multiple schemas: FIBO=%s, Healthcare=%s", fiboID, healthcareID)
}

// TestBOSCLICompatibility verifies that bos CLI output is compatible with BusinessOS API parsing.
func TestBOSCLICompatibility(t *testing.T) {
	// This test verifies that if bos CLI is available, its output format
	// matches what BusinessOS expects for import operations.

	tempDir := filepath.Join(os.TempDir(), "bos-integration-test")
	if err := os.MkdirAll(tempDir, 0755); err != nil {
		t.Logf("Failed to create temp directory: %v", err)
		t.FailNow()
	}
	defer os.RemoveAll(tempDir)

	schema := createFIBOSchema()
	schemaFile := filepath.Join(tempDir, "test_schema.json")

	schemaBytes, _ := json.MarshalIndent(schema, "", "  ")
	if err := os.WriteFile(schemaFile, schemaBytes, 0644); err != nil {
		t.Logf("Failed to write schema file: %v", err)
		t.FailNow()
	}

	t.Logf("Schema file created at: %s", schemaFile)
	// If bos CLI is available in PATH, additional validation can be performed here
}
