package middleware

import (
	"github.com/gin-gonic/gin"
)

// =============================================================================
// DEVICE ID MIDDLEWARE
// =============================================================================
// Mobile clients send X-Device-ID header to identify their device.
// This is useful for:
// 1. Per-device rate limiting (prevent one device from exhausting limits)
// 2. Push notification token association
// 3. Analytics (track which devices are most active)
// 4. Multi-device sync conflict resolution
//
// The device ID is a UUID generated by the client on first launch and stored
// locally. It persists across app sessions but changes on reinstall.
// =============================================================================

const (
	// DeviceIDHeader is the HTTP header name for device identification
	DeviceIDHeader = "X-Device-ID"

	// DeviceIDContextKey is the gin context key for storing the device ID
	DeviceIDContextKey = "device_id"
)

// DeviceIDMiddleware extracts the X-Device-ID header and stores it in context
// The device ID is optional - if not provided, an empty string is stored
func DeviceIDMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		deviceID := c.GetHeader(DeviceIDHeader)
		c.Set(DeviceIDContextKey, deviceID)
		c.Next()
	}
}

// GetDeviceID retrieves the device ID from the gin context
// Returns empty string if not set
func GetDeviceID(c *gin.Context) string {
	deviceID, exists := c.Get(DeviceIDContextKey)
	if !exists {
		return ""
	}
	return deviceID.(string)
}

// HasDeviceID checks if a device ID was provided in the request
func HasDeviceID(c *gin.Context) bool {
	return GetDeviceID(c) != ""
}
