// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contexts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveContext = `-- name: ArchiveContext :one
UPDATE contexts
SET is_archived = TRUE, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, type, content, structured_data, system_prompt_template, blocks, cover_image, icon, parent_id, is_template, is_archived, last_edited_at, word_count, is_public, share_id, property_schema, properties, client_id, created_at, updated_at
`

func (q *Queries) ArchiveContext(ctx context.Context, id pgtype.UUID) (Context, error) {
	row := q.db.QueryRow(ctx, archiveContext, id)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.StructuredData,
		&i.SystemPromptTemplate,
		&i.Blocks,
		&i.CoverImage,
		&i.Icon,
		&i.ParentID,
		&i.IsTemplate,
		&i.IsArchived,
		&i.LastEditedAt,
		&i.WordCount,
		&i.IsPublic,
		&i.ShareID,
		&i.PropertySchema,
		&i.Properties,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContext = `-- name: CreateContext :one
INSERT INTO contexts (id, user_id, name, type, content, structured_data, system_prompt_template, blocks, cover_image, icon, parent_id, is_template, property_schema, properties, client_id, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NOW(), NOW())
RETURNING id, user_id, name, type, content, structured_data, system_prompt_template, blocks, cover_image, icon, parent_id, is_template, is_archived, last_edited_at, word_count, is_public, share_id, property_schema, properties, client_id, created_at, updated_at
`

type CreateContextParams struct {
	UserID               string          `json:"user_id"`
	Name                 string          `json:"name"`
	Type                 NullContexttype `json:"type"`
	Content              *string         `json:"content"`
	StructuredData       []byte          `json:"structured_data"`
	SystemPromptTemplate *string         `json:"system_prompt_template"`
	Blocks               []byte          `json:"blocks"`
	CoverImage           *string         `json:"cover_image"`
	Icon                 *string         `json:"icon"`
	ParentID             pgtype.UUID     `json:"parent_id"`
	IsTemplate           *bool           `json:"is_template"`
	PropertySchema       []byte          `json:"property_schema"`
	Properties           []byte          `json:"properties"`
	ClientID             pgtype.UUID     `json:"client_id"`
}

func (q *Queries) CreateContext(ctx context.Context, arg CreateContextParams) (Context, error) {
	row := q.db.QueryRow(ctx, createContext,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Content,
		arg.StructuredData,
		arg.SystemPromptTemplate,
		arg.Blocks,
		arg.CoverImage,
		arg.Icon,
		arg.ParentID,
		arg.IsTemplate,
		arg.PropertySchema,
		arg.Properties,
		arg.ClientID,
	)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.StructuredData,
		&i.SystemPromptTemplate,
		&i.Blocks,
		&i.CoverImage,
		&i.Icon,
		&i.ParentID,
		&i.IsTemplate,
		&i.IsArchived,
		&i.LastEditedAt,
		&i.WordCount,
		&i.IsPublic,
		&i.ShareID,
		&i.PropertySchema,
		&i.Properties,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContext = `-- name: DeleteContext :exec
DELETE FROM contexts
WHERE id = $1 AND user_id = $2
`

type DeleteContextParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteContext(ctx context.Context, arg DeleteContextParams) error {
	_, err := q.db.Exec(ctx, deleteContext, arg.ID, arg.UserID)
	return err
}

const getContext = `-- name: GetContext :one
SELECT id, user_id, name, type, content, structured_data, system_prompt_template, blocks, cover_image, icon, parent_id, is_template, is_archived, last_edited_at, word_count, is_public, share_id, property_schema, properties, client_id, created_at, updated_at FROM contexts
WHERE id = $1 AND user_id = $2
`

type GetContextParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetContext(ctx context.Context, arg GetContextParams) (Context, error) {
	row := q.db.QueryRow(ctx, getContext, arg.ID, arg.UserID)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.StructuredData,
		&i.SystemPromptTemplate,
		&i.Blocks,
		&i.CoverImage,
		&i.Icon,
		&i.ParentID,
		&i.IsTemplate,
		&i.IsArchived,
		&i.LastEditedAt,
		&i.WordCount,
		&i.IsPublic,
		&i.ShareID,
		&i.PropertySchema,
		&i.Properties,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContextChildren = `-- name: GetContextChildren :many
SELECT id, user_id, name, type, content, structured_data, system_prompt_template, blocks, cover_image, icon, parent_id, is_template, is_archived, last_edited_at, word_count, is_public, share_id, property_schema, properties, client_id, created_at, updated_at FROM contexts
WHERE parent_id = $1 AND user_id = $2
ORDER BY name ASC
`

type GetContextChildrenParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	UserID   string      `json:"user_id"`
}

func (q *Queries) GetContextChildren(ctx context.Context, arg GetContextChildrenParams) ([]Context, error) {
	rows, err := q.db.Query(ctx, getContextChildren, arg.ParentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Context{}
	for rows.Next() {
		var i Context
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Content,
			&i.StructuredData,
			&i.SystemPromptTemplate,
			&i.Blocks,
			&i.CoverImage,
			&i.Icon,
			&i.ParentID,
			&i.IsTemplate,
			&i.IsArchived,
			&i.LastEditedAt,
			&i.WordCount,
			&i.IsPublic,
			&i.ShareID,
			&i.PropertySchema,
			&i.Properties,
			&i.ClientID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicContext = `-- name: GetPublicContext :one
SELECT id, user_id, name, type, content, structured_data, system_prompt_template, blocks, cover_image, icon, parent_id, is_template, is_archived, last_edited_at, word_count, is_public, share_id, property_schema, properties, client_id, created_at, updated_at FROM contexts
WHERE share_id = $1 AND is_public = TRUE
`

func (q *Queries) GetPublicContext(ctx context.Context, shareID *string) (Context, error) {
	row := q.db.QueryRow(ctx, getPublicContext, shareID)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.StructuredData,
		&i.SystemPromptTemplate,
		&i.Blocks,
		&i.CoverImage,
		&i.Icon,
		&i.ParentID,
		&i.IsTemplate,
		&i.IsArchived,
		&i.LastEditedAt,
		&i.WordCount,
		&i.IsPublic,
		&i.ShareID,
		&i.PropertySchema,
		&i.Properties,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContexts = `-- name: ListContexts :many
SELECT id, user_id, name, type, content, structured_data, system_prompt_template, blocks, cover_image, icon, parent_id, is_template, is_archived, last_edited_at, word_count, is_public, share_id, property_schema, properties, client_id, created_at, updated_at FROM contexts
WHERE user_id = $1
  AND ($2::boolean IS NULL OR is_archived = $2)
  AND ($3::contexttype IS NULL OR type = $3)
  AND ($4::boolean IS NULL OR is_template = $4)
  AND ($5::text IS NULL OR name ILIKE '%' || $5 || '%')
ORDER BY updated_at DESC
`

type ListContextsParams struct {
	UserID      string          `json:"user_id"`
	IsArchived  *bool           `json:"is_archived"`
	ContextType NullContexttype `json:"context_type"`
	IsTemplate  *bool           `json:"is_template"`
	Search      *string         `json:"search"`
}

func (q *Queries) ListContexts(ctx context.Context, arg ListContextsParams) ([]Context, error) {
	rows, err := q.db.Query(ctx, listContexts,
		arg.UserID,
		arg.IsArchived,
		arg.ContextType,
		arg.IsTemplate,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Context{}
	for rows.Next() {
		var i Context
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Content,
			&i.StructuredData,
			&i.SystemPromptTemplate,
			&i.Blocks,
			&i.CoverImage,
			&i.Icon,
			&i.ParentID,
			&i.IsTemplate,
			&i.IsArchived,
			&i.LastEditedAt,
			&i.WordCount,
			&i.IsPublic,
			&i.ShareID,
			&i.PropertySchema,
			&i.Properties,
			&i.ClientID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shareContext = `-- name: ShareContext :one
UPDATE contexts
SET is_public = TRUE, share_id = $2
WHERE id = $1
RETURNING id, user_id, name, type, content, structured_data, system_prompt_template, blocks, cover_image, icon, parent_id, is_template, is_archived, last_edited_at, word_count, is_public, share_id, property_schema, properties, client_id, created_at, updated_at
`

type ShareContextParams struct {
	ID      pgtype.UUID `json:"id"`
	ShareID *string     `json:"share_id"`
}

func (q *Queries) ShareContext(ctx context.Context, arg ShareContextParams) (Context, error) {
	row := q.db.QueryRow(ctx, shareContext, arg.ID, arg.ShareID)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.StructuredData,
		&i.SystemPromptTemplate,
		&i.Blocks,
		&i.CoverImage,
		&i.Icon,
		&i.ParentID,
		&i.IsTemplate,
		&i.IsArchived,
		&i.LastEditedAt,
		&i.WordCount,
		&i.IsPublic,
		&i.ShareID,
		&i.PropertySchema,
		&i.Properties,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const syncArtifactToContext = `-- name: SyncArtifactToContext :one
UPDATE contexts
SET content = CASE
      WHEN content IS NULL OR content = '' THEN $2
      ELSE content || E'\n\n---\n\n' || $2
    END,
    word_count = COALESCE(word_count, 0) + $3,
    last_edited_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, type, content, structured_data, system_prompt_template, blocks, cover_image, icon, parent_id, is_template, is_archived, last_edited_at, word_count, is_public, share_id, property_schema, properties, client_id, created_at, updated_at
`

type SyncArtifactToContextParams struct {
	ID        pgtype.UUID `json:"id"`
	Content   *string     `json:"content"`
	WordCount *int32      `json:"word_count"`
}

// Syncs artifact content to a context (appends or replaces based on use case)
func (q *Queries) SyncArtifactToContext(ctx context.Context, arg SyncArtifactToContextParams) (Context, error) {
	row := q.db.QueryRow(ctx, syncArtifactToContext, arg.ID, arg.Content, arg.WordCount)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.StructuredData,
		&i.SystemPromptTemplate,
		&i.Blocks,
		&i.CoverImage,
		&i.Icon,
		&i.ParentID,
		&i.IsTemplate,
		&i.IsArchived,
		&i.LastEditedAt,
		&i.WordCount,
		&i.IsPublic,
		&i.ShareID,
		&i.PropertySchema,
		&i.Properties,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unarchiveContext = `-- name: UnarchiveContext :one
UPDATE contexts
SET is_archived = FALSE, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, type, content, structured_data, system_prompt_template, blocks, cover_image, icon, parent_id, is_template, is_archived, last_edited_at, word_count, is_public, share_id, property_schema, properties, client_id, created_at, updated_at
`

func (q *Queries) UnarchiveContext(ctx context.Context, id pgtype.UUID) (Context, error) {
	row := q.db.QueryRow(ctx, unarchiveContext, id)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.StructuredData,
		&i.SystemPromptTemplate,
		&i.Blocks,
		&i.CoverImage,
		&i.Icon,
		&i.ParentID,
		&i.IsTemplate,
		&i.IsArchived,
		&i.LastEditedAt,
		&i.WordCount,
		&i.IsPublic,
		&i.ShareID,
		&i.PropertySchema,
		&i.Properties,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unshareContext = `-- name: UnshareContext :one
UPDATE contexts
SET is_public = FALSE, share_id = NULL
WHERE id = $1
RETURNING id, user_id, name, type, content, structured_data, system_prompt_template, blocks, cover_image, icon, parent_id, is_template, is_archived, last_edited_at, word_count, is_public, share_id, property_schema, properties, client_id, created_at, updated_at
`

func (q *Queries) UnshareContext(ctx context.Context, id pgtype.UUID) (Context, error) {
	row := q.db.QueryRow(ctx, unshareContext, id)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.StructuredData,
		&i.SystemPromptTemplate,
		&i.Blocks,
		&i.CoverImage,
		&i.Icon,
		&i.ParentID,
		&i.IsTemplate,
		&i.IsArchived,
		&i.LastEditedAt,
		&i.WordCount,
		&i.IsPublic,
		&i.ShareID,
		&i.PropertySchema,
		&i.Properties,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContext = `-- name: UpdateContext :one
UPDATE contexts
SET name = $2, type = $3, content = $4, structured_data = $5, system_prompt_template = $6,
    cover_image = $7, icon = $8, parent_id = $9, is_template = $10, property_schema = $11,
    properties = $12, client_id = $13, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, type, content, structured_data, system_prompt_template, blocks, cover_image, icon, parent_id, is_template, is_archived, last_edited_at, word_count, is_public, share_id, property_schema, properties, client_id, created_at, updated_at
`

type UpdateContextParams struct {
	ID                   pgtype.UUID     `json:"id"`
	Name                 string          `json:"name"`
	Type                 NullContexttype `json:"type"`
	Content              *string         `json:"content"`
	StructuredData       []byte          `json:"structured_data"`
	SystemPromptTemplate *string         `json:"system_prompt_template"`
	CoverImage           *string         `json:"cover_image"`
	Icon                 *string         `json:"icon"`
	ParentID             pgtype.UUID     `json:"parent_id"`
	IsTemplate           *bool           `json:"is_template"`
	PropertySchema       []byte          `json:"property_schema"`
	Properties           []byte          `json:"properties"`
	ClientID             pgtype.UUID     `json:"client_id"`
}

func (q *Queries) UpdateContext(ctx context.Context, arg UpdateContextParams) (Context, error) {
	row := q.db.QueryRow(ctx, updateContext,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Content,
		arg.StructuredData,
		arg.SystemPromptTemplate,
		arg.CoverImage,
		arg.Icon,
		arg.ParentID,
		arg.IsTemplate,
		arg.PropertySchema,
		arg.Properties,
		arg.ClientID,
	)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.StructuredData,
		&i.SystemPromptTemplate,
		&i.Blocks,
		&i.CoverImage,
		&i.Icon,
		&i.ParentID,
		&i.IsTemplate,
		&i.IsArchived,
		&i.LastEditedAt,
		&i.WordCount,
		&i.IsPublic,
		&i.ShareID,
		&i.PropertySchema,
		&i.Properties,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContextBlocks = `-- name: UpdateContextBlocks :one
UPDATE contexts
SET blocks = $2, word_count = $3, last_edited_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, type, content, structured_data, system_prompt_template, blocks, cover_image, icon, parent_id, is_template, is_archived, last_edited_at, word_count, is_public, share_id, property_schema, properties, client_id, created_at, updated_at
`

type UpdateContextBlocksParams struct {
	ID        pgtype.UUID `json:"id"`
	Blocks    []byte      `json:"blocks"`
	WordCount *int32      `json:"word_count"`
}

func (q *Queries) UpdateContextBlocks(ctx context.Context, arg UpdateContextBlocksParams) (Context, error) {
	row := q.db.QueryRow(ctx, updateContextBlocks, arg.ID, arg.Blocks, arg.WordCount)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.StructuredData,
		&i.SystemPromptTemplate,
		&i.Blocks,
		&i.CoverImage,
		&i.Icon,
		&i.ParentID,
		&i.IsTemplate,
		&i.IsArchived,
		&i.LastEditedAt,
		&i.WordCount,
		&i.IsPublic,
		&i.ShareID,
		&i.PropertySchema,
		&i.Properties,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
