// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: custom_agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCustomAgents = `-- name: ListCustomAgents :many
SELECT id, user_id, name, display_name, description, avatar, system_prompt, model_preference, temperature, max_tokens, capabilities, tools_enabled, context_sources, thinking_enabled, streaming_enabled, category, is_public, is_active, times_used, last_used_at, created_at, updated_at FROM custom_agents
WHERE user_id = $1 AND is_active = TRUE
ORDER BY times_used DESC, display_name ASC
`

func (q *Queries) ListCustomAgents(ctx context.Context, userID string) ([]CustomAgent, error) {
	rows, err := q.db.Query(ctx, listCustomAgents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomAgent{}
	for rows.Next() {
		var i CustomAgent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Avatar,
			&i.SystemPrompt,
			&i.ModelPreference,
			&i.Temperature,
			&i.MaxTokens,
			&i.Capabilities,
			&i.ToolsEnabled,
			&i.ContextSources,
			&i.ThinkingEnabled,
			&i.StreamingEnabled,
			&i.Category,
			&i.IsPublic,
			&i.IsActive,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCustomAgents = `-- name: GetAllCustomAgents :many
SELECT id, user_id, name, display_name, description, avatar, system_prompt, model_preference, temperature, max_tokens, capabilities, tools_enabled, context_sources, thinking_enabled, streaming_enabled, category, is_public, is_active, times_used, last_used_at, created_at, updated_at FROM custom_agents
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllCustomAgents(ctx context.Context, userID string) ([]CustomAgent, error) {
	rows, err := q.db.Query(ctx, getAllCustomAgents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomAgent{}
	for rows.Next() {
		var i CustomAgent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Avatar,
			&i.SystemPrompt,
			&i.ModelPreference,
			&i.Temperature,
			&i.MaxTokens,
			&i.Capabilities,
			&i.ToolsEnabled,
			&i.ContextSources,
			&i.ThinkingEnabled,
			&i.StreamingEnabled,
			&i.Category,
			&i.IsPublic,
			&i.IsActive,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomAgent = `-- name: GetCustomAgent :one
SELECT id, user_id, name, display_name, description, avatar, system_prompt, model_preference, temperature, max_tokens, capabilities, tools_enabled, context_sources, thinking_enabled, streaming_enabled, category, is_public, is_active, times_used, last_used_at, created_at, updated_at FROM custom_agents
WHERE id = $1 AND user_id = $2
`

type GetCustomAgentParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetCustomAgent(ctx context.Context, arg GetCustomAgentParams) (CustomAgent, error) {
	row := q.db.QueryRow(ctx, getCustomAgent, arg.ID, arg.UserID)
	var i CustomAgent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Avatar,
		&i.SystemPrompt,
		&i.ModelPreference,
		&i.Temperature,
		&i.MaxTokens,
		&i.Capabilities,
		&i.ToolsEnabled,
		&i.ContextSources,
		&i.ThinkingEnabled,
		&i.StreamingEnabled,
		&i.Category,
		&i.IsPublic,
		&i.IsActive,
		&i.TimesUsed,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomAgentByName = `-- name: GetCustomAgentByName :one
SELECT id, user_id, name, display_name, description, avatar, system_prompt, model_preference, temperature, max_tokens, capabilities, tools_enabled, context_sources, thinking_enabled, streaming_enabled, category, is_public, is_active, times_used, last_used_at, created_at, updated_at FROM custom_agents
WHERE name = $1 AND user_id = $2 AND is_active = TRUE
`

type GetCustomAgentByNameParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetCustomAgentByName(ctx context.Context, arg GetCustomAgentByNameParams) (CustomAgent, error) {
	row := q.db.QueryRow(ctx, getCustomAgentByName, arg.Name, arg.UserID)
	var i CustomAgent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Avatar,
		&i.SystemPrompt,
		&i.ModelPreference,
		&i.Temperature,
		&i.MaxTokens,
		&i.Capabilities,
		&i.ToolsEnabled,
		&i.ContextSources,
		&i.ThinkingEnabled,
		&i.StreamingEnabled,
		&i.Category,
		&i.IsPublic,
		&i.IsActive,
		&i.TimesUsed,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomAgent = `-- name: CreateCustomAgent :one
INSERT INTO custom_agents (
    user_id, name, display_name, description, avatar,
    system_prompt, model_preference, temperature, max_tokens,
    capabilities, tools_enabled, context_sources,
    thinking_enabled, streaming_enabled, category, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, user_id, name, display_name, description, avatar, system_prompt, model_preference, temperature, max_tokens, capabilities, tools_enabled, context_sources, thinking_enabled, streaming_enabled, category, is_public, is_active, times_used, last_used_at, created_at, updated_at
`

type CreateCustomAgentParams struct {
	UserID           string         `json:"user_id"`
	Name             string         `json:"name"`
	DisplayName      string         `json:"display_name"`
	Description      *string        `json:"description"`
	Avatar           *string        `json:"avatar"`
	SystemPrompt     string         `json:"system_prompt"`
	ModelPreference  *string        `json:"model_preference"`
	Temperature      pgtype.Numeric `json:"temperature"`
	MaxTokens        *int32         `json:"max_tokens"`
	Capabilities     []string       `json:"capabilities"`
	ToolsEnabled     []string       `json:"tools_enabled"`
	ContextSources   []string       `json:"context_sources"`
	ThinkingEnabled  *bool          `json:"thinking_enabled"`
	StreamingEnabled *bool          `json:"streaming_enabled"`
	Category         *string        `json:"category"`
	IsActive         *bool          `json:"is_active"`
}

func (q *Queries) CreateCustomAgent(ctx context.Context, arg CreateCustomAgentParams) (CustomAgent, error) {
	row := q.db.QueryRow(ctx, createCustomAgent,
		arg.UserID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.Avatar,
		arg.SystemPrompt,
		arg.ModelPreference,
		arg.Temperature,
		arg.MaxTokens,
		arg.Capabilities,
		arg.ToolsEnabled,
		arg.ContextSources,
		arg.ThinkingEnabled,
		arg.StreamingEnabled,
		arg.Category,
		arg.IsActive,
	)
	var i CustomAgent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Avatar,
		&i.SystemPrompt,
		&i.ModelPreference,
		&i.Temperature,
		&i.MaxTokens,
		&i.Capabilities,
		&i.ToolsEnabled,
		&i.ContextSources,
		&i.ThinkingEnabled,
		&i.StreamingEnabled,
		&i.Category,
		&i.IsPublic,
		&i.IsActive,
		&i.TimesUsed,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomAgent = `-- name: DeleteCustomAgent :exec
DELETE FROM custom_agents
WHERE id = $1 AND user_id = $2
`

type DeleteCustomAgentParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteCustomAgent(ctx context.Context, arg DeleteCustomAgentParams) error {
	_, err := q.db.Exec(ctx, deleteCustomAgent, arg.ID, arg.UserID)
	return err
}

const incrementAgentUsage = `-- name: IncrementAgentUsage :exec
UPDATE custom_agents
SET times_used = times_used + 1, last_used_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementAgentUsage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementAgentUsage, id)
	return err
}

// ===== AGENT PRESETS =====

const listAgentPresets = `-- name: ListAgentPresets :many
SELECT id, name, display_name, description, avatar, system_prompt, model_preference, temperature, max_tokens, capabilities, tools_enabled, context_sources, thinking_enabled, category, times_copied, created_at, updated_at FROM agent_presets
ORDER BY times_copied DESC, display_name ASC
`

func (q *Queries) ListAgentPresets(ctx context.Context) ([]AgentPreset, error) {
	rows, err := q.db.Query(ctx, listAgentPresets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentPreset{}
	for rows.Next() {
		var i AgentPreset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Avatar,
			&i.SystemPrompt,
			&i.ModelPreference,
			&i.Temperature,
			&i.MaxTokens,
			&i.Capabilities,
			&i.ToolsEnabled,
			&i.ContextSources,
			&i.ThinkingEnabled,
			&i.Category,
			&i.TimesCopied,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentPreset = `-- name: GetAgentPreset :one
SELECT id, name, display_name, description, avatar, system_prompt, model_preference, temperature, max_tokens, capabilities, tools_enabled, context_sources, thinking_enabled, category, times_copied, created_at, updated_at FROM agent_presets
WHERE id = $1
`

func (q *Queries) GetAgentPreset(ctx context.Context, id pgtype.UUID) (AgentPreset, error) {
	row := q.db.QueryRow(ctx, getAgentPreset, id)
	var i AgentPreset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Avatar,
		&i.SystemPrompt,
		&i.ModelPreference,
		&i.Temperature,
		&i.MaxTokens,
		&i.Capabilities,
		&i.ToolsEnabled,
		&i.ContextSources,
		&i.ThinkingEnabled,
		&i.Category,
		&i.TimesCopied,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementPresetCopyCount = `-- name: IncrementPresetCopyCount :exec
UPDATE agent_presets
SET times_copied = times_copied + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementPresetCopyCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementPresetCopyCount, id)
	return err
}

// ===== UPDATE CUSTOM AGENT =====

const updateCustomAgent = `-- name: UpdateCustomAgent :one
UPDATE custom_agents
SET
    name = COALESCE($3, name),
    display_name = COALESCE($4, display_name),
    description = COALESCE($5, description),
    avatar = COALESCE($6, avatar),
    system_prompt = COALESCE($7, system_prompt),
    model_preference = COALESCE($8, model_preference),
    temperature = COALESCE($9, temperature),
    max_tokens = COALESCE($10, max_tokens),
    capabilities = COALESCE($11, capabilities),
    tools_enabled = COALESCE($12, tools_enabled),
    context_sources = COALESCE($13, context_sources),
    thinking_enabled = COALESCE($14, thinking_enabled),
    streaming_enabled = COALESCE($15, streaming_enabled),
    category = COALESCE($16, category),
    is_active = COALESCE($17, is_active),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, display_name, description, avatar, system_prompt, model_preference, temperature, max_tokens, capabilities, tools_enabled, context_sources, thinking_enabled, streaming_enabled, category, is_public, is_active, times_used, last_used_at, created_at, updated_at
`

type UpdateCustomAgentParams struct {
	ID               pgtype.UUID    `json:"id"`
	UserID           string         `json:"user_id"`
	Name             *string        `json:"name"`
	DisplayName      *string        `json:"display_name"`
	Description      *string        `json:"description"`
	Avatar           *string        `json:"avatar"`
	SystemPrompt     *string        `json:"system_prompt"`
	ModelPreference  *string        `json:"model_preference"`
	Temperature      pgtype.Numeric `json:"temperature"`
	MaxTokens        *int32         `json:"max_tokens"`
	Capabilities     []string       `json:"capabilities"`
	ToolsEnabled     []string       `json:"tools_enabled"`
	ContextSources   []string       `json:"context_sources"`
	ThinkingEnabled  *bool          `json:"thinking_enabled"`
	StreamingEnabled *bool          `json:"streaming_enabled"`
	Category         *string        `json:"category"`
	IsActive         *bool          `json:"is_active"`
}

func (q *Queries) UpdateCustomAgent(ctx context.Context, arg UpdateCustomAgentParams) (CustomAgent, error) {
	row := q.db.QueryRow(ctx, updateCustomAgent,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.Avatar,
		arg.SystemPrompt,
		arg.ModelPreference,
		arg.Temperature,
		arg.MaxTokens,
		arg.Capabilities,
		arg.ToolsEnabled,
		arg.ContextSources,
		arg.ThinkingEnabled,
		arg.StreamingEnabled,
		arg.Category,
		arg.IsActive,
	)
	var i CustomAgent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Avatar,
		&i.SystemPrompt,
		&i.ModelPreference,
		&i.Temperature,
		&i.MaxTokens,
		&i.Capabilities,
		&i.ToolsEnabled,
		&i.ContextSources,
		&i.ThinkingEnabled,
		&i.StreamingEnabled,
		&i.Category,
		&i.IsPublic,
		&i.IsActive,
		&i.TimesUsed,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// ===== LIST BY CATEGORY =====

const listCustomAgentsByCategory = `-- name: ListCustomAgentsByCategory :many
SELECT id, user_id, name, display_name, description, avatar, system_prompt, model_preference, temperature, max_tokens, capabilities, tools_enabled, context_sources, thinking_enabled, streaming_enabled, category, is_public, is_active, times_used, last_used_at, created_at, updated_at FROM custom_agents
WHERE user_id = $1 AND category = $2 AND is_active = TRUE
ORDER BY times_used DESC, display_name ASC
`

type ListCustomAgentsByCategoryParams struct {
	UserID   string  `json:"user_id"`
	Category *string `json:"category"`
}

func (q *Queries) ListCustomAgentsByCategory(ctx context.Context, arg ListCustomAgentsByCategoryParams) ([]CustomAgent, error) {
	rows, err := q.db.Query(ctx, listCustomAgentsByCategory, arg.UserID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomAgent{}
	for rows.Next() {
		var i CustomAgent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Avatar,
			&i.SystemPrompt,
			&i.ModelPreference,
			&i.Temperature,
			&i.MaxTokens,
			&i.Capabilities,
			&i.ToolsEnabled,
			&i.ContextSources,
			&i.ThinkingEnabled,
			&i.StreamingEnabled,
			&i.Category,
			&i.IsPublic,
			&i.IsActive,
			&i.TimesUsed,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ===== GET PRESET BY NAME =====

const getAgentPresetByName = `-- name: GetAgentPresetByName :one
SELECT id, name, display_name, description, avatar, system_prompt, model_preference, temperature, max_tokens, capabilities, tools_enabled, context_sources, thinking_enabled, category, times_copied, created_at, updated_at FROM agent_presets
WHERE name = $1
`

func (q *Queries) GetAgentPresetByName(ctx context.Context, name string) (AgentPreset, error) {
	row := q.db.QueryRow(ctx, getAgentPresetByName, name)
	var i AgentPreset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Avatar,
		&i.SystemPrompt,
		&i.ModelPreference,
		&i.Temperature,
		&i.MaxTokens,
		&i.Capabilities,
		&i.ToolsEnabled,
		&i.ContextSources,
		&i.ThinkingEnabled,
		&i.Category,
		&i.TimesCopied,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// ===== CREATE AGENT FROM PRESET =====

const createAgentFromPreset = `-- name: CreateAgentFromPreset :one
INSERT INTO custom_agents (
    user_id, name, display_name, description, avatar,
    system_prompt, model_preference, temperature, max_tokens,
    capabilities, tools_enabled, context_sources,
    thinking_enabled, streaming_enabled, category, is_active
)
SELECT
    $1,
    $2,
    display_name,
    description,
    avatar,
    system_prompt,
    model_preference,
    temperature,
    max_tokens,
    capabilities,
    tools_enabled,
    context_sources,
    thinking_enabled,
    TRUE,
    category,
    TRUE
FROM agent_presets
WHERE id = $3
RETURNING id, user_id, name, display_name, description, avatar, system_prompt, model_preference, temperature, max_tokens, capabilities, tools_enabled, context_sources, thinking_enabled, streaming_enabled, category, is_public, is_active, times_used, last_used_at, created_at, updated_at
`

type CreateAgentFromPresetParams struct {
	UserID   string      `json:"user_id"`
	Name     string      `json:"name"`
	PresetID pgtype.UUID `json:"preset_id"`
}

func (q *Queries) CreateAgentFromPreset(ctx context.Context, arg CreateAgentFromPresetParams) (CustomAgent, error) {
	row := q.db.QueryRow(ctx, createAgentFromPreset, arg.UserID, arg.Name, arg.PresetID)
	var i CustomAgent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Avatar,
		&i.SystemPrompt,
		&i.ModelPreference,
		&i.Temperature,
		&i.MaxTokens,
		&i.Capabilities,
		&i.ToolsEnabled,
		&i.ContextSources,
		&i.ThinkingEnabled,
		&i.StreamingEnabled,
		&i.Category,
		&i.IsPublic,
		&i.IsActive,
		&i.TimesUsed,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
