// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: microsoft.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMicrosoftCalendarByUser = `-- name: DeleteMicrosoftCalendarByUser :exec
DELETE FROM microsoft_calendar_events WHERE user_id = $1
`

func (q *Queries) DeleteMicrosoftCalendarByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftCalendarByUser, userID)
	return err
}

const deleteMicrosoftCalendarEvent = `-- name: DeleteMicrosoftCalendarEvent :exec
DELETE FROM microsoft_calendar_events
WHERE user_id = $1 AND event_id = $2
`

type DeleteMicrosoftCalendarEventParams struct {
	UserID  string `json:"user_id"`
	EventID string `json:"event_id"`
}

func (q *Queries) DeleteMicrosoftCalendarEvent(ctx context.Context, arg DeleteMicrosoftCalendarEventParams) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftCalendarEvent, arg.UserID, arg.EventID)
	return err
}

const deleteMicrosoftContact = `-- name: DeleteMicrosoftContact :exec
DELETE FROM microsoft_contacts
WHERE user_id = $1 AND contact_id = $2
`

type DeleteMicrosoftContactParams struct {
	UserID    string `json:"user_id"`
	ContactID string `json:"contact_id"`
}

func (q *Queries) DeleteMicrosoftContact(ctx context.Context, arg DeleteMicrosoftContactParams) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftContact, arg.UserID, arg.ContactID)
	return err
}

const deleteMicrosoftContactsByUser = `-- name: DeleteMicrosoftContactsByUser :exec
DELETE FROM microsoft_contacts WHERE user_id = $1
`

func (q *Queries) DeleteMicrosoftContactsByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftContactsByUser, userID)
	return err
}

const deleteMicrosoftMailByUser = `-- name: DeleteMicrosoftMailByUser :exec
DELETE FROM microsoft_mail_messages WHERE user_id = $1
`

func (q *Queries) DeleteMicrosoftMailByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftMailByUser, userID)
	return err
}

const deleteMicrosoftMailMessage = `-- name: DeleteMicrosoftMailMessage :exec
DELETE FROM microsoft_mail_messages
WHERE user_id = $1 AND message_id = $2
`

type DeleteMicrosoftMailMessageParams struct {
	UserID    string `json:"user_id"`
	MessageID string `json:"message_id"`
}

func (q *Queries) DeleteMicrosoftMailMessage(ctx context.Context, arg DeleteMicrosoftMailMessageParams) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftMailMessage, arg.UserID, arg.MessageID)
	return err
}

const deleteMicrosoftOneDriveByUser = `-- name: DeleteMicrosoftOneDriveByUser :exec
DELETE FROM microsoft_onedrive_files WHERE user_id = $1
`

func (q *Queries) DeleteMicrosoftOneDriveByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftOneDriveByUser, userID)
	return err
}

const deleteMicrosoftOneDriveFile = `-- name: DeleteMicrosoftOneDriveFile :exec
DELETE FROM microsoft_onedrive_files
WHERE user_id = $1 AND item_id = $2
`

type DeleteMicrosoftOneDriveFileParams struct {
	UserID string `json:"user_id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) DeleteMicrosoftOneDriveFile(ctx context.Context, arg DeleteMicrosoftOneDriveFileParams) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftOneDriveFile, arg.UserID, arg.ItemID)
	return err
}

const deleteMicrosoftToDoList = `-- name: DeleteMicrosoftToDoList :exec
DELETE FROM microsoft_todo_lists
WHERE user_id = $1 AND list_id = $2
`

type DeleteMicrosoftToDoListParams struct {
	UserID string `json:"user_id"`
	ListID string `json:"list_id"`
}

func (q *Queries) DeleteMicrosoftToDoList(ctx context.Context, arg DeleteMicrosoftToDoListParams) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftToDoList, arg.UserID, arg.ListID)
	return err
}

const deleteMicrosoftToDoListsByUser = `-- name: DeleteMicrosoftToDoListsByUser :exec
DELETE FROM microsoft_todo_lists WHERE user_id = $1
`

func (q *Queries) DeleteMicrosoftToDoListsByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftToDoListsByUser, userID)
	return err
}

const deleteMicrosoftToDoTask = `-- name: DeleteMicrosoftToDoTask :exec
DELETE FROM microsoft_todo_tasks
WHERE user_id = $1 AND task_id = $2
`

type DeleteMicrosoftToDoTaskParams struct {
	UserID string `json:"user_id"`
	TaskID string `json:"task_id"`
}

func (q *Queries) DeleteMicrosoftToDoTask(ctx context.Context, arg DeleteMicrosoftToDoTaskParams) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftToDoTask, arg.UserID, arg.TaskID)
	return err
}

const deleteMicrosoftToDoTasksByList = `-- name: DeleteMicrosoftToDoTasksByList :exec
DELETE FROM microsoft_todo_tasks
WHERE user_id = $1 AND list_id = $2
`

type DeleteMicrosoftToDoTasksByListParams struct {
	UserID string `json:"user_id"`
	ListID string `json:"list_id"`
}

func (q *Queries) DeleteMicrosoftToDoTasksByList(ctx context.Context, arg DeleteMicrosoftToDoTasksByListParams) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftToDoTasksByList, arg.UserID, arg.ListID)
	return err
}

const deleteMicrosoftToDoTasksByUser = `-- name: DeleteMicrosoftToDoTasksByUser :exec
DELETE FROM microsoft_todo_tasks WHERE user_id = $1
`

func (q *Queries) DeleteMicrosoftToDoTasksByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftToDoTasksByUser, userID)
	return err
}

const deleteMicrosoftToken = `-- name: DeleteMicrosoftToken :exec
DELETE FROM microsoft_oauth_tokens WHERE user_id = $1
`

func (q *Queries) DeleteMicrosoftToken(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteMicrosoftToken, userID)
	return err
}

const getMicrosoftCalendarEvent = `-- name: GetMicrosoftCalendarEvent :one
SELECT id, user_id, event_id, calendar_id, calendar_name, subject, body_preview, body_content, body_content_type, location_display_name, location_address, location_coordinates, start_datetime, start_timezone, end_datetime, end_timezone, is_all_day, recurrence, series_master_id, type, attendees, organizer_email, organizer_name, is_online_meeting, online_meeting_provider, online_meeting_url, online_meeting_join_url, response_status, response_time, importance, sensitivity, show_as, is_cancelled, is_reminder_on, reminder_minutes_before_start, categories, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_calendar_events
WHERE user_id = $1 AND event_id = $2
`

type GetMicrosoftCalendarEventParams struct {
	UserID  string `json:"user_id"`
	EventID string `json:"event_id"`
}

func (q *Queries) GetMicrosoftCalendarEvent(ctx context.Context, arg GetMicrosoftCalendarEventParams) (MicrosoftCalendarEvent, error) {
	row := q.db.QueryRow(ctx, getMicrosoftCalendarEvent, arg.UserID, arg.EventID)
	var i MicrosoftCalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CalendarID,
		&i.CalendarName,
		&i.Subject,
		&i.BodyPreview,
		&i.BodyContent,
		&i.BodyContentType,
		&i.LocationDisplayName,
		&i.LocationAddress,
		&i.LocationCoordinates,
		&i.StartDatetime,
		&i.StartTimezone,
		&i.EndDatetime,
		&i.EndTimezone,
		&i.IsAllDay,
		&i.Recurrence,
		&i.SeriesMasterID,
		&i.Type,
		&i.Attendees,
		&i.OrganizerEmail,
		&i.OrganizerName,
		&i.IsOnlineMeeting,
		&i.OnlineMeetingProvider,
		&i.OnlineMeetingUrl,
		&i.OnlineMeetingJoinUrl,
		&i.ResponseStatus,
		&i.ResponseTime,
		&i.Importance,
		&i.Sensitivity,
		&i.ShowAs,
		&i.IsCancelled,
		&i.IsReminderOn,
		&i.ReminderMinutesBeforeStart,
		&i.Categories,
		&i.CreatedDatetime,
		&i.LastModifiedDatetime,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMicrosoftCalendarEvents = `-- name: GetMicrosoftCalendarEvents :many
SELECT id, user_id, event_id, calendar_id, calendar_name, subject, body_preview, body_content, body_content_type, location_display_name, location_address, location_coordinates, start_datetime, start_timezone, end_datetime, end_timezone, is_all_day, recurrence, series_master_id, type, attendees, organizer_email, organizer_name, is_online_meeting, online_meeting_provider, online_meeting_url, online_meeting_join_url, response_status, response_time, importance, sensitivity, show_as, is_cancelled, is_reminder_on, reminder_minutes_before_start, categories, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_calendar_events
WHERE user_id = $1
ORDER BY start_datetime ASC
LIMIT $2 OFFSET $3
`

type GetMicrosoftCalendarEventsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetMicrosoftCalendarEvents(ctx context.Context, arg GetMicrosoftCalendarEventsParams) ([]MicrosoftCalendarEvent, error) {
	rows, err := q.db.Query(ctx, getMicrosoftCalendarEvents, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftCalendarEvent{}
	for rows.Next() {
		var i MicrosoftCalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.CalendarID,
			&i.CalendarName,
			&i.Subject,
			&i.BodyPreview,
			&i.BodyContent,
			&i.BodyContentType,
			&i.LocationDisplayName,
			&i.LocationAddress,
			&i.LocationCoordinates,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.EndDatetime,
			&i.EndTimezone,
			&i.IsAllDay,
			&i.Recurrence,
			&i.SeriesMasterID,
			&i.Type,
			&i.Attendees,
			&i.OrganizerEmail,
			&i.OrganizerName,
			&i.IsOnlineMeeting,
			&i.OnlineMeetingProvider,
			&i.OnlineMeetingUrl,
			&i.OnlineMeetingJoinUrl,
			&i.ResponseStatus,
			&i.ResponseTime,
			&i.Importance,
			&i.Sensitivity,
			&i.ShowAs,
			&i.IsCancelled,
			&i.IsReminderOn,
			&i.ReminderMinutesBeforeStart,
			&i.Categories,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftCalendarEventsByCalendar = `-- name: GetMicrosoftCalendarEventsByCalendar :many
SELECT id, user_id, event_id, calendar_id, calendar_name, subject, body_preview, body_content, body_content_type, location_display_name, location_address, location_coordinates, start_datetime, start_timezone, end_datetime, end_timezone, is_all_day, recurrence, series_master_id, type, attendees, organizer_email, organizer_name, is_online_meeting, online_meeting_provider, online_meeting_url, online_meeting_join_url, response_status, response_time, importance, sensitivity, show_as, is_cancelled, is_reminder_on, reminder_minutes_before_start, categories, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_calendar_events
WHERE user_id = $1 AND calendar_id = $2
ORDER BY start_datetime ASC
LIMIT $3 OFFSET $4
`

type GetMicrosoftCalendarEventsByCalendarParams struct {
	UserID     string  `json:"user_id"`
	CalendarID *string `json:"calendar_id"`
	Limit      int32   `json:"limit"`
	Offset     int32   `json:"offset"`
}

func (q *Queries) GetMicrosoftCalendarEventsByCalendar(ctx context.Context, arg GetMicrosoftCalendarEventsByCalendarParams) ([]MicrosoftCalendarEvent, error) {
	rows, err := q.db.Query(ctx, getMicrosoftCalendarEventsByCalendar,
		arg.UserID,
		arg.CalendarID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftCalendarEvent{}
	for rows.Next() {
		var i MicrosoftCalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.CalendarID,
			&i.CalendarName,
			&i.Subject,
			&i.BodyPreview,
			&i.BodyContent,
			&i.BodyContentType,
			&i.LocationDisplayName,
			&i.LocationAddress,
			&i.LocationCoordinates,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.EndDatetime,
			&i.EndTimezone,
			&i.IsAllDay,
			&i.Recurrence,
			&i.SeriesMasterID,
			&i.Type,
			&i.Attendees,
			&i.OrganizerEmail,
			&i.OrganizerName,
			&i.IsOnlineMeeting,
			&i.OnlineMeetingProvider,
			&i.OnlineMeetingUrl,
			&i.OnlineMeetingJoinUrl,
			&i.ResponseStatus,
			&i.ResponseTime,
			&i.Importance,
			&i.Sensitivity,
			&i.ShowAs,
			&i.IsCancelled,
			&i.IsReminderOn,
			&i.ReminderMinutesBeforeStart,
			&i.Categories,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftCalendarEventsByDateRange = `-- name: GetMicrosoftCalendarEventsByDateRange :many
SELECT id, user_id, event_id, calendar_id, calendar_name, subject, body_preview, body_content, body_content_type, location_display_name, location_address, location_coordinates, start_datetime, start_timezone, end_datetime, end_timezone, is_all_day, recurrence, series_master_id, type, attendees, organizer_email, organizer_name, is_online_meeting, online_meeting_provider, online_meeting_url, online_meeting_join_url, response_status, response_time, importance, sensitivity, show_as, is_cancelled, is_reminder_on, reminder_minutes_before_start, categories, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_calendar_events
WHERE user_id = $1
  AND start_datetime >= $2
  AND end_datetime <= $3
ORDER BY start_datetime ASC
`

type GetMicrosoftCalendarEventsByDateRangeParams struct {
	UserID        string             `json:"user_id"`
	StartDatetime pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime   pgtype.Timestamptz `json:"end_datetime"`
}

func (q *Queries) GetMicrosoftCalendarEventsByDateRange(ctx context.Context, arg GetMicrosoftCalendarEventsByDateRangeParams) ([]MicrosoftCalendarEvent, error) {
	rows, err := q.db.Query(ctx, getMicrosoftCalendarEventsByDateRange, arg.UserID, arg.StartDatetime, arg.EndDatetime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftCalendarEvent{}
	for rows.Next() {
		var i MicrosoftCalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.CalendarID,
			&i.CalendarName,
			&i.Subject,
			&i.BodyPreview,
			&i.BodyContent,
			&i.BodyContentType,
			&i.LocationDisplayName,
			&i.LocationAddress,
			&i.LocationCoordinates,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.EndDatetime,
			&i.EndTimezone,
			&i.IsAllDay,
			&i.Recurrence,
			&i.SeriesMasterID,
			&i.Type,
			&i.Attendees,
			&i.OrganizerEmail,
			&i.OrganizerName,
			&i.IsOnlineMeeting,
			&i.OnlineMeetingProvider,
			&i.OnlineMeetingUrl,
			&i.OnlineMeetingJoinUrl,
			&i.ResponseStatus,
			&i.ResponseTime,
			&i.Importance,
			&i.Sensitivity,
			&i.ShowAs,
			&i.IsCancelled,
			&i.IsReminderOn,
			&i.ReminderMinutesBeforeStart,
			&i.Categories,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftContact = `-- name: GetMicrosoftContact :one
SELECT id, user_id, contact_id, display_name, given_name, surname, middle_name, nickname, title, email_addresses, phone_numbers, addresses, im_addresses, websites, company_name, department, job_title, office_location, profession, manager, assistant_name, birthday, spouse_name, personal_notes, photo_url, categories, parent_folder_id, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_contacts
WHERE user_id = $1 AND contact_id = $2
`

type GetMicrosoftContactParams struct {
	UserID    string `json:"user_id"`
	ContactID string `json:"contact_id"`
}

func (q *Queries) GetMicrosoftContact(ctx context.Context, arg GetMicrosoftContactParams) (MicrosoftContact, error) {
	row := q.db.QueryRow(ctx, getMicrosoftContact, arg.UserID, arg.ContactID)
	var i MicrosoftContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContactID,
		&i.DisplayName,
		&i.GivenName,
		&i.Surname,
		&i.MiddleName,
		&i.Nickname,
		&i.Title,
		&i.EmailAddresses,
		&i.PhoneNumbers,
		&i.Addresses,
		&i.ImAddresses,
		&i.Websites,
		&i.CompanyName,
		&i.Department,
		&i.JobTitle,
		&i.OfficeLocation,
		&i.Profession,
		&i.Manager,
		&i.AssistantName,
		&i.Birthday,
		&i.SpouseName,
		&i.PersonalNotes,
		&i.PhotoUrl,
		&i.Categories,
		&i.ParentFolderID,
		&i.CreatedDatetime,
		&i.LastModifiedDatetime,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMicrosoftContacts = `-- name: GetMicrosoftContacts :many
SELECT id, user_id, contact_id, display_name, given_name, surname, middle_name, nickname, title, email_addresses, phone_numbers, addresses, im_addresses, websites, company_name, department, job_title, office_location, profession, manager, assistant_name, birthday, spouse_name, personal_notes, photo_url, categories, parent_folder_id, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_contacts
WHERE user_id = $1
ORDER BY display_name NULLS LAST
LIMIT $2 OFFSET $3
`

type GetMicrosoftContactsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetMicrosoftContacts(ctx context.Context, arg GetMicrosoftContactsParams) ([]MicrosoftContact, error) {
	rows, err := q.db.Query(ctx, getMicrosoftContacts, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftContact{}
	for rows.Next() {
		var i MicrosoftContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContactID,
			&i.DisplayName,
			&i.GivenName,
			&i.Surname,
			&i.MiddleName,
			&i.Nickname,
			&i.Title,
			&i.EmailAddresses,
			&i.PhoneNumbers,
			&i.Addresses,
			&i.ImAddresses,
			&i.Websites,
			&i.CompanyName,
			&i.Department,
			&i.JobTitle,
			&i.OfficeLocation,
			&i.Profession,
			&i.Manager,
			&i.AssistantName,
			&i.Birthday,
			&i.SpouseName,
			&i.PersonalNotes,
			&i.PhotoUrl,
			&i.Categories,
			&i.ParentFolderID,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftContactsByCompany = `-- name: GetMicrosoftContactsByCompany :many
SELECT id, user_id, contact_id, display_name, given_name, surname, middle_name, nickname, title, email_addresses, phone_numbers, addresses, im_addresses, websites, company_name, department, job_title, office_location, profession, manager, assistant_name, birthday, spouse_name, personal_notes, photo_url, categories, parent_folder_id, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_contacts
WHERE user_id = $1 AND company_name = $2
ORDER BY display_name NULLS LAST
`

type GetMicrosoftContactsByCompanyParams struct {
	UserID      string  `json:"user_id"`
	CompanyName *string `json:"company_name"`
}

func (q *Queries) GetMicrosoftContactsByCompany(ctx context.Context, arg GetMicrosoftContactsByCompanyParams) ([]MicrosoftContact, error) {
	rows, err := q.db.Query(ctx, getMicrosoftContactsByCompany, arg.UserID, arg.CompanyName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftContact{}
	for rows.Next() {
		var i MicrosoftContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContactID,
			&i.DisplayName,
			&i.GivenName,
			&i.Surname,
			&i.MiddleName,
			&i.Nickname,
			&i.Title,
			&i.EmailAddresses,
			&i.PhoneNumbers,
			&i.Addresses,
			&i.ImAddresses,
			&i.Websites,
			&i.CompanyName,
			&i.Department,
			&i.JobTitle,
			&i.OfficeLocation,
			&i.Profession,
			&i.Manager,
			&i.AssistantName,
			&i.Birthday,
			&i.SpouseName,
			&i.PersonalNotes,
			&i.PhotoUrl,
			&i.Categories,
			&i.ParentFolderID,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftContactsCount = `-- name: GetMicrosoftContactsCount :one
SELECT COUNT(*) FROM microsoft_contacts WHERE user_id = $1
`

func (q *Queries) GetMicrosoftContactsCount(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, getMicrosoftContactsCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMicrosoftMailConversation = `-- name: GetMicrosoftMailConversation :many
SELECT id, user_id, message_id, conversation_id, subject, body_preview, body_content, body_content_type, importance, from_email, from_name, to_recipients, cc_recipients, bcc_recipients, reply_to, is_read, is_draft, has_attachments, folder_id, folder_name, categories, flag_status, attachments, received_datetime, sent_datetime, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_mail_messages
WHERE user_id = $1 AND conversation_id = $2
ORDER BY received_datetime ASC
`

type GetMicrosoftMailConversationParams struct {
	UserID         string  `json:"user_id"`
	ConversationID *string `json:"conversation_id"`
}

func (q *Queries) GetMicrosoftMailConversation(ctx context.Context, arg GetMicrosoftMailConversationParams) ([]MicrosoftMailMessage, error) {
	rows, err := q.db.Query(ctx, getMicrosoftMailConversation, arg.UserID, arg.ConversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftMailMessage{}
	for rows.Next() {
		var i MicrosoftMailMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MessageID,
			&i.ConversationID,
			&i.Subject,
			&i.BodyPreview,
			&i.BodyContent,
			&i.BodyContentType,
			&i.Importance,
			&i.FromEmail,
			&i.FromName,
			&i.ToRecipients,
			&i.CcRecipients,
			&i.BccRecipients,
			&i.ReplyTo,
			&i.IsRead,
			&i.IsDraft,
			&i.HasAttachments,
			&i.FolderID,
			&i.FolderName,
			&i.Categories,
			&i.FlagStatus,
			&i.Attachments,
			&i.ReceivedDatetime,
			&i.SentDatetime,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftMailMessage = `-- name: GetMicrosoftMailMessage :one
SELECT id, user_id, message_id, conversation_id, subject, body_preview, body_content, body_content_type, importance, from_email, from_name, to_recipients, cc_recipients, bcc_recipients, reply_to, is_read, is_draft, has_attachments, folder_id, folder_name, categories, flag_status, attachments, received_datetime, sent_datetime, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_mail_messages
WHERE user_id = $1 AND message_id = $2
`

type GetMicrosoftMailMessageParams struct {
	UserID    string `json:"user_id"`
	MessageID string `json:"message_id"`
}

func (q *Queries) GetMicrosoftMailMessage(ctx context.Context, arg GetMicrosoftMailMessageParams) (MicrosoftMailMessage, error) {
	row := q.db.QueryRow(ctx, getMicrosoftMailMessage, arg.UserID, arg.MessageID)
	var i MicrosoftMailMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessageID,
		&i.ConversationID,
		&i.Subject,
		&i.BodyPreview,
		&i.BodyContent,
		&i.BodyContentType,
		&i.Importance,
		&i.FromEmail,
		&i.FromName,
		&i.ToRecipients,
		&i.CcRecipients,
		&i.BccRecipients,
		&i.ReplyTo,
		&i.IsRead,
		&i.IsDraft,
		&i.HasAttachments,
		&i.FolderID,
		&i.FolderName,
		&i.Categories,
		&i.FlagStatus,
		&i.Attachments,
		&i.ReceivedDatetime,
		&i.SentDatetime,
		&i.CreatedDatetime,
		&i.LastModifiedDatetime,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMicrosoftMailMessages = `-- name: GetMicrosoftMailMessages :many
SELECT id, user_id, message_id, conversation_id, subject, body_preview, body_content, body_content_type, importance, from_email, from_name, to_recipients, cc_recipients, bcc_recipients, reply_to, is_read, is_draft, has_attachments, folder_id, folder_name, categories, flag_status, attachments, received_datetime, sent_datetime, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_mail_messages
WHERE user_id = $1
ORDER BY received_datetime DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type GetMicrosoftMailMessagesParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetMicrosoftMailMessages(ctx context.Context, arg GetMicrosoftMailMessagesParams) ([]MicrosoftMailMessage, error) {
	rows, err := q.db.Query(ctx, getMicrosoftMailMessages, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftMailMessage{}
	for rows.Next() {
		var i MicrosoftMailMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MessageID,
			&i.ConversationID,
			&i.Subject,
			&i.BodyPreview,
			&i.BodyContent,
			&i.BodyContentType,
			&i.Importance,
			&i.FromEmail,
			&i.FromName,
			&i.ToRecipients,
			&i.CcRecipients,
			&i.BccRecipients,
			&i.ReplyTo,
			&i.IsRead,
			&i.IsDraft,
			&i.HasAttachments,
			&i.FolderID,
			&i.FolderName,
			&i.Categories,
			&i.FlagStatus,
			&i.Attachments,
			&i.ReceivedDatetime,
			&i.SentDatetime,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftMailMessagesByFolder = `-- name: GetMicrosoftMailMessagesByFolder :many
SELECT id, user_id, message_id, conversation_id, subject, body_preview, body_content, body_content_type, importance, from_email, from_name, to_recipients, cc_recipients, bcc_recipients, reply_to, is_read, is_draft, has_attachments, folder_id, folder_name, categories, flag_status, attachments, received_datetime, sent_datetime, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_mail_messages
WHERE user_id = $1 AND folder_id = $2
ORDER BY received_datetime DESC NULLS LAST
LIMIT $3 OFFSET $4
`

type GetMicrosoftMailMessagesByFolderParams struct {
	UserID   string  `json:"user_id"`
	FolderID *string `json:"folder_id"`
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
}

func (q *Queries) GetMicrosoftMailMessagesByFolder(ctx context.Context, arg GetMicrosoftMailMessagesByFolderParams) ([]MicrosoftMailMessage, error) {
	rows, err := q.db.Query(ctx, getMicrosoftMailMessagesByFolder,
		arg.UserID,
		arg.FolderID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftMailMessage{}
	for rows.Next() {
		var i MicrosoftMailMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MessageID,
			&i.ConversationID,
			&i.Subject,
			&i.BodyPreview,
			&i.BodyContent,
			&i.BodyContentType,
			&i.Importance,
			&i.FromEmail,
			&i.FromName,
			&i.ToRecipients,
			&i.CcRecipients,
			&i.BccRecipients,
			&i.ReplyTo,
			&i.IsRead,
			&i.IsDraft,
			&i.HasAttachments,
			&i.FolderID,
			&i.FolderName,
			&i.Categories,
			&i.FlagStatus,
			&i.Attachments,
			&i.ReceivedDatetime,
			&i.SentDatetime,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftOneDriveFile = `-- name: GetMicrosoftOneDriveFile :one
SELECT id, user_id, item_id, name, description, mime_type, size_bytes, parent_reference_id, parent_reference_path, web_url, is_folder, folder_child_count, file_hash, shared, shared_scope, shared_link, permissions, created_by_user_email, created_by_user_name, last_modified_by_user_email, last_modified_by_user_name, created_datetime, last_modified_datetime, download_url, thumbnails, synced_at, created_at, updated_at FROM microsoft_onedrive_files
WHERE user_id = $1 AND item_id = $2
`

type GetMicrosoftOneDriveFileParams struct {
	UserID string `json:"user_id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) GetMicrosoftOneDriveFile(ctx context.Context, arg GetMicrosoftOneDriveFileParams) (MicrosoftOnedriveFile, error) {
	row := q.db.QueryRow(ctx, getMicrosoftOneDriveFile, arg.UserID, arg.ItemID)
	var i MicrosoftOnedriveFile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Name,
		&i.Description,
		&i.MimeType,
		&i.SizeBytes,
		&i.ParentReferenceID,
		&i.ParentReferencePath,
		&i.WebUrl,
		&i.IsFolder,
		&i.FolderChildCount,
		&i.FileHash,
		&i.Shared,
		&i.SharedScope,
		&i.SharedLink,
		&i.Permissions,
		&i.CreatedByUserEmail,
		&i.CreatedByUserName,
		&i.LastModifiedByUserEmail,
		&i.LastModifiedByUserName,
		&i.CreatedDatetime,
		&i.LastModifiedDatetime,
		&i.DownloadUrl,
		&i.Thumbnails,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMicrosoftOneDriveFiles = `-- name: GetMicrosoftOneDriveFiles :many
SELECT id, user_id, item_id, name, description, mime_type, size_bytes, parent_reference_id, parent_reference_path, web_url, is_folder, folder_child_count, file_hash, shared, shared_scope, shared_link, permissions, created_by_user_email, created_by_user_name, last_modified_by_user_email, last_modified_by_user_name, created_datetime, last_modified_datetime, download_url, thumbnails, synced_at, created_at, updated_at FROM microsoft_onedrive_files
WHERE user_id = $1
ORDER BY last_modified_datetime DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type GetMicrosoftOneDriveFilesParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetMicrosoftOneDriveFiles(ctx context.Context, arg GetMicrosoftOneDriveFilesParams) ([]MicrosoftOnedriveFile, error) {
	rows, err := q.db.Query(ctx, getMicrosoftOneDriveFiles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftOnedriveFile{}
	for rows.Next() {
		var i MicrosoftOnedriveFile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemID,
			&i.Name,
			&i.Description,
			&i.MimeType,
			&i.SizeBytes,
			&i.ParentReferenceID,
			&i.ParentReferencePath,
			&i.WebUrl,
			&i.IsFolder,
			&i.FolderChildCount,
			&i.FileHash,
			&i.Shared,
			&i.SharedScope,
			&i.SharedLink,
			&i.Permissions,
			&i.CreatedByUserEmail,
			&i.CreatedByUserName,
			&i.LastModifiedByUserEmail,
			&i.LastModifiedByUserName,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.DownloadUrl,
			&i.Thumbnails,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftOneDriveFilesByFolder = `-- name: GetMicrosoftOneDriveFilesByFolder :many
SELECT id, user_id, item_id, name, description, mime_type, size_bytes, parent_reference_id, parent_reference_path, web_url, is_folder, folder_child_count, file_hash, shared, shared_scope, shared_link, permissions, created_by_user_email, created_by_user_name, last_modified_by_user_email, last_modified_by_user_name, created_datetime, last_modified_datetime, download_url, thumbnails, synced_at, created_at, updated_at FROM microsoft_onedrive_files
WHERE user_id = $1 AND parent_reference_id = $2
ORDER BY is_folder DESC, name ASC
LIMIT $3 OFFSET $4
`

type GetMicrosoftOneDriveFilesByFolderParams struct {
	UserID            string  `json:"user_id"`
	ParentReferenceID *string `json:"parent_reference_id"`
	Limit             int32   `json:"limit"`
	Offset            int32   `json:"offset"`
}

func (q *Queries) GetMicrosoftOneDriveFilesByFolder(ctx context.Context, arg GetMicrosoftOneDriveFilesByFolderParams) ([]MicrosoftOnedriveFile, error) {
	rows, err := q.db.Query(ctx, getMicrosoftOneDriveFilesByFolder,
		arg.UserID,
		arg.ParentReferenceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftOnedriveFile{}
	for rows.Next() {
		var i MicrosoftOnedriveFile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemID,
			&i.Name,
			&i.Description,
			&i.MimeType,
			&i.SizeBytes,
			&i.ParentReferenceID,
			&i.ParentReferencePath,
			&i.WebUrl,
			&i.IsFolder,
			&i.FolderChildCount,
			&i.FileHash,
			&i.Shared,
			&i.SharedScope,
			&i.SharedLink,
			&i.Permissions,
			&i.CreatedByUserEmail,
			&i.CreatedByUserName,
			&i.LastModifiedByUserEmail,
			&i.LastModifiedByUserName,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.DownloadUrl,
			&i.Thumbnails,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftOneDriveFolders = `-- name: GetMicrosoftOneDriveFolders :many
SELECT id, user_id, item_id, name, description, mime_type, size_bytes, parent_reference_id, parent_reference_path, web_url, is_folder, folder_child_count, file_hash, shared, shared_scope, shared_link, permissions, created_by_user_email, created_by_user_name, last_modified_by_user_email, last_modified_by_user_name, created_datetime, last_modified_datetime, download_url, thumbnails, synced_at, created_at, updated_at FROM microsoft_onedrive_files
WHERE user_id = $1 AND is_folder = TRUE
ORDER BY name ASC
`

func (q *Queries) GetMicrosoftOneDriveFolders(ctx context.Context, userID string) ([]MicrosoftOnedriveFile, error) {
	rows, err := q.db.Query(ctx, getMicrosoftOneDriveFolders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftOnedriveFile{}
	for rows.Next() {
		var i MicrosoftOnedriveFile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemID,
			&i.Name,
			&i.Description,
			&i.MimeType,
			&i.SizeBytes,
			&i.ParentReferenceID,
			&i.ParentReferencePath,
			&i.WebUrl,
			&i.IsFolder,
			&i.FolderChildCount,
			&i.FileHash,
			&i.Shared,
			&i.SharedScope,
			&i.SharedLink,
			&i.Permissions,
			&i.CreatedByUserEmail,
			&i.CreatedByUserName,
			&i.LastModifiedByUserEmail,
			&i.LastModifiedByUserName,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.DownloadUrl,
			&i.Thumbnails,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftOneDriveRecentFiles = `-- name: GetMicrosoftOneDriveRecentFiles :many
SELECT id, user_id, item_id, name, description, mime_type, size_bytes, parent_reference_id, parent_reference_path, web_url, is_folder, folder_child_count, file_hash, shared, shared_scope, shared_link, permissions, created_by_user_email, created_by_user_name, last_modified_by_user_email, last_modified_by_user_name, created_datetime, last_modified_datetime, download_url, thumbnails, synced_at, created_at, updated_at FROM microsoft_onedrive_files
WHERE user_id = $1 AND is_folder = FALSE
ORDER BY last_modified_datetime DESC NULLS LAST
LIMIT $2
`

type GetMicrosoftOneDriveRecentFilesParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetMicrosoftOneDriveRecentFiles(ctx context.Context, arg GetMicrosoftOneDriveRecentFilesParams) ([]MicrosoftOnedriveFile, error) {
	rows, err := q.db.Query(ctx, getMicrosoftOneDriveRecentFiles, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftOnedriveFile{}
	for rows.Next() {
		var i MicrosoftOnedriveFile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemID,
			&i.Name,
			&i.Description,
			&i.MimeType,
			&i.SizeBytes,
			&i.ParentReferenceID,
			&i.ParentReferencePath,
			&i.WebUrl,
			&i.IsFolder,
			&i.FolderChildCount,
			&i.FileHash,
			&i.Shared,
			&i.SharedScope,
			&i.SharedLink,
			&i.Permissions,
			&i.CreatedByUserEmail,
			&i.CreatedByUserName,
			&i.LastModifiedByUserEmail,
			&i.LastModifiedByUserName,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.DownloadUrl,
			&i.Thumbnails,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftOneDriveStorageUsed = `-- name: GetMicrosoftOneDriveStorageUsed :one
SELECT COALESCE(SUM(size_bytes), 0)::BIGINT as total_bytes
FROM microsoft_onedrive_files
WHERE user_id = $1 AND is_folder = FALSE
`

func (q *Queries) GetMicrosoftOneDriveStorageUsed(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, getMicrosoftOneDriveStorageUsed, userID)
	var total_bytes int64
	err := row.Scan(&total_bytes)
	return total_bytes, err
}

const getMicrosoftToDoIncompleteTasks = `-- name: GetMicrosoftToDoIncompleteTasks :many
SELECT id, user_id, task_id, list_id, title, body_content, body_content_type, importance, status, due_datetime, due_timezone, start_datetime, start_timezone, completed_datetime, completed_timezone, recurrence, is_reminder_on, reminder_datetime, categories, linked_resources, checklist_items, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_todo_tasks
WHERE user_id = $1 AND status != 'completed'
ORDER BY due_datetime ASC NULLS LAST
LIMIT $2
`

type GetMicrosoftToDoIncompleteTasksParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetMicrosoftToDoIncompleteTasks(ctx context.Context, arg GetMicrosoftToDoIncompleteTasksParams) ([]MicrosoftTodoTask, error) {
	rows, err := q.db.Query(ctx, getMicrosoftToDoIncompleteTasks, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftTodoTask{}
	for rows.Next() {
		var i MicrosoftTodoTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.ListID,
			&i.Title,
			&i.BodyContent,
			&i.BodyContentType,
			&i.Importance,
			&i.Status,
			&i.DueDatetime,
			&i.DueTimezone,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.CompletedDatetime,
			&i.CompletedTimezone,
			&i.Recurrence,
			&i.IsReminderOn,
			&i.ReminderDatetime,
			&i.Categories,
			&i.LinkedResources,
			&i.ChecklistItems,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftToDoList = `-- name: GetMicrosoftToDoList :one
SELECT id, user_id, list_id, display_name, is_owner, is_shared, wellknown_list_name, synced_at, created_at, updated_at FROM microsoft_todo_lists
WHERE user_id = $1 AND list_id = $2
`

type GetMicrosoftToDoListParams struct {
	UserID string `json:"user_id"`
	ListID string `json:"list_id"`
}

func (q *Queries) GetMicrosoftToDoList(ctx context.Context, arg GetMicrosoftToDoListParams) (MicrosoftTodoList, error) {
	row := q.db.QueryRow(ctx, getMicrosoftToDoList, arg.UserID, arg.ListID)
	var i MicrosoftTodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListID,
		&i.DisplayName,
		&i.IsOwner,
		&i.IsShared,
		&i.WellknownListName,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMicrosoftToDoLists = `-- name: GetMicrosoftToDoLists :many
SELECT id, user_id, list_id, display_name, is_owner, is_shared, wellknown_list_name, synced_at, created_at, updated_at FROM microsoft_todo_lists
WHERE user_id = $1
ORDER BY display_name ASC
`

func (q *Queries) GetMicrosoftToDoLists(ctx context.Context, userID string) ([]MicrosoftTodoList, error) {
	rows, err := q.db.Query(ctx, getMicrosoftToDoLists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftTodoList{}
	for rows.Next() {
		var i MicrosoftTodoList
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ListID,
			&i.DisplayName,
			&i.IsOwner,
			&i.IsShared,
			&i.WellknownListName,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftToDoOverdueTasks = `-- name: GetMicrosoftToDoOverdueTasks :many
SELECT id, user_id, task_id, list_id, title, body_content, body_content_type, importance, status, due_datetime, due_timezone, start_datetime, start_timezone, completed_datetime, completed_timezone, recurrence, is_reminder_on, reminder_datetime, categories, linked_resources, checklist_items, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_todo_tasks
WHERE user_id = $1
  AND status != 'completed'
  AND due_datetime < NOW()
ORDER BY due_datetime ASC
`

func (q *Queries) GetMicrosoftToDoOverdueTasks(ctx context.Context, userID string) ([]MicrosoftTodoTask, error) {
	rows, err := q.db.Query(ctx, getMicrosoftToDoOverdueTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftTodoTask{}
	for rows.Next() {
		var i MicrosoftTodoTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.ListID,
			&i.Title,
			&i.BodyContent,
			&i.BodyContentType,
			&i.Importance,
			&i.Status,
			&i.DueDatetime,
			&i.DueTimezone,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.CompletedDatetime,
			&i.CompletedTimezone,
			&i.Recurrence,
			&i.IsReminderOn,
			&i.ReminderDatetime,
			&i.Categories,
			&i.LinkedResources,
			&i.ChecklistItems,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftToDoTask = `-- name: GetMicrosoftToDoTask :one
SELECT id, user_id, task_id, list_id, title, body_content, body_content_type, importance, status, due_datetime, due_timezone, start_datetime, start_timezone, completed_datetime, completed_timezone, recurrence, is_reminder_on, reminder_datetime, categories, linked_resources, checklist_items, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_todo_tasks
WHERE user_id = $1 AND task_id = $2
`

type GetMicrosoftToDoTaskParams struct {
	UserID string `json:"user_id"`
	TaskID string `json:"task_id"`
}

func (q *Queries) GetMicrosoftToDoTask(ctx context.Context, arg GetMicrosoftToDoTaskParams) (MicrosoftTodoTask, error) {
	row := q.db.QueryRow(ctx, getMicrosoftToDoTask, arg.UserID, arg.TaskID)
	var i MicrosoftTodoTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.ListID,
		&i.Title,
		&i.BodyContent,
		&i.BodyContentType,
		&i.Importance,
		&i.Status,
		&i.DueDatetime,
		&i.DueTimezone,
		&i.StartDatetime,
		&i.StartTimezone,
		&i.CompletedDatetime,
		&i.CompletedTimezone,
		&i.Recurrence,
		&i.IsReminderOn,
		&i.ReminderDatetime,
		&i.Categories,
		&i.LinkedResources,
		&i.ChecklistItems,
		&i.CreatedDatetime,
		&i.LastModifiedDatetime,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMicrosoftToDoTasks = `-- name: GetMicrosoftToDoTasks :many
SELECT id, user_id, task_id, list_id, title, body_content, body_content_type, importance, status, due_datetime, due_timezone, start_datetime, start_timezone, completed_datetime, completed_timezone, recurrence, is_reminder_on, reminder_datetime, categories, linked_resources, checklist_items, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_todo_tasks
WHERE user_id = $1
ORDER BY due_datetime ASC NULLS LAST
LIMIT $2 OFFSET $3
`

type GetMicrosoftToDoTasksParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetMicrosoftToDoTasks(ctx context.Context, arg GetMicrosoftToDoTasksParams) ([]MicrosoftTodoTask, error) {
	rows, err := q.db.Query(ctx, getMicrosoftToDoTasks, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftTodoTask{}
	for rows.Next() {
		var i MicrosoftTodoTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.ListID,
			&i.Title,
			&i.BodyContent,
			&i.BodyContentType,
			&i.Importance,
			&i.Status,
			&i.DueDatetime,
			&i.DueTimezone,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.CompletedDatetime,
			&i.CompletedTimezone,
			&i.Recurrence,
			&i.IsReminderOn,
			&i.ReminderDatetime,
			&i.Categories,
			&i.LinkedResources,
			&i.ChecklistItems,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftToDoTasksByList = `-- name: GetMicrosoftToDoTasksByList :many
SELECT id, user_id, task_id, list_id, title, body_content, body_content_type, importance, status, due_datetime, due_timezone, start_datetime, start_timezone, completed_datetime, completed_timezone, recurrence, is_reminder_on, reminder_datetime, categories, linked_resources, checklist_items, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_todo_tasks
WHERE user_id = $1 AND list_id = $2
ORDER BY due_datetime ASC NULLS LAST
LIMIT $3 OFFSET $4
`

type GetMicrosoftToDoTasksByListParams struct {
	UserID string `json:"user_id"`
	ListID string `json:"list_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetMicrosoftToDoTasksByList(ctx context.Context, arg GetMicrosoftToDoTasksByListParams) ([]MicrosoftTodoTask, error) {
	rows, err := q.db.Query(ctx, getMicrosoftToDoTasksByList,
		arg.UserID,
		arg.ListID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftTodoTask{}
	for rows.Next() {
		var i MicrosoftTodoTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.ListID,
			&i.Title,
			&i.BodyContent,
			&i.BodyContentType,
			&i.Importance,
			&i.Status,
			&i.DueDatetime,
			&i.DueTimezone,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.CompletedDatetime,
			&i.CompletedTimezone,
			&i.Recurrence,
			&i.IsReminderOn,
			&i.ReminderDatetime,
			&i.Categories,
			&i.LinkedResources,
			&i.ChecklistItems,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftToDoTasksByStatus = `-- name: GetMicrosoftToDoTasksByStatus :many
SELECT id, user_id, task_id, list_id, title, body_content, body_content_type, importance, status, due_datetime, due_timezone, start_datetime, start_timezone, completed_datetime, completed_timezone, recurrence, is_reminder_on, reminder_datetime, categories, linked_resources, checklist_items, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_todo_tasks
WHERE user_id = $1 AND status = $2
ORDER BY due_datetime ASC NULLS LAST
LIMIT $3 OFFSET $4
`

type GetMicrosoftToDoTasksByStatusParams struct {
	UserID string  `json:"user_id"`
	Status *string `json:"status"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
}

func (q *Queries) GetMicrosoftToDoTasksByStatus(ctx context.Context, arg GetMicrosoftToDoTasksByStatusParams) ([]MicrosoftTodoTask, error) {
	rows, err := q.db.Query(ctx, getMicrosoftToDoTasksByStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftTodoTask{}
	for rows.Next() {
		var i MicrosoftTodoTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.ListID,
			&i.Title,
			&i.BodyContent,
			&i.BodyContentType,
			&i.Importance,
			&i.Status,
			&i.DueDatetime,
			&i.DueTimezone,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.CompletedDatetime,
			&i.CompletedTimezone,
			&i.Recurrence,
			&i.IsReminderOn,
			&i.ReminderDatetime,
			&i.Categories,
			&i.LinkedResources,
			&i.ChecklistItems,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftToDoTasksDueToday = `-- name: GetMicrosoftToDoTasksDueToday :many
SELECT id, user_id, task_id, list_id, title, body_content, body_content_type, importance, status, due_datetime, due_timezone, start_datetime, start_timezone, completed_datetime, completed_timezone, recurrence, is_reminder_on, reminder_datetime, categories, linked_resources, checklist_items, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_todo_tasks
WHERE user_id = $1
  AND status != 'completed'
  AND due_datetime >= CURRENT_DATE
  AND due_datetime < CURRENT_DATE + INTERVAL '1 day'
ORDER BY due_datetime ASC
`

func (q *Queries) GetMicrosoftToDoTasksDueToday(ctx context.Context, userID string) ([]MicrosoftTodoTask, error) {
	rows, err := q.db.Query(ctx, getMicrosoftToDoTasksDueToday, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftTodoTask{}
	for rows.Next() {
		var i MicrosoftTodoTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.ListID,
			&i.Title,
			&i.BodyContent,
			&i.BodyContentType,
			&i.Importance,
			&i.Status,
			&i.DueDatetime,
			&i.DueTimezone,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.CompletedDatetime,
			&i.CompletedTimezone,
			&i.Recurrence,
			&i.IsReminderOn,
			&i.ReminderDatetime,
			&i.Categories,
			&i.LinkedResources,
			&i.ChecklistItems,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrosoftToken = `-- name: GetMicrosoftToken :one
SELECT id, user_id, access_token, refresh_token, expiry, scopes, microsoft_id, microsoft_email, created_at, updated_at FROM microsoft_oauth_tokens WHERE user_id = $1
`

func (q *Queries) GetMicrosoftToken(ctx context.Context, userID string) (MicrosoftOauthToken, error) {
	row := q.db.QueryRow(ctx, getMicrosoftToken, userID)
	var i MicrosoftOauthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expiry,
		&i.Scopes,
		&i.MicrosoftID,
		&i.MicrosoftEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMicrosoftTokensByScope = `-- name: GetMicrosoftTokensByScope :many
SELECT id, user_id, access_token, refresh_token, expiry, scopes, microsoft_id, microsoft_email, created_at, updated_at FROM microsoft_oauth_tokens
WHERE $1 = ANY(scopes)
`

func (q *Queries) GetMicrosoftTokensByScope(ctx context.Context, scopes []string) ([]MicrosoftOauthToken, error) {
	rows, err := q.db.Query(ctx, getMicrosoftTokensByScope, scopes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftOauthToken{}
	for rows.Next() {
		var i MicrosoftOauthToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.Expiry,
			&i.Scopes,
			&i.MicrosoftID,
			&i.MicrosoftEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadMicrosoftMailCount = `-- name: GetUnreadMicrosoftMailCount :one
SELECT COUNT(*) FROM microsoft_mail_messages
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) GetUnreadMicrosoftMailCount(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadMicrosoftMailCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUpcomingMicrosoftEvents = `-- name: GetUpcomingMicrosoftEvents :many
SELECT id, user_id, event_id, calendar_id, calendar_name, subject, body_preview, body_content, body_content_type, location_display_name, location_address, location_coordinates, start_datetime, start_timezone, end_datetime, end_timezone, is_all_day, recurrence, series_master_id, type, attendees, organizer_email, organizer_name, is_online_meeting, online_meeting_provider, online_meeting_url, online_meeting_join_url, response_status, response_time, importance, sensitivity, show_as, is_cancelled, is_reminder_on, reminder_minutes_before_start, categories, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_calendar_events
WHERE user_id = $1
  AND start_datetime >= NOW()
  AND is_cancelled = FALSE
ORDER BY start_datetime ASC
LIMIT $2
`

type GetUpcomingMicrosoftEventsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetUpcomingMicrosoftEvents(ctx context.Context, arg GetUpcomingMicrosoftEventsParams) ([]MicrosoftCalendarEvent, error) {
	rows, err := q.db.Query(ctx, getUpcomingMicrosoftEvents, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftCalendarEvent{}
	for rows.Next() {
		var i MicrosoftCalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.CalendarID,
			&i.CalendarName,
			&i.Subject,
			&i.BodyPreview,
			&i.BodyContent,
			&i.BodyContentType,
			&i.LocationDisplayName,
			&i.LocationAddress,
			&i.LocationCoordinates,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.EndDatetime,
			&i.EndTimezone,
			&i.IsAllDay,
			&i.Recurrence,
			&i.SeriesMasterID,
			&i.Type,
			&i.Attendees,
			&i.OrganizerEmail,
			&i.OrganizerName,
			&i.IsOnlineMeeting,
			&i.OnlineMeetingProvider,
			&i.OnlineMeetingUrl,
			&i.OnlineMeetingJoinUrl,
			&i.ResponseStatus,
			&i.ResponseTime,
			&i.Importance,
			&i.Sensitivity,
			&i.ShowAs,
			&i.IsCancelled,
			&i.IsReminderOn,
			&i.ReminderMinutesBeforeStart,
			&i.Categories,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMicrosoftMailAsRead = `-- name: MarkMicrosoftMailAsRead :exec
UPDATE microsoft_mail_messages
SET is_read = TRUE, updated_at = NOW()
WHERE user_id = $1 AND message_id = $2
`

type MarkMicrosoftMailAsReadParams struct {
	UserID    string `json:"user_id"`
	MessageID string `json:"message_id"`
}

func (q *Queries) MarkMicrosoftMailAsRead(ctx context.Context, arg MarkMicrosoftMailAsReadParams) error {
	_, err := q.db.Exec(ctx, markMicrosoftMailAsRead, arg.UserID, arg.MessageID)
	return err
}

const markMicrosoftToDoTaskComplete = `-- name: MarkMicrosoftToDoTaskComplete :exec
UPDATE microsoft_todo_tasks
SET status = 'completed',
    completed_datetime = NOW(),
    updated_at = NOW()
WHERE user_id = $1 AND task_id = $2
`

type MarkMicrosoftToDoTaskCompleteParams struct {
	UserID string `json:"user_id"`
	TaskID string `json:"task_id"`
}

func (q *Queries) MarkMicrosoftToDoTaskComplete(ctx context.Context, arg MarkMicrosoftToDoTaskCompleteParams) error {
	_, err := q.db.Exec(ctx, markMicrosoftToDoTaskComplete, arg.UserID, arg.TaskID)
	return err
}

const searchMicrosoftContacts = `-- name: SearchMicrosoftContacts :many
SELECT id, user_id, contact_id, display_name, given_name, surname, middle_name, nickname, title, email_addresses, phone_numbers, addresses, im_addresses, websites, company_name, department, job_title, office_location, profession, manager, assistant_name, birthday, spouse_name, personal_notes, photo_url, categories, parent_folder_id, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_contacts
WHERE user_id = $1
  AND (display_name ILIKE $2 OR company_name ILIKE $2)
ORDER BY display_name NULLS LAST
LIMIT $3
`

type SearchMicrosoftContactsParams struct {
	UserID      string  `json:"user_id"`
	DisplayName *string `json:"display_name"`
	Limit       int32   `json:"limit"`
}

func (q *Queries) SearchMicrosoftContacts(ctx context.Context, arg SearchMicrosoftContactsParams) ([]MicrosoftContact, error) {
	rows, err := q.db.Query(ctx, searchMicrosoftContacts, arg.UserID, arg.DisplayName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftContact{}
	for rows.Next() {
		var i MicrosoftContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContactID,
			&i.DisplayName,
			&i.GivenName,
			&i.Surname,
			&i.MiddleName,
			&i.Nickname,
			&i.Title,
			&i.EmailAddresses,
			&i.PhoneNumbers,
			&i.Addresses,
			&i.ImAddresses,
			&i.Websites,
			&i.CompanyName,
			&i.Department,
			&i.JobTitle,
			&i.OfficeLocation,
			&i.Profession,
			&i.Manager,
			&i.AssistantName,
			&i.Birthday,
			&i.SpouseName,
			&i.PersonalNotes,
			&i.PhotoUrl,
			&i.Categories,
			&i.ParentFolderID,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMicrosoftMail = `-- name: SearchMicrosoftMail :many
SELECT id, user_id, message_id, conversation_id, subject, body_preview, body_content, body_content_type, importance, from_email, from_name, to_recipients, cc_recipients, bcc_recipients, reply_to, is_read, is_draft, has_attachments, folder_id, folder_name, categories, flag_status, attachments, received_datetime, sent_datetime, created_datetime, last_modified_datetime, synced_at, created_at, updated_at FROM microsoft_mail_messages
WHERE user_id = $1
  AND (subject ILIKE $2 OR body_preview ILIKE $2 OR from_email ILIKE $2)
ORDER BY received_datetime DESC NULLS LAST
LIMIT $3
`

type SearchMicrosoftMailParams struct {
	UserID  string  `json:"user_id"`
	Subject *string `json:"subject"`
	Limit   int32   `json:"limit"`
}

func (q *Queries) SearchMicrosoftMail(ctx context.Context, arg SearchMicrosoftMailParams) ([]MicrosoftMailMessage, error) {
	rows, err := q.db.Query(ctx, searchMicrosoftMail, arg.UserID, arg.Subject, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftMailMessage{}
	for rows.Next() {
		var i MicrosoftMailMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MessageID,
			&i.ConversationID,
			&i.Subject,
			&i.BodyPreview,
			&i.BodyContent,
			&i.BodyContentType,
			&i.Importance,
			&i.FromEmail,
			&i.FromName,
			&i.ToRecipients,
			&i.CcRecipients,
			&i.BccRecipients,
			&i.ReplyTo,
			&i.IsRead,
			&i.IsDraft,
			&i.HasAttachments,
			&i.FolderID,
			&i.FolderName,
			&i.Categories,
			&i.FlagStatus,
			&i.Attachments,
			&i.ReceivedDatetime,
			&i.SentDatetime,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMicrosoftOneDriveFiles = `-- name: SearchMicrosoftOneDriveFiles :many
SELECT id, user_id, item_id, name, description, mime_type, size_bytes, parent_reference_id, parent_reference_path, web_url, is_folder, folder_child_count, file_hash, shared, shared_scope, shared_link, permissions, created_by_user_email, created_by_user_name, last_modified_by_user_email, last_modified_by_user_name, created_datetime, last_modified_datetime, download_url, thumbnails, synced_at, created_at, updated_at FROM microsoft_onedrive_files
WHERE user_id = $1 AND name ILIKE $2
ORDER BY last_modified_datetime DESC NULLS LAST
LIMIT $3
`

type SearchMicrosoftOneDriveFilesParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) SearchMicrosoftOneDriveFiles(ctx context.Context, arg SearchMicrosoftOneDriveFilesParams) ([]MicrosoftOnedriveFile, error) {
	rows, err := q.db.Query(ctx, searchMicrosoftOneDriveFiles, arg.UserID, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MicrosoftOnedriveFile{}
	for rows.Next() {
		var i MicrosoftOnedriveFile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemID,
			&i.Name,
			&i.Description,
			&i.MimeType,
			&i.SizeBytes,
			&i.ParentReferenceID,
			&i.ParentReferencePath,
			&i.WebUrl,
			&i.IsFolder,
			&i.FolderChildCount,
			&i.FileHash,
			&i.Shared,
			&i.SharedScope,
			&i.SharedLink,
			&i.Permissions,
			&i.CreatedByUserEmail,
			&i.CreatedByUserName,
			&i.LastModifiedByUserEmail,
			&i.LastModifiedByUserName,
			&i.CreatedDatetime,
			&i.LastModifiedDatetime,
			&i.DownloadUrl,
			&i.Thumbnails,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMicrosoftCalendarEvent = `-- name: UpsertMicrosoftCalendarEvent :one

INSERT INTO microsoft_calendar_events (
    user_id, event_id, calendar_id, calendar_name, subject, body_preview,
    body_content, body_content_type, location_display_name, location_address,
    location_coordinates, start_datetime, start_timezone, end_datetime, end_timezone,
    is_all_day, recurrence, series_master_id, type, attendees, organizer_email,
    organizer_name, is_online_meeting, online_meeting_provider, online_meeting_url,
    online_meeting_join_url, response_status, response_time, importance, sensitivity,
    show_as, is_cancelled, is_reminder_on, reminder_minutes_before_start, categories,
    created_datetime, last_modified_datetime
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37)
ON CONFLICT (user_id, event_id) DO UPDATE SET
    calendar_id = EXCLUDED.calendar_id,
    calendar_name = EXCLUDED.calendar_name,
    subject = EXCLUDED.subject,
    body_preview = EXCLUDED.body_preview,
    body_content = EXCLUDED.body_content,
    location_display_name = EXCLUDED.location_display_name,
    location_address = EXCLUDED.location_address,
    start_datetime = EXCLUDED.start_datetime,
    start_timezone = EXCLUDED.start_timezone,
    end_datetime = EXCLUDED.end_datetime,
    end_timezone = EXCLUDED.end_timezone,
    is_all_day = EXCLUDED.is_all_day,
    attendees = EXCLUDED.attendees,
    response_status = EXCLUDED.response_status,
    response_time = EXCLUDED.response_time,
    is_online_meeting = EXCLUDED.is_online_meeting,
    online_meeting_url = EXCLUDED.online_meeting_url,
    online_meeting_join_url = EXCLUDED.online_meeting_join_url,
    is_cancelled = EXCLUDED.is_cancelled,
    categories = EXCLUDED.categories,
    last_modified_datetime = EXCLUDED.last_modified_datetime,
    synced_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, event_id, calendar_id, calendar_name, subject, body_preview, body_content, body_content_type, location_display_name, location_address, location_coordinates, start_datetime, start_timezone, end_datetime, end_timezone, is_all_day, recurrence, series_master_id, type, attendees, organizer_email, organizer_name, is_online_meeting, online_meeting_provider, online_meeting_url, online_meeting_join_url, response_status, response_time, importance, sensitivity, show_as, is_cancelled, is_reminder_on, reminder_minutes_before_start, categories, created_datetime, last_modified_datetime, synced_at, created_at, updated_at
`

type UpsertMicrosoftCalendarEventParams struct {
	UserID                     string             `json:"user_id"`
	EventID                    string             `json:"event_id"`
	CalendarID                 *string            `json:"calendar_id"`
	CalendarName               *string            `json:"calendar_name"`
	Subject                    *string            `json:"subject"`
	BodyPreview                *string            `json:"body_preview"`
	BodyContent                *string            `json:"body_content"`
	BodyContentType            *string            `json:"body_content_type"`
	LocationDisplayName        *string            `json:"location_display_name"`
	LocationAddress            []byte             `json:"location_address"`
	LocationCoordinates        []byte             `json:"location_coordinates"`
	StartDatetime              pgtype.Timestamptz `json:"start_datetime"`
	StartTimezone              *string            `json:"start_timezone"`
	EndDatetime                pgtype.Timestamptz `json:"end_datetime"`
	EndTimezone                *string            `json:"end_timezone"`
	IsAllDay                   *bool              `json:"is_all_day"`
	Recurrence                 []byte             `json:"recurrence"`
	SeriesMasterID             *string            `json:"series_master_id"`
	Type                       *string            `json:"type"`
	Attendees                  []byte             `json:"attendees"`
	OrganizerEmail             *string            `json:"organizer_email"`
	OrganizerName              *string            `json:"organizer_name"`
	IsOnlineMeeting            *bool              `json:"is_online_meeting"`
	OnlineMeetingProvider      *string            `json:"online_meeting_provider"`
	OnlineMeetingUrl           *string            `json:"online_meeting_url"`
	OnlineMeetingJoinUrl       *string            `json:"online_meeting_join_url"`
	ResponseStatus             *string            `json:"response_status"`
	ResponseTime               pgtype.Timestamptz `json:"response_time"`
	Importance                 *string            `json:"importance"`
	Sensitivity                *string            `json:"sensitivity"`
	ShowAs                     *string            `json:"show_as"`
	IsCancelled                *bool              `json:"is_cancelled"`
	IsReminderOn               *bool              `json:"is_reminder_on"`
	ReminderMinutesBeforeStart *int32             `json:"reminder_minutes_before_start"`
	Categories                 []byte             `json:"categories"`
	CreatedDatetime            pgtype.Timestamptz `json:"created_datetime"`
	LastModifiedDatetime       pgtype.Timestamptz `json:"last_modified_datetime"`
}

// ============================================================================
// Microsoft Calendar Events
// ============================================================================
func (q *Queries) UpsertMicrosoftCalendarEvent(ctx context.Context, arg UpsertMicrosoftCalendarEventParams) (MicrosoftCalendarEvent, error) {
	row := q.db.QueryRow(ctx, upsertMicrosoftCalendarEvent,
		arg.UserID,
		arg.EventID,
		arg.CalendarID,
		arg.CalendarName,
		arg.Subject,
		arg.BodyPreview,
		arg.BodyContent,
		arg.BodyContentType,
		arg.LocationDisplayName,
		arg.LocationAddress,
		arg.LocationCoordinates,
		arg.StartDatetime,
		arg.StartTimezone,
		arg.EndDatetime,
		arg.EndTimezone,
		arg.IsAllDay,
		arg.Recurrence,
		arg.SeriesMasterID,
		arg.Type,
		arg.Attendees,
		arg.OrganizerEmail,
		arg.OrganizerName,
		arg.IsOnlineMeeting,
		arg.OnlineMeetingProvider,
		arg.OnlineMeetingUrl,
		arg.OnlineMeetingJoinUrl,
		arg.ResponseStatus,
		arg.ResponseTime,
		arg.Importance,
		arg.Sensitivity,
		arg.ShowAs,
		arg.IsCancelled,
		arg.IsReminderOn,
		arg.ReminderMinutesBeforeStart,
		arg.Categories,
		arg.CreatedDatetime,
		arg.LastModifiedDatetime,
	)
	var i MicrosoftCalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CalendarID,
		&i.CalendarName,
		&i.Subject,
		&i.BodyPreview,
		&i.BodyContent,
		&i.BodyContentType,
		&i.LocationDisplayName,
		&i.LocationAddress,
		&i.LocationCoordinates,
		&i.StartDatetime,
		&i.StartTimezone,
		&i.EndDatetime,
		&i.EndTimezone,
		&i.IsAllDay,
		&i.Recurrence,
		&i.SeriesMasterID,
		&i.Type,
		&i.Attendees,
		&i.OrganizerEmail,
		&i.OrganizerName,
		&i.IsOnlineMeeting,
		&i.OnlineMeetingProvider,
		&i.OnlineMeetingUrl,
		&i.OnlineMeetingJoinUrl,
		&i.ResponseStatus,
		&i.ResponseTime,
		&i.Importance,
		&i.Sensitivity,
		&i.ShowAs,
		&i.IsCancelled,
		&i.IsReminderOn,
		&i.ReminderMinutesBeforeStart,
		&i.Categories,
		&i.CreatedDatetime,
		&i.LastModifiedDatetime,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMicrosoftContact = `-- name: UpsertMicrosoftContact :one

INSERT INTO microsoft_contacts (
    user_id, contact_id, display_name, given_name, surname, middle_name, nickname,
    title, email_addresses, phone_numbers, addresses, im_addresses, websites,
    company_name, department, job_title, office_location, profession, manager,
    assistant_name, birthday, spouse_name, personal_notes, photo_url, categories,
    parent_folder_id, created_datetime, last_modified_datetime
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28)
ON CONFLICT (user_id, contact_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    given_name = EXCLUDED.given_name,
    surname = EXCLUDED.surname,
    middle_name = EXCLUDED.middle_name,
    nickname = EXCLUDED.nickname,
    title = EXCLUDED.title,
    email_addresses = EXCLUDED.email_addresses,
    phone_numbers = EXCLUDED.phone_numbers,
    addresses = EXCLUDED.addresses,
    im_addresses = EXCLUDED.im_addresses,
    websites = EXCLUDED.websites,
    company_name = EXCLUDED.company_name,
    department = EXCLUDED.department,
    job_title = EXCLUDED.job_title,
    office_location = EXCLUDED.office_location,
    manager = EXCLUDED.manager,
    birthday = EXCLUDED.birthday,
    spouse_name = EXCLUDED.spouse_name,
    personal_notes = EXCLUDED.personal_notes,
    photo_url = EXCLUDED.photo_url,
    categories = EXCLUDED.categories,
    last_modified_datetime = EXCLUDED.last_modified_datetime,
    synced_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, contact_id, display_name, given_name, surname, middle_name, nickname, title, email_addresses, phone_numbers, addresses, im_addresses, websites, company_name, department, job_title, office_location, profession, manager, assistant_name, birthday, spouse_name, personal_notes, photo_url, categories, parent_folder_id, created_datetime, last_modified_datetime, synced_at, created_at, updated_at
`

type UpsertMicrosoftContactParams struct {
	UserID               string             `json:"user_id"`
	ContactID            string             `json:"contact_id"`
	DisplayName          *string            `json:"display_name"`
	GivenName            *string            `json:"given_name"`
	Surname              *string            `json:"surname"`
	MiddleName           *string            `json:"middle_name"`
	Nickname             *string            `json:"nickname"`
	Title                *string            `json:"title"`
	EmailAddresses       []byte             `json:"email_addresses"`
	PhoneNumbers         []byte             `json:"phone_numbers"`
	Addresses            []byte             `json:"addresses"`
	ImAddresses          []byte             `json:"im_addresses"`
	Websites             []byte             `json:"websites"`
	CompanyName          *string            `json:"company_name"`
	Department           *string            `json:"department"`
	JobTitle             *string            `json:"job_title"`
	OfficeLocation       *string            `json:"office_location"`
	Profession           *string            `json:"profession"`
	Manager              *string            `json:"manager"`
	AssistantName        *string            `json:"assistant_name"`
	Birthday             pgtype.Date        `json:"birthday"`
	SpouseName           *string            `json:"spouse_name"`
	PersonalNotes        *string            `json:"personal_notes"`
	PhotoUrl             *string            `json:"photo_url"`
	Categories           []byte             `json:"categories"`
	ParentFolderID       *string            `json:"parent_folder_id"`
	CreatedDatetime      pgtype.Timestamptz `json:"created_datetime"`
	LastModifiedDatetime pgtype.Timestamptz `json:"last_modified_datetime"`
}

// ============================================================================
// Microsoft Contacts
// ============================================================================
func (q *Queries) UpsertMicrosoftContact(ctx context.Context, arg UpsertMicrosoftContactParams) (MicrosoftContact, error) {
	row := q.db.QueryRow(ctx, upsertMicrosoftContact,
		arg.UserID,
		arg.ContactID,
		arg.DisplayName,
		arg.GivenName,
		arg.Surname,
		arg.MiddleName,
		arg.Nickname,
		arg.Title,
		arg.EmailAddresses,
		arg.PhoneNumbers,
		arg.Addresses,
		arg.ImAddresses,
		arg.Websites,
		arg.CompanyName,
		arg.Department,
		arg.JobTitle,
		arg.OfficeLocation,
		arg.Profession,
		arg.Manager,
		arg.AssistantName,
		arg.Birthday,
		arg.SpouseName,
		arg.PersonalNotes,
		arg.PhotoUrl,
		arg.Categories,
		arg.ParentFolderID,
		arg.CreatedDatetime,
		arg.LastModifiedDatetime,
	)
	var i MicrosoftContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContactID,
		&i.DisplayName,
		&i.GivenName,
		&i.Surname,
		&i.MiddleName,
		&i.Nickname,
		&i.Title,
		&i.EmailAddresses,
		&i.PhoneNumbers,
		&i.Addresses,
		&i.ImAddresses,
		&i.Websites,
		&i.CompanyName,
		&i.Department,
		&i.JobTitle,
		&i.OfficeLocation,
		&i.Profession,
		&i.Manager,
		&i.AssistantName,
		&i.Birthday,
		&i.SpouseName,
		&i.PersonalNotes,
		&i.PhotoUrl,
		&i.Categories,
		&i.ParentFolderID,
		&i.CreatedDatetime,
		&i.LastModifiedDatetime,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMicrosoftMailMessage = `-- name: UpsertMicrosoftMailMessage :one

INSERT INTO microsoft_mail_messages (
    user_id, message_id, conversation_id, subject, body_preview,
    body_content, body_content_type, importance, from_email, from_name,
    to_recipients, cc_recipients, bcc_recipients, reply_to,
    is_read, is_draft, has_attachments, folder_id, folder_name,
    categories, flag_status, attachments, received_datetime, sent_datetime,
    created_datetime, last_modified_datetime
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26)
ON CONFLICT (user_id, message_id) DO UPDATE SET
    conversation_id = EXCLUDED.conversation_id,
    subject = EXCLUDED.subject,
    body_preview = EXCLUDED.body_preview,
    body_content = EXCLUDED.body_content,
    body_content_type = EXCLUDED.body_content_type,
    importance = EXCLUDED.importance,
    is_read = EXCLUDED.is_read,
    is_draft = EXCLUDED.is_draft,
    has_attachments = EXCLUDED.has_attachments,
    folder_id = EXCLUDED.folder_id,
    folder_name = EXCLUDED.folder_name,
    categories = EXCLUDED.categories,
    flag_status = EXCLUDED.flag_status,
    attachments = EXCLUDED.attachments,
    last_modified_datetime = EXCLUDED.last_modified_datetime,
    synced_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, message_id, conversation_id, subject, body_preview, body_content, body_content_type, importance, from_email, from_name, to_recipients, cc_recipients, bcc_recipients, reply_to, is_read, is_draft, has_attachments, folder_id, folder_name, categories, flag_status, attachments, received_datetime, sent_datetime, created_datetime, last_modified_datetime, synced_at, created_at, updated_at
`

type UpsertMicrosoftMailMessageParams struct {
	UserID               string             `json:"user_id"`
	MessageID            string             `json:"message_id"`
	ConversationID       *string            `json:"conversation_id"`
	Subject              *string            `json:"subject"`
	BodyPreview          *string            `json:"body_preview"`
	BodyContent          *string            `json:"body_content"`
	BodyContentType      *string            `json:"body_content_type"`
	Importance           *string            `json:"importance"`
	FromEmail            *string            `json:"from_email"`
	FromName             *string            `json:"from_name"`
	ToRecipients         []byte             `json:"to_recipients"`
	CcRecipients         []byte             `json:"cc_recipients"`
	BccRecipients        []byte             `json:"bcc_recipients"`
	ReplyTo              []byte             `json:"reply_to"`
	IsRead               *bool              `json:"is_read"`
	IsDraft              *bool              `json:"is_draft"`
	HasAttachments       *bool              `json:"has_attachments"`
	FolderID             *string            `json:"folder_id"`
	FolderName           *string            `json:"folder_name"`
	Categories           []byte             `json:"categories"`
	FlagStatus           *string            `json:"flag_status"`
	Attachments          []byte             `json:"attachments"`
	ReceivedDatetime     pgtype.Timestamptz `json:"received_datetime"`
	SentDatetime         pgtype.Timestamptz `json:"sent_datetime"`
	CreatedDatetime      pgtype.Timestamptz `json:"created_datetime"`
	LastModifiedDatetime pgtype.Timestamptz `json:"last_modified_datetime"`
}

// ============================================================================
// Microsoft Mail Messages
// ============================================================================
func (q *Queries) UpsertMicrosoftMailMessage(ctx context.Context, arg UpsertMicrosoftMailMessageParams) (MicrosoftMailMessage, error) {
	row := q.db.QueryRow(ctx, upsertMicrosoftMailMessage,
		arg.UserID,
		arg.MessageID,
		arg.ConversationID,
		arg.Subject,
		arg.BodyPreview,
		arg.BodyContent,
		arg.BodyContentType,
		arg.Importance,
		arg.FromEmail,
		arg.FromName,
		arg.ToRecipients,
		arg.CcRecipients,
		arg.BccRecipients,
		arg.ReplyTo,
		arg.IsRead,
		arg.IsDraft,
		arg.HasAttachments,
		arg.FolderID,
		arg.FolderName,
		arg.Categories,
		arg.FlagStatus,
		arg.Attachments,
		arg.ReceivedDatetime,
		arg.SentDatetime,
		arg.CreatedDatetime,
		arg.LastModifiedDatetime,
	)
	var i MicrosoftMailMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessageID,
		&i.ConversationID,
		&i.Subject,
		&i.BodyPreview,
		&i.BodyContent,
		&i.BodyContentType,
		&i.Importance,
		&i.FromEmail,
		&i.FromName,
		&i.ToRecipients,
		&i.CcRecipients,
		&i.BccRecipients,
		&i.ReplyTo,
		&i.IsRead,
		&i.IsDraft,
		&i.HasAttachments,
		&i.FolderID,
		&i.FolderName,
		&i.Categories,
		&i.FlagStatus,
		&i.Attachments,
		&i.ReceivedDatetime,
		&i.SentDatetime,
		&i.CreatedDatetime,
		&i.LastModifiedDatetime,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMicrosoftOneDriveFile = `-- name: UpsertMicrosoftOneDriveFile :one

INSERT INTO microsoft_onedrive_files (
    user_id, item_id, name, description, mime_type, size_bytes,
    parent_reference_id, parent_reference_path, web_url, is_folder,
    folder_child_count, file_hash, shared, shared_scope, shared_link,
    permissions, created_by_user_email, created_by_user_name,
    last_modified_by_user_email, last_modified_by_user_name,
    created_datetime, last_modified_datetime, download_url, thumbnails
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24)
ON CONFLICT (user_id, item_id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    mime_type = EXCLUDED.mime_type,
    size_bytes = EXCLUDED.size_bytes,
    parent_reference_id = EXCLUDED.parent_reference_id,
    parent_reference_path = EXCLUDED.parent_reference_path,
    web_url = EXCLUDED.web_url,
    is_folder = EXCLUDED.is_folder,
    folder_child_count = EXCLUDED.folder_child_count,
    file_hash = EXCLUDED.file_hash,
    shared = EXCLUDED.shared,
    shared_scope = EXCLUDED.shared_scope,
    shared_link = EXCLUDED.shared_link,
    permissions = EXCLUDED.permissions,
    last_modified_by_user_email = EXCLUDED.last_modified_by_user_email,
    last_modified_by_user_name = EXCLUDED.last_modified_by_user_name,
    last_modified_datetime = EXCLUDED.last_modified_datetime,
    download_url = EXCLUDED.download_url,
    thumbnails = EXCLUDED.thumbnails,
    synced_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, item_id, name, description, mime_type, size_bytes, parent_reference_id, parent_reference_path, web_url, is_folder, folder_child_count, file_hash, shared, shared_scope, shared_link, permissions, created_by_user_email, created_by_user_name, last_modified_by_user_email, last_modified_by_user_name, created_datetime, last_modified_datetime, download_url, thumbnails, synced_at, created_at, updated_at
`

type UpsertMicrosoftOneDriveFileParams struct {
	UserID                  string             `json:"user_id"`
	ItemID                  string             `json:"item_id"`
	Name                    string             `json:"name"`
	Description             *string            `json:"description"`
	MimeType                *string            `json:"mime_type"`
	SizeBytes               *int64             `json:"size_bytes"`
	ParentReferenceID       *string            `json:"parent_reference_id"`
	ParentReferencePath     *string            `json:"parent_reference_path"`
	WebUrl                  *string            `json:"web_url"`
	IsFolder                *bool              `json:"is_folder"`
	FolderChildCount        *int32             `json:"folder_child_count"`
	FileHash                *string            `json:"file_hash"`
	Shared                  *bool              `json:"shared"`
	SharedScope             *string            `json:"shared_scope"`
	SharedLink              []byte             `json:"shared_link"`
	Permissions             []byte             `json:"permissions"`
	CreatedByUserEmail      *string            `json:"created_by_user_email"`
	CreatedByUserName       *string            `json:"created_by_user_name"`
	LastModifiedByUserEmail *string            `json:"last_modified_by_user_email"`
	LastModifiedByUserName  *string            `json:"last_modified_by_user_name"`
	CreatedDatetime         pgtype.Timestamptz `json:"created_datetime"`
	LastModifiedDatetime    pgtype.Timestamptz `json:"last_modified_datetime"`
	DownloadUrl             *string            `json:"download_url"`
	Thumbnails              []byte             `json:"thumbnails"`
}

// ============================================================================
// Microsoft OneDrive Files
// ============================================================================
func (q *Queries) UpsertMicrosoftOneDriveFile(ctx context.Context, arg UpsertMicrosoftOneDriveFileParams) (MicrosoftOnedriveFile, error) {
	row := q.db.QueryRow(ctx, upsertMicrosoftOneDriveFile,
		arg.UserID,
		arg.ItemID,
		arg.Name,
		arg.Description,
		arg.MimeType,
		arg.SizeBytes,
		arg.ParentReferenceID,
		arg.ParentReferencePath,
		arg.WebUrl,
		arg.IsFolder,
		arg.FolderChildCount,
		arg.FileHash,
		arg.Shared,
		arg.SharedScope,
		arg.SharedLink,
		arg.Permissions,
		arg.CreatedByUserEmail,
		arg.CreatedByUserName,
		arg.LastModifiedByUserEmail,
		arg.LastModifiedByUserName,
		arg.CreatedDatetime,
		arg.LastModifiedDatetime,
		arg.DownloadUrl,
		arg.Thumbnails,
	)
	var i MicrosoftOnedriveFile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Name,
		&i.Description,
		&i.MimeType,
		&i.SizeBytes,
		&i.ParentReferenceID,
		&i.ParentReferencePath,
		&i.WebUrl,
		&i.IsFolder,
		&i.FolderChildCount,
		&i.FileHash,
		&i.Shared,
		&i.SharedScope,
		&i.SharedLink,
		&i.Permissions,
		&i.CreatedByUserEmail,
		&i.CreatedByUserName,
		&i.LastModifiedByUserEmail,
		&i.LastModifiedByUserName,
		&i.CreatedDatetime,
		&i.LastModifiedDatetime,
		&i.DownloadUrl,
		&i.Thumbnails,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMicrosoftToDoList = `-- name: UpsertMicrosoftToDoList :one

INSERT INTO microsoft_todo_lists (
    user_id, list_id, display_name, is_owner, is_shared, wellknown_list_name
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, list_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    is_owner = EXCLUDED.is_owner,
    is_shared = EXCLUDED.is_shared,
    wellknown_list_name = EXCLUDED.wellknown_list_name,
    synced_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, list_id, display_name, is_owner, is_shared, wellknown_list_name, synced_at, created_at, updated_at
`

type UpsertMicrosoftToDoListParams struct {
	UserID            string  `json:"user_id"`
	ListID            string  `json:"list_id"`
	DisplayName       string  `json:"display_name"`
	IsOwner           *bool   `json:"is_owner"`
	IsShared          *bool   `json:"is_shared"`
	WellknownListName *string `json:"wellknown_list_name"`
}

// ============================================================================
// Microsoft To Do Lists
// ============================================================================
func (q *Queries) UpsertMicrosoftToDoList(ctx context.Context, arg UpsertMicrosoftToDoListParams) (MicrosoftTodoList, error) {
	row := q.db.QueryRow(ctx, upsertMicrosoftToDoList,
		arg.UserID,
		arg.ListID,
		arg.DisplayName,
		arg.IsOwner,
		arg.IsShared,
		arg.WellknownListName,
	)
	var i MicrosoftTodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListID,
		&i.DisplayName,
		&i.IsOwner,
		&i.IsShared,
		&i.WellknownListName,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMicrosoftToDoTask = `-- name: UpsertMicrosoftToDoTask :one

INSERT INTO microsoft_todo_tasks (
    user_id, task_id, list_id, title, body_content, body_content_type,
    importance, status, due_datetime, due_timezone, start_datetime, start_timezone,
    completed_datetime, completed_timezone, recurrence, is_reminder_on,
    reminder_datetime, categories, linked_resources, checklist_items,
    created_datetime, last_modified_datetime
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
ON CONFLICT (user_id, task_id) DO UPDATE SET
    list_id = EXCLUDED.list_id,
    title = EXCLUDED.title,
    body_content = EXCLUDED.body_content,
    body_content_type = EXCLUDED.body_content_type,
    importance = EXCLUDED.importance,
    status = EXCLUDED.status,
    due_datetime = EXCLUDED.due_datetime,
    due_timezone = EXCLUDED.due_timezone,
    start_datetime = EXCLUDED.start_datetime,
    start_timezone = EXCLUDED.start_timezone,
    completed_datetime = EXCLUDED.completed_datetime,
    completed_timezone = EXCLUDED.completed_timezone,
    recurrence = EXCLUDED.recurrence,
    is_reminder_on = EXCLUDED.is_reminder_on,
    reminder_datetime = EXCLUDED.reminder_datetime,
    categories = EXCLUDED.categories,
    linked_resources = EXCLUDED.linked_resources,
    checklist_items = EXCLUDED.checklist_items,
    last_modified_datetime = EXCLUDED.last_modified_datetime,
    synced_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, task_id, list_id, title, body_content, body_content_type, importance, status, due_datetime, due_timezone, start_datetime, start_timezone, completed_datetime, completed_timezone, recurrence, is_reminder_on, reminder_datetime, categories, linked_resources, checklist_items, created_datetime, last_modified_datetime, synced_at, created_at, updated_at
`

type UpsertMicrosoftToDoTaskParams struct {
	UserID               string             `json:"user_id"`
	TaskID               string             `json:"task_id"`
	ListID               string             `json:"list_id"`
	Title                string             `json:"title"`
	BodyContent          *string            `json:"body_content"`
	BodyContentType      *string            `json:"body_content_type"`
	Importance           *string            `json:"importance"`
	Status               *string            `json:"status"`
	DueDatetime          pgtype.Timestamptz `json:"due_datetime"`
	DueTimezone          *string            `json:"due_timezone"`
	StartDatetime        pgtype.Timestamptz `json:"start_datetime"`
	StartTimezone        *string            `json:"start_timezone"`
	CompletedDatetime    pgtype.Timestamptz `json:"completed_datetime"`
	CompletedTimezone    *string            `json:"completed_timezone"`
	Recurrence           []byte             `json:"recurrence"`
	IsReminderOn         *bool              `json:"is_reminder_on"`
	ReminderDatetime     pgtype.Timestamptz `json:"reminder_datetime"`
	Categories           []byte             `json:"categories"`
	LinkedResources      []byte             `json:"linked_resources"`
	ChecklistItems       []byte             `json:"checklist_items"`
	CreatedDatetime      pgtype.Timestamptz `json:"created_datetime"`
	LastModifiedDatetime pgtype.Timestamptz `json:"last_modified_datetime"`
}

// ============================================================================
// Microsoft To Do Tasks
// ============================================================================
func (q *Queries) UpsertMicrosoftToDoTask(ctx context.Context, arg UpsertMicrosoftToDoTaskParams) (MicrosoftTodoTask, error) {
	row := q.db.QueryRow(ctx, upsertMicrosoftToDoTask,
		arg.UserID,
		arg.TaskID,
		arg.ListID,
		arg.Title,
		arg.BodyContent,
		arg.BodyContentType,
		arg.Importance,
		arg.Status,
		arg.DueDatetime,
		arg.DueTimezone,
		arg.StartDatetime,
		arg.StartTimezone,
		arg.CompletedDatetime,
		arg.CompletedTimezone,
		arg.Recurrence,
		arg.IsReminderOn,
		arg.ReminderDatetime,
		arg.Categories,
		arg.LinkedResources,
		arg.ChecklistItems,
		arg.CreatedDatetime,
		arg.LastModifiedDatetime,
	)
	var i MicrosoftTodoTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.ListID,
		&i.Title,
		&i.BodyContent,
		&i.BodyContentType,
		&i.Importance,
		&i.Status,
		&i.DueDatetime,
		&i.DueTimezone,
		&i.StartDatetime,
		&i.StartTimezone,
		&i.CompletedDatetime,
		&i.CompletedTimezone,
		&i.Recurrence,
		&i.IsReminderOn,
		&i.ReminderDatetime,
		&i.Categories,
		&i.LinkedResources,
		&i.ChecklistItems,
		&i.CreatedDatetime,
		&i.LastModifiedDatetime,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMicrosoftToken = `-- name: UpsertMicrosoftToken :one


INSERT INTO microsoft_oauth_tokens (
    user_id, access_token, refresh_token, expiry, scopes,
    microsoft_id, microsoft_email
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id) DO UPDATE SET
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    expiry = EXCLUDED.expiry,
    scopes = EXCLUDED.scopes,
    microsoft_id = EXCLUDED.microsoft_id,
    microsoft_email = EXCLUDED.microsoft_email,
    updated_at = NOW()
RETURNING id, user_id, access_token, refresh_token, expiry, scopes, microsoft_id, microsoft_email, created_at, updated_at
`

type UpsertMicrosoftTokenParams struct {
	UserID         string             `json:"user_id"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   *string            `json:"refresh_token"`
	Expiry         pgtype.Timestamptz `json:"expiry"`
	Scopes         []string           `json:"scopes"`
	MicrosoftID    *string            `json:"microsoft_id"`
	MicrosoftEmail *string            `json:"microsoft_email"`
}

// Microsoft 365 Queries
// SQLC queries for Microsoft 365 integrations (Outlook, OneDrive, To Do)
// ============================================================================
// Microsoft OAuth Tokens
// ============================================================================
func (q *Queries) UpsertMicrosoftToken(ctx context.Context, arg UpsertMicrosoftTokenParams) (MicrosoftOauthToken, error) {
	row := q.db.QueryRow(ctx, upsertMicrosoftToken,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Expiry,
		arg.Scopes,
		arg.MicrosoftID,
		arg.MicrosoftEmail,
	)
	var i MicrosoftOauthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expiry,
		&i.Scopes,
		&i.MicrosoftID,
		&i.MicrosoftEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
