// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: research.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const checkDuplicateSourceByHash = `-- name: CheckDuplicateSourceByHash :one
SELECT id, task_id, title, url
FROM research_sources
WHERE task_id = $1
  AND content_hash = $2
LIMIT 1
`

type CheckDuplicateSourceByHashParams struct {
	TaskID      pgtype.UUID `json:"task_id"`
	ContentHash *string     `json:"content_hash"`
}

type CheckDuplicateSourceByHashRow struct {
	ID     pgtype.UUID `json:"id"`
	TaskID pgtype.UUID `json:"task_id"`
	Title  string      `json:"title"`
	Url    *string     `json:"url"`
}

func (q *Queries) CheckDuplicateSourceByHash(ctx context.Context, arg CheckDuplicateSourceByHashParams) (CheckDuplicateSourceByHashRow, error) {
	row := q.db.QueryRow(ctx, checkDuplicateSourceByHash, arg.TaskID, arg.ContentHash)
	var i CheckDuplicateSourceByHashRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Url,
	)
	return i, err
}

const createResearchQuery = `-- name: CreateResearchQuery :one

INSERT INTO research_queries (
    task_id,
    question,
    search_type,
    weight,
    order_num,
    depends_on
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, task_id, question, search_type, weight, order_num, depends_on, results_count, completed, duration_ms, error_message, created_at, completed_at
`

type CreateResearchQueryParams struct {
	TaskID     pgtype.UUID    `json:"task_id"`
	Question   string         `json:"question"`
	SearchType string         `json:"search_type"`
	Weight     pgtype.Numeric `json:"weight"`
	OrderNum   int32          `json:"order_num"`
	DependsOn  []pgtype.UUID  `json:"depends_on"`
}

// ============================================================================
// RESEARCH QUERIES (Sub-questions)
// ============================================================================
func (q *Queries) CreateResearchQuery(ctx context.Context, arg CreateResearchQueryParams) (ResearchQuery, error) {
	row := q.db.QueryRow(ctx, createResearchQuery,
		arg.TaskID,
		arg.Question,
		arg.SearchType,
		arg.Weight,
		arg.OrderNum,
		arg.DependsOn,
	)
	var i ResearchQuery
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Question,
		&i.SearchType,
		&i.Weight,
		&i.OrderNum,
		&i.DependsOn,
		&i.ResultsCount,
		&i.Completed,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createResearchReport = `-- name: CreateResearchReport :one

INSERT INTO research_reports (
    task_id,
    content,
    format,
    citations,
    sections,
    word_count,
    citation_count,
    section_count,
    quality_score
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, task_id, content, format, citations, sections, word_count, citation_count, section_count, quality_score, created_at, updated_at
`

type CreateResearchReportParams struct {
	TaskID        pgtype.UUID    `json:"task_id"`
	Content       string         `json:"content"`
	Format        string         `json:"format"`
	Citations     []byte         `json:"citations"`
	Sections      []byte         `json:"sections"`
	WordCount     *int32         `json:"word_count"`
	CitationCount *int32         `json:"citation_count"`
	SectionCount  *int32         `json:"section_count"`
	QualityScore  pgtype.Numeric `json:"quality_score"`
}

// ============================================================================
// RESEARCH REPORTS
// ============================================================================
func (q *Queries) CreateResearchReport(ctx context.Context, arg CreateResearchReportParams) (ResearchReport, error) {
	row := q.db.QueryRow(ctx, createResearchReport,
		arg.TaskID,
		arg.Content,
		arg.Format,
		arg.Citations,
		arg.Sections,
		arg.WordCount,
		arg.CitationCount,
		arg.SectionCount,
		arg.QualityScore,
	)
	var i ResearchReport
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Format,
		&i.Citations,
		&i.Sections,
		&i.WordCount,
		&i.CitationCount,
		&i.SectionCount,
		&i.QualityScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createResearchSource = `-- name: CreateResearchSource :one

INSERT INTO research_sources (
    task_id,
    query_id,
    source_type,
    url,
    domain,
    title,
    content,
    snippet,
    relevance_score,
    author,
    published_at,
    content_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, task_id, query_id, source_type, url, domain, title, content, snippet, relevance_score, final_rank, cited, embedding, content_hash, author, published_at, fetched_at
`

type CreateResearchSourceParams struct {
	TaskID         pgtype.UUID        `json:"task_id"`
	QueryID        pgtype.UUID        `json:"query_id"`
	SourceType     string             `json:"source_type"`
	Url            *string            `json:"url"`
	Domain         *string            `json:"domain"`
	Title          string             `json:"title"`
	Content        *string            `json:"content"`
	Snippet        *string            `json:"snippet"`
	RelevanceScore pgtype.Numeric     `json:"relevance_score"`
	Author         *string            `json:"author"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	ContentHash    *string            `json:"content_hash"`
}

// ============================================================================
// RESEARCH SOURCES
// ============================================================================
func (q *Queries) CreateResearchSource(ctx context.Context, arg CreateResearchSourceParams) (ResearchSource, error) {
	row := q.db.QueryRow(ctx, createResearchSource,
		arg.TaskID,
		arg.QueryID,
		arg.SourceType,
		arg.Url,
		arg.Domain,
		arg.Title,
		arg.Content,
		arg.Snippet,
		arg.RelevanceScore,
		arg.Author,
		arg.PublishedAt,
		arg.ContentHash,
	)
	var i ResearchSource
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.QueryID,
		&i.SourceType,
		&i.Url,
		&i.Domain,
		&i.Title,
		&i.Content,
		&i.Snippet,
		&i.RelevanceScore,
		&i.FinalRank,
		&i.Cited,
		&i.Embedding,
		&i.ContentHash,
		&i.Author,
		&i.PublishedAt,
		&i.FetchedAt,
	)
	return i, err
}

const createResearchTask = `-- name: CreateResearchTask :one


INSERT INTO research_tasks (
    user_id,
    workspace_id,
    conversation_id,
    query,
    status
) VALUES (
    $1, $2, $3, $4, 'pending'
) RETURNING id, user_id, workspace_id, conversation_id, query, status, total_sources, cited_sources, word_count, report_content, report_format, duration_ms, llm_tokens_used, search_api_calls, search_cost_usd, quality_score, source_diversity_score, error_message, error_phase, created_at, started_at, completed_at
`

type CreateResearchTaskParams struct {
	UserID         string      `json:"user_id"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	Query          string      `json:"query"`
}

// Research System SQLC Queries
// Generated: 2026-01-19
// ============================================================================
// RESEARCH TASKS
// ============================================================================
func (q *Queries) CreateResearchTask(ctx context.Context, arg CreateResearchTaskParams) (ResearchTask, error) {
	row := q.db.QueryRow(ctx, createResearchTask,
		arg.UserID,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.Query,
	)
	var i ResearchTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Query,
		&i.Status,
		&i.TotalSources,
		&i.CitedSources,
		&i.WordCount,
		&i.ReportContent,
		&i.ReportFormat,
		&i.DurationMs,
		&i.LlmTokensUsed,
		&i.SearchApiCalls,
		&i.SearchCostUsd,
		&i.QualityScore,
		&i.SourceDiversityScore,
		&i.ErrorMessage,
		&i.ErrorPhase,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteResearchReport = `-- name: DeleteResearchReport :exec
DELETE FROM research_reports
WHERE task_id = $1
`

func (q *Queries) DeleteResearchReport(ctx context.Context, taskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteResearchReport, taskID)
	return err
}

const deleteResearchTask = `-- name: DeleteResearchTask :exec
DELETE FROM research_tasks
WHERE id = $1
`

func (q *Queries) DeleteResearchTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteResearchTask, id)
	return err
}

const findSimilarResearchSources = `-- name: FindSimilarResearchSources :many
SELECT id, task_id, title, url,
       1 - (embedding <=> $2::vector) AS similarity
FROM research_sources
WHERE task_id = $1
  AND embedding IS NOT NULL
ORDER BY embedding <=> $2::vector
LIMIT $3
`

type FindSimilarResearchSourcesParams struct {
	TaskID  pgtype.UUID      `json:"task_id"`
	Column2 *pgvector.Vector `json:"column_2"`
	Limit   int32            `json:"limit"`
}

type FindSimilarResearchSourcesRow struct {
	ID         pgtype.UUID `json:"id"`
	TaskID     pgtype.UUID `json:"task_id"`
	Title      string      `json:"title"`
	Url        *string     `json:"url"`
	Similarity int32       `json:"similarity"`
}

func (q *Queries) FindSimilarResearchSources(ctx context.Context, arg FindSimilarResearchSourcesParams) ([]FindSimilarResearchSourcesRow, error) {
	rows, err := q.db.Query(ctx, findSimilarResearchSources, arg.TaskID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSimilarResearchSourcesRow{}
	for rows.Next() {
		var i FindSimilarResearchSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.Url,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResearchQuery = `-- name: GetResearchQuery :one
SELECT id, task_id, question, search_type, weight, order_num, depends_on, results_count, completed, duration_ms, error_message, created_at, completed_at FROM research_queries
WHERE id = $1
`

func (q *Queries) GetResearchQuery(ctx context.Context, id pgtype.UUID) (ResearchQuery, error) {
	row := q.db.QueryRow(ctx, getResearchQuery, id)
	var i ResearchQuery
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Question,
		&i.SearchType,
		&i.Weight,
		&i.OrderNum,
		&i.DependsOn,
		&i.ResultsCount,
		&i.Completed,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getResearchQueryDependencies = `-- name: GetResearchQueryDependencies :many
SELECT id, task_id, question, search_type, weight, order_num, depends_on, results_count, completed, duration_ms, error_message, created_at, completed_at FROM research_queries
WHERE task_id = $1
  AND id = ANY($2::uuid[])
`

type GetResearchQueryDependenciesParams struct {
	TaskID  pgtype.UUID   `json:"task_id"`
	Column2 []pgtype.UUID `json:"column_2"`
}

func (q *Queries) GetResearchQueryDependencies(ctx context.Context, arg GetResearchQueryDependenciesParams) ([]ResearchQuery, error) {
	rows, err := q.db.Query(ctx, getResearchQueryDependencies, arg.TaskID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResearchQuery{}
	for rows.Next() {
		var i ResearchQuery
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Question,
			&i.SearchType,
			&i.Weight,
			&i.OrderNum,
			&i.DependsOn,
			&i.ResultsCount,
			&i.Completed,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResearchReport = `-- name: GetResearchReport :one
SELECT id, task_id, content, format, citations, sections, word_count, citation_count, section_count, quality_score, created_at, updated_at FROM research_reports
WHERE id = $1
`

func (q *Queries) GetResearchReport(ctx context.Context, id pgtype.UUID) (ResearchReport, error) {
	row := q.db.QueryRow(ctx, getResearchReport, id)
	var i ResearchReport
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Format,
		&i.Citations,
		&i.Sections,
		&i.WordCount,
		&i.CitationCount,
		&i.SectionCount,
		&i.QualityScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResearchReportByTask = `-- name: GetResearchReportByTask :one
SELECT id, task_id, content, format, citations, sections, word_count, citation_count, section_count, quality_score, created_at, updated_at FROM research_reports
WHERE task_id = $1
`

func (q *Queries) GetResearchReportByTask(ctx context.Context, taskID pgtype.UUID) (ResearchReport, error) {
	row := q.db.QueryRow(ctx, getResearchReportByTask, taskID)
	var i ResearchReport
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Format,
		&i.Citations,
		&i.Sections,
		&i.WordCount,
		&i.CitationCount,
		&i.SectionCount,
		&i.QualityScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResearchSource = `-- name: GetResearchSource :one
SELECT id, task_id, query_id, source_type, url, domain, title, content, snippet, relevance_score, final_rank, cited, embedding, content_hash, author, published_at, fetched_at FROM research_sources
WHERE id = $1
`

func (q *Queries) GetResearchSource(ctx context.Context, id pgtype.UUID) (ResearchSource, error) {
	row := q.db.QueryRow(ctx, getResearchSource, id)
	var i ResearchSource
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.QueryID,
		&i.SourceType,
		&i.Url,
		&i.Domain,
		&i.Title,
		&i.Content,
		&i.Snippet,
		&i.RelevanceScore,
		&i.FinalRank,
		&i.Cited,
		&i.Embedding,
		&i.ContentHash,
		&i.Author,
		&i.PublishedAt,
		&i.FetchedAt,
	)
	return i, err
}

const getResearchTask = `-- name: GetResearchTask :one
SELECT id, user_id, workspace_id, conversation_id, query, status, total_sources, cited_sources, word_count, report_content, report_format, duration_ms, llm_tokens_used, search_api_calls, search_cost_usd, quality_score, source_diversity_score, error_message, error_phase, created_at, started_at, completed_at FROM research_tasks
WHERE id = $1
`

func (q *Queries) GetResearchTask(ctx context.Context, id pgtype.UUID) (ResearchTask, error) {
	row := q.db.QueryRow(ctx, getResearchTask, id)
	var i ResearchTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Query,
		&i.Status,
		&i.TotalSources,
		&i.CitedSources,
		&i.WordCount,
		&i.ReportContent,
		&i.ReportFormat,
		&i.DurationMs,
		&i.LlmTokensUsed,
		&i.SearchApiCalls,
		&i.SearchCostUsd,
		&i.QualityScore,
		&i.SourceDiversityScore,
		&i.ErrorMessage,
		&i.ErrorPhase,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getResearchTaskPerformance = `-- name: GetResearchTaskPerformance :many
SELECT
    DATE_TRUNC('day', created_at) AS day,
    COUNT(*) AS tasks_count,
    AVG(duration_ms) AS avg_duration_ms,
    AVG(quality_score) AS avg_quality,
    SUM(search_cost_usd) AS total_cost
FROM research_tasks
WHERE workspace_id = $1
  AND created_at > $2
  AND status = 'completed'
GROUP BY DATE_TRUNC('day', created_at)
ORDER BY day DESC
`

type GetResearchTaskPerformanceParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type GetResearchTaskPerformanceRow struct {
	Day           pgtype.Interval `json:"day"`
	TasksCount    int64           `json:"tasks_count"`
	AvgDurationMs float64         `json:"avg_duration_ms"`
	AvgQuality    float64         `json:"avg_quality"`
	TotalCost     int64           `json:"total_cost"`
}

func (q *Queries) GetResearchTaskPerformance(ctx context.Context, arg GetResearchTaskPerformanceParams) ([]GetResearchTaskPerformanceRow, error) {
	rows, err := q.db.Query(ctx, getResearchTaskPerformance, arg.WorkspaceID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetResearchTaskPerformanceRow{}
	for rows.Next() {
		var i GetResearchTaskPerformanceRow
		if err := rows.Scan(
			&i.Day,
			&i.TasksCount,
			&i.AvgDurationMs,
			&i.AvgQuality,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResearchTaskStats = `-- name: GetResearchTaskStats :one

SELECT
    COUNT(*) AS total_tasks,
    COUNT(*) FILTER (WHERE status = 'completed') AS completed_tasks,
    COUNT(*) FILTER (WHERE status = 'failed') AS failed_tasks,
    AVG(duration_ms) FILTER (WHERE status = 'completed') AS avg_duration_ms,
    AVG(quality_score) FILTER (WHERE status = 'completed') AS avg_quality_score,
    SUM(llm_tokens_used) AS total_llm_tokens,
    SUM(search_cost_usd) AS total_search_cost
FROM research_tasks
WHERE user_id = $1
  AND created_at > $2
`

type GetResearchTaskStatsParams struct {
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GetResearchTaskStatsRow struct {
	TotalTasks      int64   `json:"total_tasks"`
	CompletedTasks  int64   `json:"completed_tasks"`
	FailedTasks     int64   `json:"failed_tasks"`
	AvgDurationMs   float64 `json:"avg_duration_ms"`
	AvgQualityScore float64 `json:"avg_quality_score"`
	TotalLlmTokens  int64   `json:"total_llm_tokens"`
	TotalSearchCost int64   `json:"total_search_cost"`
}

// ============================================================================
// ANALYTICS & METRICS
// ============================================================================
func (q *Queries) GetResearchTaskStats(ctx context.Context, arg GetResearchTaskStatsParams) (GetResearchTaskStatsRow, error) {
	row := q.db.QueryRow(ctx, getResearchTaskStats, arg.UserID, arg.CreatedAt)
	var i GetResearchTaskStatsRow
	err := row.Scan(
		&i.TotalTasks,
		&i.CompletedTasks,
		&i.FailedTasks,
		&i.AvgDurationMs,
		&i.AvgQualityScore,
		&i.TotalLlmTokens,
		&i.TotalSearchCost,
	)
	return i, err
}

const getSourceDiversityCount = `-- name: GetSourceDiversityCount :one
SELECT COUNT(DISTINCT domain) AS unique_domains
FROM research_sources
WHERE task_id = $1
  AND cited = TRUE
`

func (q *Queries) GetSourceDiversityCount(ctx context.Context, taskID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getSourceDiversityCount, taskID)
	var unique_domains int64
	err := row.Scan(&unique_domains)
	return unique_domains, err
}

const listCitedResearchSources = `-- name: ListCitedResearchSources :many
SELECT id, task_id, query_id, source_type, url, domain, title, content, snippet, relevance_score, final_rank, cited, embedding, content_hash, author, published_at, fetched_at FROM research_sources
WHERE task_id = $1
  AND cited = TRUE
ORDER BY final_rank ASC
`

func (q *Queries) ListCitedResearchSources(ctx context.Context, taskID pgtype.UUID) ([]ResearchSource, error) {
	rows, err := q.db.Query(ctx, listCitedResearchSources, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResearchSource{}
	for rows.Next() {
		var i ResearchSource
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.QueryID,
			&i.SourceType,
			&i.Url,
			&i.Domain,
			&i.Title,
			&i.Content,
			&i.Snippet,
			&i.RelevanceScore,
			&i.FinalRank,
			&i.Cited,
			&i.Embedding,
			&i.ContentHash,
			&i.Author,
			&i.PublishedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingResearchQueries = `-- name: ListPendingResearchQueries :many
SELECT id, task_id, question, search_type, weight, order_num, depends_on, results_count, completed, duration_ms, error_message, created_at, completed_at FROM research_queries
WHERE task_id = $1
  AND completed = FALSE
ORDER BY order_num ASC
`

func (q *Queries) ListPendingResearchQueries(ctx context.Context, taskID pgtype.UUID) ([]ResearchQuery, error) {
	rows, err := q.db.Query(ctx, listPendingResearchQueries, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResearchQuery{}
	for rows.Next() {
		var i ResearchQuery
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Question,
			&i.SearchType,
			&i.Weight,
			&i.OrderNum,
			&i.DependsOn,
			&i.ResultsCount,
			&i.Completed,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentResearchReports = `-- name: ListRecentResearchReports :many
SELECT r.id, r.task_id, r.content, r.format, r.citations, r.sections, r.word_count, r.citation_count, r.section_count, r.quality_score, r.created_at, r.updated_at, t.query, t.user_id, t.workspace_id
FROM research_reports r
JOIN research_tasks t ON r.task_id = t.id
WHERE t.user_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListRecentResearchReportsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListRecentResearchReportsRow struct {
	ID            pgtype.UUID        `json:"id"`
	TaskID        pgtype.UUID        `json:"task_id"`
	Content       string             `json:"content"`
	Format        string             `json:"format"`
	Citations     []byte             `json:"citations"`
	Sections      []byte             `json:"sections"`
	WordCount     *int32             `json:"word_count"`
	CitationCount *int32             `json:"citation_count"`
	SectionCount  *int32             `json:"section_count"`
	QualityScore  pgtype.Numeric     `json:"quality_score"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Query         string             `json:"query"`
	UserID        string             `json:"user_id"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
}

func (q *Queries) ListRecentResearchReports(ctx context.Context, arg ListRecentResearchReportsParams) ([]ListRecentResearchReportsRow, error) {
	rows, err := q.db.Query(ctx, listRecentResearchReports, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentResearchReportsRow{}
	for rows.Next() {
		var i ListRecentResearchReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Content,
			&i.Format,
			&i.Citations,
			&i.Sections,
			&i.WordCount,
			&i.CitationCount,
			&i.SectionCount,
			&i.QualityScore,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Query,
			&i.UserID,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResearchQueriesByTask = `-- name: ListResearchQueriesByTask :many
SELECT id, task_id, question, search_type, weight, order_num, depends_on, results_count, completed, duration_ms, error_message, created_at, completed_at FROM research_queries
WHERE task_id = $1
ORDER BY order_num ASC
`

func (q *Queries) ListResearchQueriesByTask(ctx context.Context, taskID pgtype.UUID) ([]ResearchQuery, error) {
	rows, err := q.db.Query(ctx, listResearchQueriesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResearchQuery{}
	for rows.Next() {
		var i ResearchQuery
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Question,
			&i.SearchType,
			&i.Weight,
			&i.OrderNum,
			&i.DependsOn,
			&i.ResultsCount,
			&i.Completed,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResearchSourcesByQuery = `-- name: ListResearchSourcesByQuery :many
SELECT id, task_id, query_id, source_type, url, domain, title, content, snippet, relevance_score, final_rank, cited, embedding, content_hash, author, published_at, fetched_at FROM research_sources
WHERE query_id = $1
ORDER BY relevance_score DESC
`

func (q *Queries) ListResearchSourcesByQuery(ctx context.Context, queryID pgtype.UUID) ([]ResearchSource, error) {
	rows, err := q.db.Query(ctx, listResearchSourcesByQuery, queryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResearchSource{}
	for rows.Next() {
		var i ResearchSource
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.QueryID,
			&i.SourceType,
			&i.Url,
			&i.Domain,
			&i.Title,
			&i.Content,
			&i.Snippet,
			&i.RelevanceScore,
			&i.FinalRank,
			&i.Cited,
			&i.Embedding,
			&i.ContentHash,
			&i.Author,
			&i.PublishedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResearchSourcesByTask = `-- name: ListResearchSourcesByTask :many
SELECT id, task_id, query_id, source_type, url, domain, title, content, snippet, relevance_score, final_rank, cited, embedding, content_hash, author, published_at, fetched_at FROM research_sources
WHERE task_id = $1
ORDER BY relevance_score DESC
`

func (q *Queries) ListResearchSourcesByTask(ctx context.Context, taskID pgtype.UUID) ([]ResearchSource, error) {
	rows, err := q.db.Query(ctx, listResearchSourcesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResearchSource{}
	for rows.Next() {
		var i ResearchSource
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.QueryID,
			&i.SourceType,
			&i.Url,
			&i.Domain,
			&i.Title,
			&i.Content,
			&i.Snippet,
			&i.RelevanceScore,
			&i.FinalRank,
			&i.Cited,
			&i.Embedding,
			&i.ContentHash,
			&i.Author,
			&i.PublishedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResearchTasksByConversation = `-- name: ListResearchTasksByConversation :many
SELECT id, user_id, workspace_id, conversation_id, query, status, total_sources, cited_sources, word_count, report_content, report_format, duration_ms, llm_tokens_used, search_api_calls, search_cost_usd, quality_score, source_diversity_score, error_message, error_phase, created_at, started_at, completed_at FROM research_tasks
WHERE conversation_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListResearchTasksByConversation(ctx context.Context, conversationID pgtype.UUID) ([]ResearchTask, error) {
	rows, err := q.db.Query(ctx, listResearchTasksByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResearchTask{}
	for rows.Next() {
		var i ResearchTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.Query,
			&i.Status,
			&i.TotalSources,
			&i.CitedSources,
			&i.WordCount,
			&i.ReportContent,
			&i.ReportFormat,
			&i.DurationMs,
			&i.LlmTokensUsed,
			&i.SearchApiCalls,
			&i.SearchCostUsd,
			&i.QualityScore,
			&i.SourceDiversityScore,
			&i.ErrorMessage,
			&i.ErrorPhase,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResearchTasksByUser = `-- name: ListResearchTasksByUser :many
SELECT id, user_id, workspace_id, conversation_id, query, status, total_sources, cited_sources, word_count, report_content, report_format, duration_ms, llm_tokens_used, search_api_calls, search_cost_usd, quality_score, source_diversity_score, error_message, error_phase, created_at, started_at, completed_at FROM research_tasks
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListResearchTasksByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListResearchTasksByUser(ctx context.Context, arg ListResearchTasksByUserParams) ([]ResearchTask, error) {
	rows, err := q.db.Query(ctx, listResearchTasksByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResearchTask{}
	for rows.Next() {
		var i ResearchTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.Query,
			&i.Status,
			&i.TotalSources,
			&i.CitedSources,
			&i.WordCount,
			&i.ReportContent,
			&i.ReportFormat,
			&i.DurationMs,
			&i.LlmTokensUsed,
			&i.SearchApiCalls,
			&i.SearchCostUsd,
			&i.QualityScore,
			&i.SourceDiversityScore,
			&i.ErrorMessage,
			&i.ErrorPhase,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResearchTasksByWorkspace = `-- name: ListResearchTasksByWorkspace :many
SELECT id, user_id, workspace_id, conversation_id, query, status, total_sources, cited_sources, word_count, report_content, report_format, duration_ms, llm_tokens_used, search_api_calls, search_cost_usd, quality_score, source_diversity_score, error_message, error_phase, created_at, started_at, completed_at FROM research_tasks
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListResearchTasksByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListResearchTasksByWorkspace(ctx context.Context, arg ListResearchTasksByWorkspaceParams) ([]ResearchTask, error) {
	rows, err := q.db.Query(ctx, listResearchTasksByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResearchTask{}
	for rows.Next() {
		var i ResearchTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.Query,
			&i.Status,
			&i.TotalSources,
			&i.CitedSources,
			&i.WordCount,
			&i.ReportContent,
			&i.ReportFormat,
			&i.DurationMs,
			&i.LlmTokensUsed,
			&i.SearchApiCalls,
			&i.SearchCostUsd,
			&i.QualityScore,
			&i.SourceDiversityScore,
			&i.ErrorMessage,
			&i.ErrorPhase,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopResearchSources = `-- name: ListTopResearchSources :many
SELECT id, task_id, query_id, source_type, url, domain, title, content, snippet, relevance_score, final_rank, cited, embedding, content_hash, author, published_at, fetched_at FROM research_sources
WHERE task_id = $1
  AND final_rank IS NOT NULL
ORDER BY final_rank ASC
LIMIT $2
`

type ListTopResearchSourcesParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListTopResearchSources(ctx context.Context, arg ListTopResearchSourcesParams) ([]ResearchSource, error) {
	rows, err := q.db.Query(ctx, listTopResearchSources, arg.TaskID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResearchSource{}
	for rows.Next() {
		var i ResearchSource
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.QueryID,
			&i.SourceType,
			&i.Url,
			&i.Domain,
			&i.Title,
			&i.Content,
			&i.Snippet,
			&i.RelevanceScore,
			&i.FinalRank,
			&i.Cited,
			&i.Embedding,
			&i.ContentHash,
			&i.Author,
			&i.PublishedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markResearchQueryCompleted = `-- name: MarkResearchQueryCompleted :exec
UPDATE research_queries
SET completed = TRUE,
    results_count = $2,
    duration_ms = $3,
    completed_at = NOW()
WHERE id = $1
`

type MarkResearchQueryCompletedParams struct {
	ID           pgtype.UUID `json:"id"`
	ResultsCount *int32      `json:"results_count"`
	DurationMs   *int32      `json:"duration_ms"`
}

func (q *Queries) MarkResearchQueryCompleted(ctx context.Context, arg MarkResearchQueryCompletedParams) error {
	_, err := q.db.Exec(ctx, markResearchQueryCompleted, arg.ID, arg.ResultsCount, arg.DurationMs)
	return err
}

const markResearchQueryFailed = `-- name: MarkResearchQueryFailed :exec
UPDATE research_queries
SET completed = FALSE,
    error_message = $2
WHERE id = $1
`

type MarkResearchQueryFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) MarkResearchQueryFailed(ctx context.Context, arg MarkResearchQueryFailedParams) error {
	_, err := q.db.Exec(ctx, markResearchQueryFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markResearchSourceCited = `-- name: MarkResearchSourceCited :exec
UPDATE research_sources
SET cited = TRUE
WHERE id = $1
`

func (q *Queries) MarkResearchSourceCited(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markResearchSourceCited, id)
	return err
}

const setResearchTaskReport = `-- name: SetResearchTaskReport :exec
UPDATE research_tasks
SET report_content = $2,
    report_format = $3,
    status = 'completed',
    completed_at = NOW()
WHERE id = $1
`

type SetResearchTaskReportParams struct {
	ID            pgtype.UUID `json:"id"`
	ReportContent *string     `json:"report_content"`
	ReportFormat  *string     `json:"report_format"`
}

func (q *Queries) SetResearchTaskReport(ctx context.Context, arg SetResearchTaskReportParams) error {
	_, err := q.db.Exec(ctx, setResearchTaskReport, arg.ID, arg.ReportContent, arg.ReportFormat)
	return err
}

const updateResearchReport = `-- name: UpdateResearchReport :exec
UPDATE research_reports
SET content = $2,
    format = $3,
    citations = $4,
    sections = $5,
    word_count = $6,
    citation_count = $7,
    section_count = $8,
    quality_score = $9,
    updated_at = NOW()
WHERE task_id = $1
`

type UpdateResearchReportParams struct {
	TaskID        pgtype.UUID    `json:"task_id"`
	Content       string         `json:"content"`
	Format        string         `json:"format"`
	Citations     []byte         `json:"citations"`
	Sections      []byte         `json:"sections"`
	WordCount     *int32         `json:"word_count"`
	CitationCount *int32         `json:"citation_count"`
	SectionCount  *int32         `json:"section_count"`
	QualityScore  pgtype.Numeric `json:"quality_score"`
}

func (q *Queries) UpdateResearchReport(ctx context.Context, arg UpdateResearchReportParams) error {
	_, err := q.db.Exec(ctx, updateResearchReport,
		arg.TaskID,
		arg.Content,
		arg.Format,
		arg.Citations,
		arg.Sections,
		arg.WordCount,
		arg.CitationCount,
		arg.SectionCount,
		arg.QualityScore,
	)
	return err
}

const updateResearchSourceEmbedding = `-- name: UpdateResearchSourceEmbedding :exec
UPDATE research_sources
SET embedding = $2::vector
WHERE id = $1
`

type UpdateResearchSourceEmbeddingParams struct {
	ID      pgtype.UUID      `json:"id"`
	Column2 *pgvector.Vector `json:"column_2"`
}

func (q *Queries) UpdateResearchSourceEmbedding(ctx context.Context, arg UpdateResearchSourceEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateResearchSourceEmbedding, arg.ID, arg.Column2)
	return err
}

const updateResearchSourceRank = `-- name: UpdateResearchSourceRank :exec
UPDATE research_sources
SET final_rank = $2
WHERE id = $1
`

type UpdateResearchSourceRankParams struct {
	ID        pgtype.UUID `json:"id"`
	FinalRank *int32      `json:"final_rank"`
}

func (q *Queries) UpdateResearchSourceRank(ctx context.Context, arg UpdateResearchSourceRankParams) error {
	_, err := q.db.Exec(ctx, updateResearchSourceRank, arg.ID, arg.FinalRank)
	return err
}

const updateResearchTaskError = `-- name: UpdateResearchTaskError :exec
UPDATE research_tasks
SET status = 'failed',
    error_message = $2,
    error_phase = $3,
    completed_at = NOW()
WHERE id = $1
`

type UpdateResearchTaskErrorParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
	ErrorPhase   *string     `json:"error_phase"`
}

func (q *Queries) UpdateResearchTaskError(ctx context.Context, arg UpdateResearchTaskErrorParams) error {
	_, err := q.db.Exec(ctx, updateResearchTaskError, arg.ID, arg.ErrorMessage, arg.ErrorPhase)
	return err
}

const updateResearchTaskMetrics = `-- name: UpdateResearchTaskMetrics :exec
UPDATE research_tasks
SET duration_ms = $2,
    llm_tokens_used = $3,
    search_api_calls = $4,
    search_cost_usd = $5,
    total_sources = $6,
    cited_sources = $7,
    word_count = $8,
    quality_score = $9,
    source_diversity_score = $10
WHERE id = $1
`

type UpdateResearchTaskMetricsParams struct {
	ID                   pgtype.UUID    `json:"id"`
	DurationMs           *int32         `json:"duration_ms"`
	LlmTokensUsed        *int32         `json:"llm_tokens_used"`
	SearchApiCalls       *int32         `json:"search_api_calls"`
	SearchCostUsd        pgtype.Numeric `json:"search_cost_usd"`
	TotalSources         *int32         `json:"total_sources"`
	CitedSources         *int32         `json:"cited_sources"`
	WordCount            *int32         `json:"word_count"`
	QualityScore         pgtype.Numeric `json:"quality_score"`
	SourceDiversityScore *int32         `json:"source_diversity_score"`
}

func (q *Queries) UpdateResearchTaskMetrics(ctx context.Context, arg UpdateResearchTaskMetricsParams) error {
	_, err := q.db.Exec(ctx, updateResearchTaskMetrics,
		arg.ID,
		arg.DurationMs,
		arg.LlmTokensUsed,
		arg.SearchApiCalls,
		arg.SearchCostUsd,
		arg.TotalSources,
		arg.CitedSources,
		arg.WordCount,
		arg.QualityScore,
		arg.SourceDiversityScore,
	)
	return err
}

const updateResearchTaskStatus = `-- name: UpdateResearchTaskStatus :exec
UPDATE research_tasks
SET status = $2,
    started_at = CASE WHEN $2 = 'planning' AND started_at IS NULL THEN NOW() ELSE started_at END,
    completed_at = CASE WHEN $2 IN ('completed', 'failed') THEN NOW() ELSE completed_at END
WHERE id = $1
`

type UpdateResearchTaskStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateResearchTaskStatus(ctx context.Context, arg UpdateResearchTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateResearchTaskStatus, arg.ID, arg.Status)
	return err
}
