// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_external_apps.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserExternalApp = `-- name: CreateUserExternalApp :one
INSERT INTO user_external_apps (
    user_id,
    workspace_id,
    name,
    url,
    icon,
    color,
    logo_url,
    category,
    description,
    iframe_config,
    open_on_startup,
    app_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING
    id,
    user_id,
    workspace_id,
    name,
    url,
    icon,
    color,
    logo_url,
    category,
    description,
    position_x,
    position_y,
    position_z,
    iframe_config,
    is_active,
    open_on_startup,
    app_type,
    created_at,
    updated_at,
    last_opened_at
`

type CreateUserExternalAppParams struct {
	UserID        string      `json:"user_id"`
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	Name          string      `json:"name"`
	Url           string      `json:"url"`
	Icon          string      `json:"icon"`
	Color         string      `json:"color"`
	LogoUrl       *string     `json:"logo_url"`
	Category      *string     `json:"category"`
	Description   *string     `json:"description"`
	IframeConfig  []byte      `json:"iframe_config"`
	OpenOnStartup *bool       `json:"open_on_startup"`
	AppType       string      `json:"app_type"`
}

// Create a new external app
func (q *Queries) CreateUserExternalApp(ctx context.Context, arg CreateUserExternalAppParams) (UserExternalApp, error) {
	row := q.db.QueryRow(ctx, createUserExternalApp,
		arg.UserID,
		arg.WorkspaceID,
		arg.Name,
		arg.Url,
		arg.Icon,
		arg.Color,
		arg.LogoUrl,
		arg.Category,
		arg.Description,
		arg.IframeConfig,
		arg.OpenOnStartup,
		arg.AppType,
	)
	var i UserExternalApp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Name,
		&i.Url,
		&i.Icon,
		&i.Color,
		&i.LogoUrl,
		&i.Category,
		&i.Description,
		&i.PositionX,
		&i.PositionY,
		&i.PositionZ,
		&i.IframeConfig,
		&i.IsActive,
		&i.OpenOnStartup,
		&i.AppType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOpenedAt,
	)
	return i, err
}

const deleteUserExternalApp = `-- name: DeleteUserExternalApp :exec
DELETE FROM user_external_apps
WHERE id = $1 AND workspace_id = $2
`

type DeleteUserExternalAppParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

// Delete an external app
func (q *Queries) DeleteUserExternalApp(ctx context.Context, arg DeleteUserExternalAppParams) error {
	_, err := q.db.Exec(ctx, deleteUserExternalApp, arg.ID, arg.WorkspaceID)
	return err
}

const getStartupApps = `-- name: GetStartupApps :many
SELECT
    id,
    user_id,
    workspace_id,
    name,
    url,
    icon,
    color,
    logo_url,
    category,
    description,
    position_x,
    position_y,
    position_z,
    iframe_config,
    is_active,
    open_on_startup,
    app_type,
    created_at,
    updated_at,
    last_opened_at
FROM user_external_apps
WHERE workspace_id = $1
  AND is_active = true
  AND open_on_startup = true
ORDER BY created_at ASC
`

// Get all apps configured to open on startup
func (q *Queries) GetStartupApps(ctx context.Context, workspaceID pgtype.UUID) ([]UserExternalApp, error) {
	rows, err := q.db.Query(ctx, getStartupApps, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserExternalApp{}
	for rows.Next() {
		var i UserExternalApp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Name,
			&i.Url,
			&i.Icon,
			&i.Color,
			&i.LogoUrl,
			&i.Category,
			&i.Description,
			&i.PositionX,
			&i.PositionY,
			&i.PositionZ,
			&i.IframeConfig,
			&i.IsActive,
			&i.OpenOnStartup,
			&i.AppType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastOpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserExternalApp = `-- name: GetUserExternalApp :one
SELECT
    id,
    user_id,
    workspace_id,
    name,
    url,
    icon,
    color,
    logo_url,
    category,
    description,
    position_x,
    position_y,
    position_z,
    iframe_config,
    is_active,
    open_on_startup,
    app_type,
    created_at,
    updated_at,
    last_opened_at
FROM user_external_apps
WHERE id = $1 AND workspace_id = $2
`

type GetUserExternalAppParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

// Get a specific external app by ID
func (q *Queries) GetUserExternalApp(ctx context.Context, arg GetUserExternalAppParams) (UserExternalApp, error) {
	row := q.db.QueryRow(ctx, getUserExternalApp, arg.ID, arg.WorkspaceID)
	var i UserExternalApp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Name,
		&i.Url,
		&i.Icon,
		&i.Color,
		&i.LogoUrl,
		&i.Category,
		&i.Description,
		&i.PositionX,
		&i.PositionY,
		&i.PositionZ,
		&i.IframeConfig,
		&i.IsActive,
		&i.OpenOnStartup,
		&i.AppType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOpenedAt,
	)
	return i, err
}

const listAllUserExternalApps = `-- name: ListAllUserExternalApps :many
SELECT
    id,
    user_id,
    workspace_id,
    name,
    url,
    icon,
    color,
    logo_url,
    category,
    description,
    position_x,
    position_y,
    position_z,
    iframe_config,
    is_active,
    open_on_startup,
    app_type,
    created_at,
    updated_at,
    last_opened_at
FROM user_external_apps
WHERE workspace_id = $1
ORDER BY created_at DESC
`

// Get all external apps for a workspace (including inactive)
func (q *Queries) ListAllUserExternalApps(ctx context.Context, workspaceID pgtype.UUID) ([]UserExternalApp, error) {
	rows, err := q.db.Query(ctx, listAllUserExternalApps, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserExternalApp{}
	for rows.Next() {
		var i UserExternalApp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Name,
			&i.Url,
			&i.Icon,
			&i.Color,
			&i.LogoUrl,
			&i.Category,
			&i.Description,
			&i.PositionX,
			&i.PositionY,
			&i.PositionZ,
			&i.IframeConfig,
			&i.IsActive,
			&i.OpenOnStartup,
			&i.AppType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastOpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserExternalApps = `-- name: ListUserExternalApps :many

SELECT
    id,
    user_id,
    workspace_id,
    name,
    url,
    icon,
    color,
    logo_url,
    category,
    description,
    position_x,
    position_y,
    position_z,
    iframe_config,
    is_active,
    open_on_startup,
    app_type,
    created_at,
    updated_at,
    last_opened_at
FROM user_external_apps
WHERE workspace_id = $1
  AND is_active = true
ORDER BY created_at DESC
`

// User External Apps Queries
// Full CRUD operations for managing user-added web applications
// Get all active external apps for a workspace
func (q *Queries) ListUserExternalApps(ctx context.Context, workspaceID pgtype.UUID) ([]UserExternalApp, error) {
	rows, err := q.db.Query(ctx, listUserExternalApps, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserExternalApp{}
	for rows.Next() {
		var i UserExternalApp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Name,
			&i.Url,
			&i.Icon,
			&i.Color,
			&i.LogoUrl,
			&i.Category,
			&i.Description,
			&i.PositionX,
			&i.PositionY,
			&i.PositionZ,
			&i.IframeConfig,
			&i.IsActive,
			&i.OpenOnStartup,
			&i.AppType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastOpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAppOpened = `-- name: RecordAppOpened :exec
UPDATE user_external_apps
SET last_opened_at = NOW()
WHERE id = $1
`

// Update last_opened_at timestamp when app is accessed
func (q *Queries) RecordAppOpened(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordAppOpened, id)
	return err
}

const toggleAppActive = `-- name: ToggleAppActive :exec
UPDATE user_external_apps
SET
    is_active = $2,
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $3
`

type ToggleAppActiveParams struct {
	ID          pgtype.UUID `json:"id"`
	IsActive    *bool       `json:"is_active"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

// Enable/disable an app without deleting
func (q *Queries) ToggleAppActive(ctx context.Context, arg ToggleAppActiveParams) error {
	_, err := q.db.Exec(ctx, toggleAppActive, arg.ID, arg.IsActive, arg.WorkspaceID)
	return err
}

const updateAppPosition = `-- name: UpdateAppPosition :exec
UPDATE user_external_apps
SET
    position_x = $2,
    position_y = $3,
    position_z = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAppPositionParams struct {
	ID        pgtype.UUID `json:"id"`
	PositionX *int32      `json:"position_x"`
	PositionY *int32      `json:"position_y"`
	PositionZ *int32      `json:"position_z"`
}

// Update app position on 3D desktop (called when user moves window)
func (q *Queries) UpdateAppPosition(ctx context.Context, arg UpdateAppPositionParams) error {
	_, err := q.db.Exec(ctx, updateAppPosition,
		arg.ID,
		arg.PositionX,
		arg.PositionY,
		arg.PositionZ,
	)
	return err
}

const updateUserExternalApp = `-- name: UpdateUserExternalApp :one
UPDATE user_external_apps
SET
    name = COALESCE($3, name),
    url = COALESCE($4, url),
    icon = COALESCE($5, icon),
    color = COALESCE($6, color),
    logo_url = COALESCE($7, logo_url),
    category = COALESCE($8, category),
    description = COALESCE($9, description),
    position_x = COALESCE($10, position_x),
    position_y = COALESCE($11, position_y),
    position_z = COALESCE($12, position_z),
    iframe_config = COALESCE($13, iframe_config),
    is_active = COALESCE($14, is_active),
    open_on_startup = COALESCE($15, open_on_startup),
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING
    id,
    user_id,
    workspace_id,
    name,
    url,
    icon,
    color,
    logo_url,
    category,
    description,
    position_x,
    position_y,
    position_z,
    iframe_config,
    is_active,
    open_on_startup,
    app_type,
    created_at,
    updated_at,
    last_opened_at
`

type UpdateUserExternalAppParams struct {
	ID            pgtype.UUID `json:"id"`
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	Name          *string     `json:"name"`
	Url           *string     `json:"url"`
	Icon          *string     `json:"icon"`
	Color         *string     `json:"color"`
	LogoUrl       *string     `json:"logo_url"`
	Category      *string     `json:"category"`
	Description   *string     `json:"description"`
	PositionX     *int32      `json:"position_x"`
	PositionY     *int32      `json:"position_y"`
	PositionZ     *int32      `json:"position_z"`
	IframeConfig  []byte      `json:"iframe_config"`
	IsActive      *bool       `json:"is_active"`
	OpenOnStartup *bool       `json:"open_on_startup"`
}

// Update an existing external app
func (q *Queries) UpdateUserExternalApp(ctx context.Context, arg UpdateUserExternalAppParams) (UserExternalApp, error) {
	row := q.db.QueryRow(ctx, updateUserExternalApp,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Url,
		arg.Icon,
		arg.Color,
		arg.LogoUrl,
		arg.Category,
		arg.Description,
		arg.PositionX,
		arg.PositionY,
		arg.PositionZ,
		arg.IframeConfig,
		arg.IsActive,
		arg.OpenOnStartup,
	)
	var i UserExternalApp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Name,
		&i.Url,
		&i.Icon,
		&i.Color,
		&i.LogoUrl,
		&i.Category,
		&i.Description,
		&i.PositionX,
		&i.PositionY,
		&i.PositionZ,
		&i.IframeConfig,
		&i.IsActive,
		&i.OpenOnStartup,
		&i.AppType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOpenedAt,
	)
	return i, err
}
