import {
	Download, Star, Package,
	BarChart2, Clock, FileText, MessageSquare, Mail,
	Zap, Settings, Database, Globe, Shield, Bell, Users,
	Calendar, Folder, Search, Image, Code, Terminal,
	Layers, Activity, PieChart, TrendingUp, Send,
	Briefcase, CreditCard, DollarSign, Receipt, Box,
	Cpu, Hash, Link, Lock, Map, Monitor, Phone,
	Printer, Radio, Server, Wifi, Play, Bookmark
} from 'lucide-svelte';

export const moduleIconMap: Record<string, typeof Package> = {
	'bar-chart-2': BarChart2,
	'clock': Clock,
	'file-text': FileText,
	'message-square': MessageSquare,
	'mail': Mail,
	'download': Download,
	'zap': Zap,
	'settings': Settings,
	'database': Database,
	'globe': Globe,
	'shield': Shield,
	'bell': Bell,
	'users': Users,
	'calendar': Calendar,
	'folder': Folder,
	'search': Search,
	'image': Image,
	'code': Code,
	'terminal': Terminal,
	'layers': Layers,
	'activity': Activity,
	'pie-chart': PieChart,
	'trending-up': TrendingUp,
	'send': Send,
	'briefcase': Briefcase,
	'credit-card': CreditCard,
	'dollar-sign': DollarSign,
	'receipt': Receipt,
	'star': Star,
	'package': Package,
	'box': Box,
	'cpu': Cpu,
	'hash': Hash,
	'link': Link,
	'lock': Lock,
	'map': Map,
	'monitor': Monitor,
	'phone': Phone,
	'printer': Printer,
	'radio': Radio,
	'server': Server,
	'wifi': Wifi,
	'play': Play,
	'bookmark': Bookmark,
};

export { Package as FallbackIcon };
