-- Migration 089: App Generation System Tables
-- Creates tables for personalized app generation system with templates and queue

-- ================================================================
-- APP TEMPLATES
-- ================================================================

CREATE TABLE IF NOT EXISTS app_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    template_name VARCHAR(255) UNIQUE NOT NULL,
    category VARCHAR(100) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    description TEXT,
    icon_type VARCHAR(50),
    target_business_types TEXT[] DEFAULT '{}',
    target_challenges TEXT[] DEFAULT '{}',
    target_team_sizes TEXT[] DEFAULT '{}',
    priority_score INTEGER DEFAULT 50,
    template_config JSONB DEFAULT '{}'::jsonb,
    required_modules TEXT[] DEFAULT '{}',
    optional_features TEXT[] DEFAULT '{}',
    generation_prompt TEXT,
    scaffold_type VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_app_templates_category ON app_templates(category);
CREATE INDEX IF NOT EXISTS idx_app_templates_priority ON app_templates(priority_score DESC);
CREATE INDEX IF NOT EXISTS idx_app_templates_business_types ON app_templates USING GIN(target_business_types);
CREATE INDEX IF NOT EXISTS idx_app_templates_challenges ON app_templates USING GIN(target_challenges);
CREATE INDEX IF NOT EXISTS idx_app_templates_team_sizes ON app_templates USING GIN(target_team_sizes);

-- ================================================================
-- USER GENERATED APPS
-- ================================================================

CREATE TABLE IF NOT EXISTS user_generated_apps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    template_id UUID REFERENCES app_templates(id) ON DELETE SET NULL,
    app_name VARCHAR(255) NOT NULL,
    osa_app_id UUID, -- Reference to osa_apps table
    is_visible BOOLEAN DEFAULT true,
    is_pinned BOOLEAN DEFAULT false,
    is_favorite BOOLEAN DEFAULT false,
    position_index INTEGER DEFAULT 0,
    custom_config JSONB DEFAULT '{}'::jsonb,
    custom_icon VARCHAR(255),
    last_accessed_at TIMESTAMPTZ,
    access_count INTEGER DEFAULT 0,
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_generated_apps_workspace ON user_generated_apps(workspace_id);
CREATE INDEX IF NOT EXISTS idx_user_generated_apps_template ON user_generated_apps(template_id);
CREATE INDEX IF NOT EXISTS idx_user_generated_apps_pinned ON user_generated_apps(workspace_id, is_pinned DESC, position_index ASC);
CREATE INDEX IF NOT EXISTS idx_user_generated_apps_visible ON user_generated_apps(workspace_id, is_visible) WHERE is_visible = true;

-- ================================================================
-- APP GENERATION QUEUE
-- ================================================================

CREATE TABLE IF NOT EXISTS app_generation_queue (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    template_id UUID REFERENCES app_templates(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    priority INTEGER DEFAULT 5 CHECK (priority >= 1 AND priority <= 10),
    generation_context JSONB DEFAULT '{}'::jsonb,
    error_message TEXT,
    retry_count INTEGER DEFAULT 0,
    max_retries INTEGER DEFAULT 3,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_app_generation_queue_status ON app_generation_queue(status);
CREATE INDEX IF NOT EXISTS idx_app_generation_queue_workspace ON app_generation_queue(workspace_id);
CREATE INDEX IF NOT EXISTS idx_app_generation_queue_pending ON app_generation_queue(priority DESC, created_at ASC) WHERE status = 'pending';

-- ================================================================
-- COMMENTS
-- ================================================================

COMMENT ON TABLE app_templates IS 'Predefined templates for app generation (SaaS, CRM, etc.)';
COMMENT ON TABLE user_generated_apps IS 'Apps generated by users from templates';
COMMENT ON TABLE app_generation_queue IS 'Queue for async app generation processing';

COMMENT ON COLUMN app_templates.priority_score IS 'Higher score = shown first in recommendations';
COMMENT ON COLUMN app_templates.target_business_types IS 'Array of business types this template suits (e.g., saas, startup)';
COMMENT ON COLUMN app_templates.target_challenges IS 'Array of challenges this template solves';
COMMENT ON COLUMN app_templates.target_team_sizes IS 'Array of team sizes (solo, small, medium, large)';

COMMENT ON COLUMN app_generation_queue.priority IS '1-10, higher = processed first';
COMMENT ON COLUMN app_generation_queue.generation_context IS 'JSON with app_name, description, config';
