// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendarEvent = `-- name: CreateCalendarEvent :one
INSERT INTO calendar_events (
    user_id, google_event_id, calendar_id, title, description,
    start_time, end_time, all_day, location, attendees,
    status, visibility, html_link, source,
    meeting_type, context_id, project_id, client_id,
    recording_url, meeting_link, external_links,
    meeting_notes, action_items
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20, $21, $22, $23
) RETURNING id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at
`

type CreateCalendarEventParams struct {
	UserID        string             `json:"user_id"`
	GoogleEventID *string            `json:"google_event_id"`
	CalendarID    *string            `json:"calendar_id"`
	Title         *string            `json:"title"`
	Description   *string            `json:"description"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
	AllDay        *bool              `json:"all_day"`
	Location      *string            `json:"location"`
	Attendees     []byte             `json:"attendees"`
	Status        *string            `json:"status"`
	Visibility    *string            `json:"visibility"`
	HtmlLink      *string            `json:"html_link"`
	Source        *string            `json:"source"`
	MeetingType   NullMeetingtype    `json:"meeting_type"`
	ContextID     pgtype.UUID        `json:"context_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ClientID      pgtype.UUID        `json:"client_id"`
	RecordingUrl  *string            `json:"recording_url"`
	MeetingLink   *string            `json:"meeting_link"`
	ExternalLinks []byte             `json:"external_links"`
	MeetingNotes  *string            `json:"meeting_notes"`
	ActionItems   []byte             `json:"action_items"`
}

func (q *Queries) CreateCalendarEvent(ctx context.Context, arg CreateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, createCalendarEvent,
		arg.UserID,
		arg.GoogleEventID,
		arg.CalendarID,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.Location,
		arg.Attendees,
		arg.Status,
		arg.Visibility,
		arg.HtmlLink,
		arg.Source,
		arg.MeetingType,
		arg.ContextID,
		arg.ProjectID,
		arg.ClientID,
		arg.RecordingUrl,
		arg.MeetingLink,
		arg.ExternalLinks,
		arg.MeetingNotes,
		arg.ActionItems,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoogleEventID,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.Attendees,
		&i.Status,
		&i.Visibility,
		&i.HtmlLink,
		&i.Source,
		&i.MeetingType,
		&i.ContextID,
		&i.ProjectID,
		&i.ClientID,
		&i.RecordingUrl,
		&i.MeetingLink,
		&i.ExternalLinks,
		&i.MeetingNotes,
		&i.ActionItems,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCalendarEvent = `-- name: DeleteCalendarEvent :exec
DELETE FROM calendar_events
WHERE id = $1 AND user_id = $2
`

type DeleteCalendarEventParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteCalendarEvent(ctx context.Context, arg DeleteCalendarEventParams) error {
	_, err := q.db.Exec(ctx, deleteCalendarEvent, arg.ID, arg.UserID)
	return err
}

const deleteCalendarEventByGoogleId = `-- name: DeleteCalendarEventByGoogleId :exec
DELETE FROM calendar_events
WHERE google_event_id = $1 AND user_id = $2
`

type DeleteCalendarEventByGoogleIdParams struct {
	GoogleEventID *string `json:"google_event_id"`
	UserID        string  `json:"user_id"`
}

func (q *Queries) DeleteCalendarEventByGoogleId(ctx context.Context, arg DeleteCalendarEventByGoogleIdParams) error {
	_, err := q.db.Exec(ctx, deleteCalendarEventByGoogleId, arg.GoogleEventID, arg.UserID)
	return err
}

const deleteCalendarEventsForUser = `-- name: DeleteCalendarEventsForUser :exec
DELETE FROM calendar_events
WHERE user_id = $1
`

func (q *Queries) DeleteCalendarEventsForUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteCalendarEventsForUser, userID)
	return err
}

const getCalendarEvent = `-- name: GetCalendarEvent :one
SELECT id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at FROM calendar_events
WHERE id = $1 AND user_id = $2
`

type GetCalendarEventParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetCalendarEvent(ctx context.Context, arg GetCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, getCalendarEvent, arg.ID, arg.UserID)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoogleEventID,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.Attendees,
		&i.Status,
		&i.Visibility,
		&i.HtmlLink,
		&i.Source,
		&i.MeetingType,
		&i.ContextID,
		&i.ProjectID,
		&i.ClientID,
		&i.RecordingUrl,
		&i.MeetingLink,
		&i.ExternalLinks,
		&i.MeetingNotes,
		&i.ActionItems,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCalendarEventByGoogleId = `-- name: GetCalendarEventByGoogleId :one
SELECT id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at FROM calendar_events
WHERE google_event_id = $1 AND user_id = $2
`

type GetCalendarEventByGoogleIdParams struct {
	GoogleEventID *string `json:"google_event_id"`
	UserID        string  `json:"user_id"`
}

func (q *Queries) GetCalendarEventByGoogleId(ctx context.Context, arg GetCalendarEventByGoogleIdParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, getCalendarEventByGoogleId, arg.GoogleEventID, arg.UserID)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoogleEventID,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.Attendees,
		&i.Status,
		&i.Visibility,
		&i.HtmlLink,
		&i.Source,
		&i.MeetingType,
		&i.ContextID,
		&i.ProjectID,
		&i.ClientID,
		&i.RecordingUrl,
		&i.MeetingLink,
		&i.ExternalLinks,
		&i.MeetingNotes,
		&i.ActionItems,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCalendarStats = `-- name: GetCalendarStats :one
SELECT
    COUNT(*) as total_events,
    COUNT(CASE WHEN source = 'google' THEN 1 END) as google_events,
    COUNT(CASE WHEN source = 'local' OR source IS NULL THEN 1 END) as local_events,
    MIN(start_time) as date_range_from,
    MAX(end_time) as date_range_to,
    MAX(synced_at) as last_sync
FROM calendar_events
WHERE user_id = $1
`

type GetCalendarStatsRow struct {
	TotalEvents   int64       `json:"total_events"`
	GoogleEvents  int64       `json:"google_events"`
	LocalEvents   int64       `json:"local_events"`
	DateRangeFrom interface{} `json:"date_range_from"`
	DateRangeTo   interface{} `json:"date_range_to"`
	LastSync      interface{} `json:"last_sync"`
}

func (q *Queries) GetCalendarStats(ctx context.Context, userID string) (GetCalendarStatsRow, error) {
	row := q.db.QueryRow(ctx, getCalendarStats, userID)
	var i GetCalendarStatsRow
	err := row.Scan(
		&i.TotalEvents,
		&i.GoogleEvents,
		&i.LocalEvents,
		&i.DateRangeFrom,
		&i.DateRangeTo,
		&i.LastSync,
	)
	return i, err
}

const getEventsForClient = `-- name: GetEventsForClient :many
SELECT id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at FROM calendar_events
WHERE client_id = $1
ORDER BY start_time DESC
`

func (q *Queries) GetEventsForClient(ctx context.Context, clientID pgtype.UUID) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, getEventsForClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoogleEventID,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.Location,
			&i.Attendees,
			&i.Status,
			&i.Visibility,
			&i.HtmlLink,
			&i.Source,
			&i.MeetingType,
			&i.ContextID,
			&i.ProjectID,
			&i.ClientID,
			&i.RecordingUrl,
			&i.MeetingLink,
			&i.ExternalLinks,
			&i.MeetingNotes,
			&i.ActionItems,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsForContext = `-- name: GetEventsForContext :many
SELECT id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at FROM calendar_events
WHERE context_id = $1
ORDER BY start_time DESC
`

func (q *Queries) GetEventsForContext(ctx context.Context, contextID pgtype.UUID) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, getEventsForContext, contextID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoogleEventID,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.Location,
			&i.Attendees,
			&i.Status,
			&i.Visibility,
			&i.HtmlLink,
			&i.Source,
			&i.MeetingType,
			&i.ContextID,
			&i.ProjectID,
			&i.ClientID,
			&i.RecordingUrl,
			&i.MeetingLink,
			&i.ExternalLinks,
			&i.MeetingNotes,
			&i.ActionItems,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsForProject = `-- name: GetEventsForProject :many
SELECT id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at FROM calendar_events
WHERE project_id = $1
ORDER BY start_time DESC
`

func (q *Queries) GetEventsForProject(ctx context.Context, projectID pgtype.UUID) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, getEventsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoogleEventID,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.Location,
			&i.Attendees,
			&i.Status,
			&i.Visibility,
			&i.HtmlLink,
			&i.Source,
			&i.MeetingType,
			&i.ContextID,
			&i.ProjectID,
			&i.ClientID,
			&i.RecordingUrl,
			&i.MeetingLink,
			&i.ExternalLinks,
			&i.MeetingNotes,
			&i.ActionItems,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeetingsByType = `-- name: GetMeetingsByType :many
SELECT meeting_type, COUNT(*) as count
FROM calendar_events
WHERE user_id = $1
  AND start_time >= $2
  AND end_time <= $3
GROUP BY meeting_type
ORDER BY count DESC
`

type GetMeetingsByTypeParams struct {
	UserID    string             `json:"user_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type GetMeetingsByTypeRow struct {
	MeetingType NullMeetingtype `json:"meeting_type"`
	Count       int64           `json:"count"`
}

func (q *Queries) GetMeetingsByType(ctx context.Context, arg GetMeetingsByTypeParams) ([]GetMeetingsByTypeRow, error) {
	rows, err := q.db.Query(ctx, getMeetingsByType, arg.UserID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMeetingsByTypeRow{}
	for rows.Next() {
		var i GetMeetingsByTypeRow
		if err := rows.Scan(&i.MeetingType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamAvailability = `-- name: GetTeamAvailability :many
SELECT
    tm.id as member_id,
    tm.name as member_name,
    ce.start_time,
    ce.end_time,
    ce.title
FROM team_members tm
LEFT JOIN calendar_events ce ON tm.calendar_user_id = ce.user_id
    AND ce.start_time >= $2
    AND ce.end_time <= $3
WHERE tm.user_id = $1
  AND tm.share_calendar = TRUE
ORDER BY tm.name, ce.start_time
`

type GetTeamAvailabilityParams struct {
	UserID    string             `json:"user_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type GetTeamAvailabilityRow struct {
	MemberID   pgtype.UUID        `json:"member_id"`
	MemberName string             `json:"member_name"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	Title      *string            `json:"title"`
}

func (q *Queries) GetTeamAvailability(ctx context.Context, arg GetTeamAvailabilityParams) ([]GetTeamAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, getTeamAvailability, arg.UserID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTeamAvailabilityRow{}
	for rows.Next() {
		var i GetTeamAvailabilityRow
		if err := rows.Scan(
			&i.MemberID,
			&i.MemberName,
			&i.StartTime,
			&i.EndTime,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayEvents = `-- name: GetTodayEvents :many
SELECT id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at FROM calendar_events
WHERE user_id = $1
  AND DATE(start_time) = CURRENT_DATE
ORDER BY start_time ASC
`

func (q *Queries) GetTodayEvents(ctx context.Context, userID string) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, getTodayEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoogleEventID,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.Location,
			&i.Attendees,
			&i.Status,
			&i.Visibility,
			&i.HtmlLink,
			&i.Source,
			&i.MeetingType,
			&i.ContextID,
			&i.ProjectID,
			&i.ClientID,
			&i.RecordingUrl,
			&i.MeetingLink,
			&i.ExternalLinks,
			&i.MeetingNotes,
			&i.ActionItems,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingEvents = `-- name: GetUpcomingEvents :many
SELECT id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at FROM calendar_events
WHERE user_id = $1
  AND start_time > NOW()
ORDER BY start_time ASC
LIMIT $2
`

type GetUpcomingEventsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetUpcomingEvents(ctx context.Context, arg GetUpcomingEventsParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, getUpcomingEvents, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoogleEventID,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.Location,
			&i.Attendees,
			&i.Status,
			&i.Visibility,
			&i.HtmlLink,
			&i.Source,
			&i.MeetingType,
			&i.ContextID,
			&i.ProjectID,
			&i.ClientID,
			&i.RecordingUrl,
			&i.MeetingLink,
			&i.ExternalLinks,
			&i.MeetingNotes,
			&i.ActionItems,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarEvents = `-- name: ListCalendarEvents :many
SELECT id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at FROM calendar_events
WHERE user_id = $1
  AND start_time < $2
  AND end_time > $3
ORDER BY start_time ASC
`

type ListCalendarEventsParams struct {
	UserID    string             `json:"user_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

// Get events that overlap with the date range (start_time < range_end AND end_time > range_start)
// Params: $1=user_id, $2=range_end (EndTime), $3=range_start (StartTime)
func (q *Queries) ListCalendarEvents(ctx context.Context, arg ListCalendarEventsParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listCalendarEvents, arg.UserID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoogleEventID,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.Location,
			&i.Attendees,
			&i.Status,
			&i.Visibility,
			&i.HtmlLink,
			&i.Source,
			&i.MeetingType,
			&i.ContextID,
			&i.ProjectID,
			&i.ClientID,
			&i.RecordingUrl,
			&i.MeetingLink,
			&i.ExternalLinks,
			&i.MeetingNotes,
			&i.ActionItems,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarEventsByType = `-- name: ListCalendarEventsByType :many
SELECT id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at FROM calendar_events
WHERE user_id = $1
  AND meeting_type = $2
  AND start_time >= $3
  AND end_time <= $4
ORDER BY start_time ASC
`

type ListCalendarEventsByTypeParams struct {
	UserID      string             `json:"user_id"`
	MeetingType NullMeetingtype    `json:"meeting_type"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) ListCalendarEventsByType(ctx context.Context, arg ListCalendarEventsByTypeParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listCalendarEventsByType,
		arg.UserID,
		arg.MeetingType,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoogleEventID,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.Location,
			&i.Attendees,
			&i.Status,
			&i.Visibility,
			&i.HtmlLink,
			&i.Source,
			&i.MeetingType,
			&i.ContextID,
			&i.ProjectID,
			&i.ClientID,
			&i.RecordingUrl,
			&i.MeetingLink,
			&i.ExternalLinks,
			&i.MeetingNotes,
			&i.ActionItems,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMeetings = `-- name: SearchMeetings :many
SELECT id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at FROM calendar_events
WHERE user_id = $1
  AND (
    title ILIKE '%' || $2 || '%'
    OR description ILIKE '%' || $2 || '%'
    OR meeting_notes ILIKE '%' || $2 || '%'
  )
ORDER BY start_time DESC
LIMIT $3
`

type SearchMeetingsParams struct {
	UserID  string  `json:"user_id"`
	Column2 *string `json:"column_2"`
	Limit   int32   `json:"limit"`
}

func (q *Queries) SearchMeetings(ctx context.Context, arg SearchMeetingsParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, searchMeetings, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoogleEventID,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.Location,
			&i.Attendees,
			&i.Status,
			&i.Visibility,
			&i.HtmlLink,
			&i.Source,
			&i.MeetingType,
			&i.ContextID,
			&i.ProjectID,
			&i.ClientID,
			&i.RecordingUrl,
			&i.MeetingLink,
			&i.ExternalLinks,
			&i.MeetingNotes,
			&i.ActionItems,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendarEvent = `-- name: UpdateCalendarEvent :one
UPDATE calendar_events
SET title = $3,
    description = $4,
    start_time = $5,
    end_time = $6,
    all_day = $7,
    location = $8,
    attendees = $9,
    status = $10,
    visibility = $11,
    html_link = $12,
    meeting_type = $13,
    context_id = $14,
    project_id = $15,
    client_id = $16,
    recording_url = $17,
    meeting_link = $18,
    external_links = $19,
    meeting_notes = $20,
    action_items = $21,
    synced_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at
`

type UpdateCalendarEventParams struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        string             `json:"user_id"`
	Title         *string            `json:"title"`
	Description   *string            `json:"description"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
	AllDay        *bool              `json:"all_day"`
	Location      *string            `json:"location"`
	Attendees     []byte             `json:"attendees"`
	Status        *string            `json:"status"`
	Visibility    *string            `json:"visibility"`
	HtmlLink      *string            `json:"html_link"`
	MeetingType   NullMeetingtype    `json:"meeting_type"`
	ContextID     pgtype.UUID        `json:"context_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ClientID      pgtype.UUID        `json:"client_id"`
	RecordingUrl  *string            `json:"recording_url"`
	MeetingLink   *string            `json:"meeting_link"`
	ExternalLinks []byte             `json:"external_links"`
	MeetingNotes  *string            `json:"meeting_notes"`
	ActionItems   []byte             `json:"action_items"`
}

func (q *Queries) UpdateCalendarEvent(ctx context.Context, arg UpdateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, updateCalendarEvent,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.Location,
		arg.Attendees,
		arg.Status,
		arg.Visibility,
		arg.HtmlLink,
		arg.MeetingType,
		arg.ContextID,
		arg.ProjectID,
		arg.ClientID,
		arg.RecordingUrl,
		arg.MeetingLink,
		arg.ExternalLinks,
		arg.MeetingNotes,
		arg.ActionItems,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoogleEventID,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.Attendees,
		&i.Status,
		&i.Visibility,
		&i.HtmlLink,
		&i.Source,
		&i.MeetingType,
		&i.ContextID,
		&i.ProjectID,
		&i.ClientID,
		&i.RecordingUrl,
		&i.MeetingLink,
		&i.ExternalLinks,
		&i.MeetingNotes,
		&i.ActionItems,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMeetingDetails = `-- name: UpdateMeetingDetails :one
UPDATE calendar_events
SET meeting_type = $3,
    context_id = $4,
    project_id = $5,
    client_id = $6,
    recording_url = $7,
    meeting_link = $8,
    external_links = $9,
    meeting_notes = $10,
    action_items = $11,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at
`

type UpdateMeetingDetailsParams struct {
	ID            pgtype.UUID     `json:"id"`
	UserID        string          `json:"user_id"`
	MeetingType   NullMeetingtype `json:"meeting_type"`
	ContextID     pgtype.UUID     `json:"context_id"`
	ProjectID     pgtype.UUID     `json:"project_id"`
	ClientID      pgtype.UUID     `json:"client_id"`
	RecordingUrl  *string         `json:"recording_url"`
	MeetingLink   *string         `json:"meeting_link"`
	ExternalLinks []byte          `json:"external_links"`
	MeetingNotes  *string         `json:"meeting_notes"`
	ActionItems   []byte          `json:"action_items"`
}

func (q *Queries) UpdateMeetingDetails(ctx context.Context, arg UpdateMeetingDetailsParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, updateMeetingDetails,
		arg.ID,
		arg.UserID,
		arg.MeetingType,
		arg.ContextID,
		arg.ProjectID,
		arg.ClientID,
		arg.RecordingUrl,
		arg.MeetingLink,
		arg.ExternalLinks,
		arg.MeetingNotes,
		arg.ActionItems,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoogleEventID,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.Attendees,
		&i.Status,
		&i.Visibility,
		&i.HtmlLink,
		&i.Source,
		&i.MeetingType,
		&i.ContextID,
		&i.ProjectID,
		&i.ClientID,
		&i.RecordingUrl,
		&i.MeetingLink,
		&i.ExternalLinks,
		&i.MeetingNotes,
		&i.ActionItems,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCalendarEvent = `-- name: UpsertCalendarEvent :one
INSERT INTO calendar_events (
    user_id, google_event_id, calendar_id, title, description,
    start_time, end_time, all_day, location, attendees,
    status, visibility, html_link, source, meeting_link, external_links
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (user_id, google_event_id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    start_time = EXCLUDED.start_time,
    end_time = EXCLUDED.end_time,
    all_day = EXCLUDED.all_day,
    location = EXCLUDED.location,
    attendees = EXCLUDED.attendees,
    status = EXCLUDED.status,
    visibility = EXCLUDED.visibility,
    html_link = EXCLUDED.html_link,
    meeting_link = EXCLUDED.meeting_link,
    external_links = EXCLUDED.external_links,
    synced_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, google_event_id, calendar_id, title, description, start_time, end_time, all_day, location, attendees, status, visibility, html_link, source, meeting_type, context_id, project_id, client_id, recording_url, meeting_link, external_links, meeting_notes, action_items, synced_at, created_at, updated_at
`

type UpsertCalendarEventParams struct {
	UserID        string             `json:"user_id"`
	GoogleEventID *string            `json:"google_event_id"`
	CalendarID    *string            `json:"calendar_id"`
	Title         *string            `json:"title"`
	Description   *string            `json:"description"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
	AllDay        *bool              `json:"all_day"`
	Location      *string            `json:"location"`
	Attendees     []byte             `json:"attendees"`
	Status        *string            `json:"status"`
	Visibility    *string            `json:"visibility"`
	HtmlLink      *string            `json:"html_link"`
	Source        *string            `json:"source"`
	MeetingLink   *string            `json:"meeting_link"`
	ExternalLinks []byte             `json:"external_links"`
}

func (q *Queries) UpsertCalendarEvent(ctx context.Context, arg UpsertCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, upsertCalendarEvent,
		arg.UserID,
		arg.GoogleEventID,
		arg.CalendarID,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.Location,
		arg.Attendees,
		arg.Status,
		arg.Visibility,
		arg.HtmlLink,
		arg.Source,
		arg.MeetingLink,
		arg.ExternalLinks,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoogleEventID,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.Attendees,
		&i.Status,
		&i.Visibility,
		&i.HtmlLink,
		&i.Source,
		&i.MeetingType,
		&i.ContextID,
		&i.ProjectID,
		&i.ClientID,
		&i.RecordingUrl,
		&i.MeetingLink,
		&i.ExternalLinks,
		&i.MeetingNotes,
		&i.ActionItems,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
