// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hubspot.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHubSpotCompanies = `-- name: CountHubSpotCompanies :one
SELECT COUNT(*) FROM hubspot_companies
WHERE user_id = $1
`

func (q *Queries) CountHubSpotCompanies(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countHubSpotCompanies, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHubSpotContacts = `-- name: CountHubSpotContacts :one
SELECT COUNT(*) FROM hubspot_contacts
WHERE user_id = $1
`

func (q *Queries) CountHubSpotContacts(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countHubSpotContacts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHubSpotContactsByStage = `-- name: CountHubSpotContactsByStage :many
SELECT lifecycle_stage, COUNT(*) as count
FROM hubspot_contacts
WHERE user_id = $1
GROUP BY lifecycle_stage
ORDER BY count DESC
`

type CountHubSpotContactsByStageRow struct {
	LifecycleStage *string `json:"lifecycle_stage"`
	Count          int64   `json:"count"`
}

func (q *Queries) CountHubSpotContactsByStage(ctx context.Context, userID string) ([]CountHubSpotContactsByStageRow, error) {
	rows, err := q.db.Query(ctx, countHubSpotContactsByStage, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountHubSpotContactsByStageRow{}
	for rows.Next() {
		var i CountHubSpotContactsByStageRow
		if err := rows.Scan(&i.LifecycleStage, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countHubSpotDealsByStage = `-- name: CountHubSpotDealsByStage :many
SELECT deal_stage, COUNT(*) as count, COALESCE(SUM(amount), 0) as total_value
FROM hubspot_deals
WHERE user_id = $1
GROUP BY deal_stage
ORDER BY count DESC
`

type CountHubSpotDealsByStageRow struct {
	DealStage  *string     `json:"deal_stage"`
	Count      int64       `json:"count"`
	TotalValue interface{} `json:"total_value"`
}

func (q *Queries) CountHubSpotDealsByStage(ctx context.Context, userID string) ([]CountHubSpotDealsByStageRow, error) {
	rows, err := q.db.Query(ctx, countHubSpotDealsByStage, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountHubSpotDealsByStageRow{}
	for rows.Next() {
		var i CountHubSpotDealsByStageRow
		if err := rows.Scan(&i.DealStage, &i.Count, &i.TotalValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteHubSpotCompaniesByUser = `-- name: DeleteHubSpotCompaniesByUser :exec
DELETE FROM hubspot_companies WHERE user_id = $1
`

func (q *Queries) DeleteHubSpotCompaniesByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteHubSpotCompaniesByUser, userID)
	return err
}

const deleteHubSpotCompany = `-- name: DeleteHubSpotCompany :exec
DELETE FROM hubspot_companies
WHERE user_id = $1 AND hubspot_id = $2
`

type DeleteHubSpotCompanyParams struct {
	UserID    string `json:"user_id"`
	HubspotID string `json:"hubspot_id"`
}

func (q *Queries) DeleteHubSpotCompany(ctx context.Context, arg DeleteHubSpotCompanyParams) error {
	_, err := q.db.Exec(ctx, deleteHubSpotCompany, arg.UserID, arg.HubspotID)
	return err
}

const deleteHubSpotContact = `-- name: DeleteHubSpotContact :exec
DELETE FROM hubspot_contacts
WHERE user_id = $1 AND hubspot_id = $2
`

type DeleteHubSpotContactParams struct {
	UserID    string `json:"user_id"`
	HubspotID string `json:"hubspot_id"`
}

func (q *Queries) DeleteHubSpotContact(ctx context.Context, arg DeleteHubSpotContactParams) error {
	_, err := q.db.Exec(ctx, deleteHubSpotContact, arg.UserID, arg.HubspotID)
	return err
}

const deleteHubSpotContactsByUser = `-- name: DeleteHubSpotContactsByUser :exec
DELETE FROM hubspot_contacts WHERE user_id = $1
`

func (q *Queries) DeleteHubSpotContactsByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteHubSpotContactsByUser, userID)
	return err
}

const deleteHubSpotDeal = `-- name: DeleteHubSpotDeal :exec
DELETE FROM hubspot_deals
WHERE user_id = $1 AND hubspot_id = $2
`

type DeleteHubSpotDealParams struct {
	UserID    string `json:"user_id"`
	HubspotID string `json:"hubspot_id"`
}

func (q *Queries) DeleteHubSpotDeal(ctx context.Context, arg DeleteHubSpotDealParams) error {
	_, err := q.db.Exec(ctx, deleteHubSpotDeal, arg.UserID, arg.HubspotID)
	return err
}

const deleteHubSpotDealsByUser = `-- name: DeleteHubSpotDealsByUser :exec
DELETE FROM hubspot_deals WHERE user_id = $1
`

func (q *Queries) DeleteHubSpotDealsByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteHubSpotDealsByUser, userID)
	return err
}

const getHubSpotCompaniesByIndustry = `-- name: GetHubSpotCompaniesByIndustry :many
SELECT id, user_id, hubspot_id, name, domain, industry, number_of_employees, annual_revenue, city, state, country, owner_id, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_companies
WHERE user_id = $1 AND industry = $2
ORDER BY annual_revenue DESC NULLS LAST
LIMIT $3 OFFSET $4
`

type GetHubSpotCompaniesByIndustryParams struct {
	UserID   string  `json:"user_id"`
	Industry *string `json:"industry"`
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
}

func (q *Queries) GetHubSpotCompaniesByIndustry(ctx context.Context, arg GetHubSpotCompaniesByIndustryParams) ([]HubspotCompany, error) {
	rows, err := q.db.Query(ctx, getHubSpotCompaniesByIndustry,
		arg.UserID,
		arg.Industry,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubspotCompany{}
	for rows.Next() {
		var i HubspotCompany
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HubspotID,
			&i.Name,
			&i.Domain,
			&i.Industry,
			&i.NumberOfEmployees,
			&i.AnnualRevenue,
			&i.City,
			&i.State,
			&i.Country,
			&i.OwnerID,
			&i.Properties,
			&i.CreatedAtHubspot,
			&i.UpdatedAtHubspot,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHubSpotCompaniesByUser = `-- name: GetHubSpotCompaniesByUser :many
SELECT id, user_id, hubspot_id, name, domain, industry, number_of_employees, annual_revenue, city, state, country, owner_id, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_companies
WHERE user_id = $1
ORDER BY updated_at_hubspot DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type GetHubSpotCompaniesByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetHubSpotCompaniesByUser(ctx context.Context, arg GetHubSpotCompaniesByUserParams) ([]HubspotCompany, error) {
	rows, err := q.db.Query(ctx, getHubSpotCompaniesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubspotCompany{}
	for rows.Next() {
		var i HubspotCompany
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HubspotID,
			&i.Name,
			&i.Domain,
			&i.Industry,
			&i.NumberOfEmployees,
			&i.AnnualRevenue,
			&i.City,
			&i.State,
			&i.Country,
			&i.OwnerID,
			&i.Properties,
			&i.CreatedAtHubspot,
			&i.UpdatedAtHubspot,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHubSpotCompany = `-- name: GetHubSpotCompany :one
SELECT id, user_id, hubspot_id, name, domain, industry, number_of_employees, annual_revenue, city, state, country, owner_id, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_companies
WHERE user_id = $1 AND hubspot_id = $2
`

type GetHubSpotCompanyParams struct {
	UserID    string `json:"user_id"`
	HubspotID string `json:"hubspot_id"`
}

func (q *Queries) GetHubSpotCompany(ctx context.Context, arg GetHubSpotCompanyParams) (HubspotCompany, error) {
	row := q.db.QueryRow(ctx, getHubSpotCompany, arg.UserID, arg.HubspotID)
	var i HubspotCompany
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HubspotID,
		&i.Name,
		&i.Domain,
		&i.Industry,
		&i.NumberOfEmployees,
		&i.AnnualRevenue,
		&i.City,
		&i.State,
		&i.Country,
		&i.OwnerID,
		&i.Properties,
		&i.CreatedAtHubspot,
		&i.UpdatedAtHubspot,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHubSpotCompanyByDomain = `-- name: GetHubSpotCompanyByDomain :one
SELECT id, user_id, hubspot_id, name, domain, industry, number_of_employees, annual_revenue, city, state, country, owner_id, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_companies
WHERE user_id = $1 AND domain = $2
`

type GetHubSpotCompanyByDomainParams struct {
	UserID string  `json:"user_id"`
	Domain *string `json:"domain"`
}

func (q *Queries) GetHubSpotCompanyByDomain(ctx context.Context, arg GetHubSpotCompanyByDomainParams) (HubspotCompany, error) {
	row := q.db.QueryRow(ctx, getHubSpotCompanyByDomain, arg.UserID, arg.Domain)
	var i HubspotCompany
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HubspotID,
		&i.Name,
		&i.Domain,
		&i.Industry,
		&i.NumberOfEmployees,
		&i.AnnualRevenue,
		&i.City,
		&i.State,
		&i.Country,
		&i.OwnerID,
		&i.Properties,
		&i.CreatedAtHubspot,
		&i.UpdatedAtHubspot,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHubSpotContact = `-- name: GetHubSpotContact :one
SELECT id, user_id, hubspot_id, email, first_name, last_name, phone, company, job_title, lifecycle_stage, lead_status, owner_id, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_contacts
WHERE user_id = $1 AND hubspot_id = $2
`

type GetHubSpotContactParams struct {
	UserID    string `json:"user_id"`
	HubspotID string `json:"hubspot_id"`
}

func (q *Queries) GetHubSpotContact(ctx context.Context, arg GetHubSpotContactParams) (HubspotContact, error) {
	row := q.db.QueryRow(ctx, getHubSpotContact, arg.UserID, arg.HubspotID)
	var i HubspotContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HubspotID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Company,
		&i.JobTitle,
		&i.LifecycleStage,
		&i.LeadStatus,
		&i.OwnerID,
		&i.Properties,
		&i.CreatedAtHubspot,
		&i.UpdatedAtHubspot,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHubSpotContactByEmail = `-- name: GetHubSpotContactByEmail :one
SELECT id, user_id, hubspot_id, email, first_name, last_name, phone, company, job_title, lifecycle_stage, lead_status, owner_id, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_contacts
WHERE user_id = $1 AND email = $2
`

type GetHubSpotContactByEmailParams struct {
	UserID string  `json:"user_id"`
	Email  *string `json:"email"`
}

func (q *Queries) GetHubSpotContactByEmail(ctx context.Context, arg GetHubSpotContactByEmailParams) (HubspotContact, error) {
	row := q.db.QueryRow(ctx, getHubSpotContactByEmail, arg.UserID, arg.Email)
	var i HubspotContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HubspotID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Company,
		&i.JobTitle,
		&i.LifecycleStage,
		&i.LeadStatus,
		&i.OwnerID,
		&i.Properties,
		&i.CreatedAtHubspot,
		&i.UpdatedAtHubspot,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHubSpotContactsByLifecycleStage = `-- name: GetHubSpotContactsByLifecycleStage :many
SELECT id, user_id, hubspot_id, email, first_name, last_name, phone, company, job_title, lifecycle_stage, lead_status, owner_id, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_contacts
WHERE user_id = $1 AND lifecycle_stage = $2
ORDER BY updated_at_hubspot DESC NULLS LAST
LIMIT $3 OFFSET $4
`

type GetHubSpotContactsByLifecycleStageParams struct {
	UserID         string  `json:"user_id"`
	LifecycleStage *string `json:"lifecycle_stage"`
	Limit          int32   `json:"limit"`
	Offset         int32   `json:"offset"`
}

func (q *Queries) GetHubSpotContactsByLifecycleStage(ctx context.Context, arg GetHubSpotContactsByLifecycleStageParams) ([]HubspotContact, error) {
	rows, err := q.db.Query(ctx, getHubSpotContactsByLifecycleStage,
		arg.UserID,
		arg.LifecycleStage,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubspotContact{}
	for rows.Next() {
		var i HubspotContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HubspotID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Company,
			&i.JobTitle,
			&i.LifecycleStage,
			&i.LeadStatus,
			&i.OwnerID,
			&i.Properties,
			&i.CreatedAtHubspot,
			&i.UpdatedAtHubspot,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHubSpotContactsByOwner = `-- name: GetHubSpotContactsByOwner :many
SELECT id, user_id, hubspot_id, email, first_name, last_name, phone, company, job_title, lifecycle_stage, lead_status, owner_id, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_contacts
WHERE user_id = $1 AND owner_id = $2
ORDER BY updated_at_hubspot DESC NULLS LAST
LIMIT $3 OFFSET $4
`

type GetHubSpotContactsByOwnerParams struct {
	UserID  string  `json:"user_id"`
	OwnerID *string `json:"owner_id"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

func (q *Queries) GetHubSpotContactsByOwner(ctx context.Context, arg GetHubSpotContactsByOwnerParams) ([]HubspotContact, error) {
	rows, err := q.db.Query(ctx, getHubSpotContactsByOwner,
		arg.UserID,
		arg.OwnerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubspotContact{}
	for rows.Next() {
		var i HubspotContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HubspotID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Company,
			&i.JobTitle,
			&i.LifecycleStage,
			&i.LeadStatus,
			&i.OwnerID,
			&i.Properties,
			&i.CreatedAtHubspot,
			&i.UpdatedAtHubspot,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHubSpotContactsByUser = `-- name: GetHubSpotContactsByUser :many
SELECT id, user_id, hubspot_id, email, first_name, last_name, phone, company, job_title, lifecycle_stage, lead_status, owner_id, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_contacts
WHERE user_id = $1
ORDER BY updated_at_hubspot DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type GetHubSpotContactsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetHubSpotContactsByUser(ctx context.Context, arg GetHubSpotContactsByUserParams) ([]HubspotContact, error) {
	rows, err := q.db.Query(ctx, getHubSpotContactsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubspotContact{}
	for rows.Next() {
		var i HubspotContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HubspotID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Company,
			&i.JobTitle,
			&i.LifecycleStage,
			&i.LeadStatus,
			&i.OwnerID,
			&i.Properties,
			&i.CreatedAtHubspot,
			&i.UpdatedAtHubspot,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHubSpotDeal = `-- name: GetHubSpotDeal :one
SELECT id, user_id, hubspot_id, deal_name, amount, pipeline, deal_stage, close_date, owner_id, associated_company_ids, associated_contact_ids, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_deals
WHERE user_id = $1 AND hubspot_id = $2
`

type GetHubSpotDealParams struct {
	UserID    string `json:"user_id"`
	HubspotID string `json:"hubspot_id"`
}

func (q *Queries) GetHubSpotDeal(ctx context.Context, arg GetHubSpotDealParams) (HubspotDeal, error) {
	row := q.db.QueryRow(ctx, getHubSpotDeal, arg.UserID, arg.HubspotID)
	var i HubspotDeal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HubspotID,
		&i.DealName,
		&i.Amount,
		&i.Pipeline,
		&i.DealStage,
		&i.CloseDate,
		&i.OwnerID,
		&i.AssociatedCompanyIds,
		&i.AssociatedContactIds,
		&i.Properties,
		&i.CreatedAtHubspot,
		&i.UpdatedAtHubspot,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHubSpotDealsByPipeline = `-- name: GetHubSpotDealsByPipeline :many
SELECT id, user_id, hubspot_id, deal_name, amount, pipeline, deal_stage, close_date, owner_id, associated_company_ids, associated_contact_ids, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_deals
WHERE user_id = $1 AND pipeline = $2
ORDER BY close_date NULLS LAST
LIMIT $3 OFFSET $4
`

type GetHubSpotDealsByPipelineParams struct {
	UserID   string  `json:"user_id"`
	Pipeline *string `json:"pipeline"`
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
}

func (q *Queries) GetHubSpotDealsByPipeline(ctx context.Context, arg GetHubSpotDealsByPipelineParams) ([]HubspotDeal, error) {
	rows, err := q.db.Query(ctx, getHubSpotDealsByPipeline,
		arg.UserID,
		arg.Pipeline,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubspotDeal{}
	for rows.Next() {
		var i HubspotDeal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HubspotID,
			&i.DealName,
			&i.Amount,
			&i.Pipeline,
			&i.DealStage,
			&i.CloseDate,
			&i.OwnerID,
			&i.AssociatedCompanyIds,
			&i.AssociatedContactIds,
			&i.Properties,
			&i.CreatedAtHubspot,
			&i.UpdatedAtHubspot,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHubSpotDealsByStage = `-- name: GetHubSpotDealsByStage :many
SELECT id, user_id, hubspot_id, deal_name, amount, pipeline, deal_stage, close_date, owner_id, associated_company_ids, associated_contact_ids, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_deals
WHERE user_id = $1 AND deal_stage = $2
ORDER BY amount DESC NULLS LAST
LIMIT $3 OFFSET $4
`

type GetHubSpotDealsByStageParams struct {
	UserID    string  `json:"user_id"`
	DealStage *string `json:"deal_stage"`
	Limit     int32   `json:"limit"`
	Offset    int32   `json:"offset"`
}

func (q *Queries) GetHubSpotDealsByStage(ctx context.Context, arg GetHubSpotDealsByStageParams) ([]HubspotDeal, error) {
	rows, err := q.db.Query(ctx, getHubSpotDealsByStage,
		arg.UserID,
		arg.DealStage,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubspotDeal{}
	for rows.Next() {
		var i HubspotDeal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HubspotID,
			&i.DealName,
			&i.Amount,
			&i.Pipeline,
			&i.DealStage,
			&i.CloseDate,
			&i.OwnerID,
			&i.AssociatedCompanyIds,
			&i.AssociatedContactIds,
			&i.Properties,
			&i.CreatedAtHubspot,
			&i.UpdatedAtHubspot,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHubSpotDealsByUser = `-- name: GetHubSpotDealsByUser :many
SELECT id, user_id, hubspot_id, deal_name, amount, pipeline, deal_stage, close_date, owner_id, associated_company_ids, associated_contact_ids, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_deals
WHERE user_id = $1
ORDER BY updated_at_hubspot DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type GetHubSpotDealsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetHubSpotDealsByUser(ctx context.Context, arg GetHubSpotDealsByUserParams) ([]HubspotDeal, error) {
	rows, err := q.db.Query(ctx, getHubSpotDealsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubspotDeal{}
	for rows.Next() {
		var i HubspotDeal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HubspotID,
			&i.DealName,
			&i.Amount,
			&i.Pipeline,
			&i.DealStage,
			&i.CloseDate,
			&i.OwnerID,
			&i.AssociatedCompanyIds,
			&i.AssociatedContactIds,
			&i.Properties,
			&i.CreatedAtHubspot,
			&i.UpdatedAtHubspot,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHubSpotDealsClosingSoon = `-- name: GetHubSpotDealsClosingSoon :many
SELECT id, user_id, hubspot_id, deal_name, amount, pipeline, deal_stage, close_date, owner_id, associated_company_ids, associated_contact_ids, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_deals
WHERE user_id = $1
  AND close_date IS NOT NULL
  AND close_date <= $2
  AND deal_stage NOT IN ('closedwon', 'closedlost')
ORDER BY close_date
`

type GetHubSpotDealsClosingSoonParams struct {
	UserID    string      `json:"user_id"`
	CloseDate pgtype.Date `json:"close_date"`
}

func (q *Queries) GetHubSpotDealsClosingSoon(ctx context.Context, arg GetHubSpotDealsClosingSoonParams) ([]HubspotDeal, error) {
	rows, err := q.db.Query(ctx, getHubSpotDealsClosingSoon, arg.UserID, arg.CloseDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubspotDeal{}
	for rows.Next() {
		var i HubspotDeal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HubspotID,
			&i.DealName,
			&i.Amount,
			&i.Pipeline,
			&i.DealStage,
			&i.CloseDate,
			&i.OwnerID,
			&i.AssociatedCompanyIds,
			&i.AssociatedContactIds,
			&i.Properties,
			&i.CreatedAtHubspot,
			&i.UpdatedAtHubspot,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHubSpotDealsPipelineValue = `-- name: GetHubSpotDealsPipelineValue :one
SELECT
    COUNT(*) as deal_count,
    COALESCE(SUM(amount), 0) as total_value
FROM hubspot_deals
WHERE user_id = $1
  AND deal_stage NOT IN ('closedwon', 'closedlost')
`

type GetHubSpotDealsPipelineValueRow struct {
	DealCount  int64       `json:"deal_count"`
	TotalValue interface{} `json:"total_value"`
}

func (q *Queries) GetHubSpotDealsPipelineValue(ctx context.Context, userID string) (GetHubSpotDealsPipelineValueRow, error) {
	row := q.db.QueryRow(ctx, getHubSpotDealsPipelineValue, userID)
	var i GetHubSpotDealsPipelineValueRow
	err := row.Scan(&i.DealCount, &i.TotalValue)
	return i, err
}

const getHubSpotDealsWonValue = `-- name: GetHubSpotDealsWonValue :one
SELECT
    COUNT(*) as deal_count,
    COALESCE(SUM(amount), 0) as total_value
FROM hubspot_deals
WHERE user_id = $1 AND deal_stage = 'closedwon'
`

type GetHubSpotDealsWonValueRow struct {
	DealCount  int64       `json:"deal_count"`
	TotalValue interface{} `json:"total_value"`
}

func (q *Queries) GetHubSpotDealsWonValue(ctx context.Context, userID string) (GetHubSpotDealsWonValueRow, error) {
	row := q.db.QueryRow(ctx, getHubSpotDealsWonValue, userID)
	var i GetHubSpotDealsWonValueRow
	err := row.Scan(&i.DealCount, &i.TotalValue)
	return i, err
}

const searchHubSpotCompanies = `-- name: SearchHubSpotCompanies :many
SELECT id, user_id, hubspot_id, name, domain, industry, number_of_employees, annual_revenue, city, state, country, owner_id, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_companies
WHERE user_id = $1
  AND (name ILIKE $2 OR domain ILIKE $2)
ORDER BY updated_at_hubspot DESC NULLS LAST
LIMIT $3
`

type SearchHubSpotCompaniesParams struct {
	UserID string  `json:"user_id"`
	Name   *string `json:"name"`
	Limit  int32   `json:"limit"`
}

func (q *Queries) SearchHubSpotCompanies(ctx context.Context, arg SearchHubSpotCompaniesParams) ([]HubspotCompany, error) {
	rows, err := q.db.Query(ctx, searchHubSpotCompanies, arg.UserID, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubspotCompany{}
	for rows.Next() {
		var i HubspotCompany
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HubspotID,
			&i.Name,
			&i.Domain,
			&i.Industry,
			&i.NumberOfEmployees,
			&i.AnnualRevenue,
			&i.City,
			&i.State,
			&i.Country,
			&i.OwnerID,
			&i.Properties,
			&i.CreatedAtHubspot,
			&i.UpdatedAtHubspot,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHubSpotContacts = `-- name: SearchHubSpotContacts :many
SELECT id, user_id, hubspot_id, email, first_name, last_name, phone, company, job_title, lifecycle_stage, lead_status, owner_id, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_contacts
WHERE user_id = $1
  AND (
    email ILIKE $2
    OR first_name ILIKE $2
    OR last_name ILIKE $2
    OR company ILIKE $2
  )
ORDER BY updated_at_hubspot DESC NULLS LAST
LIMIT $3
`

type SearchHubSpotContactsParams struct {
	UserID string  `json:"user_id"`
	Email  *string `json:"email"`
	Limit  int32   `json:"limit"`
}

func (q *Queries) SearchHubSpotContacts(ctx context.Context, arg SearchHubSpotContactsParams) ([]HubspotContact, error) {
	rows, err := q.db.Query(ctx, searchHubSpotContacts, arg.UserID, arg.Email, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubspotContact{}
	for rows.Next() {
		var i HubspotContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HubspotID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Company,
			&i.JobTitle,
			&i.LifecycleStage,
			&i.LeadStatus,
			&i.OwnerID,
			&i.Properties,
			&i.CreatedAtHubspot,
			&i.UpdatedAtHubspot,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHubSpotDeals = `-- name: SearchHubSpotDeals :many
SELECT id, user_id, hubspot_id, deal_name, amount, pipeline, deal_stage, close_date, owner_id, associated_company_ids, associated_contact_ids, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at FROM hubspot_deals
WHERE user_id = $1 AND deal_name ILIKE $2
ORDER BY amount DESC NULLS LAST
LIMIT $3
`

type SearchHubSpotDealsParams struct {
	UserID   string  `json:"user_id"`
	DealName *string `json:"deal_name"`
	Limit    int32   `json:"limit"`
}

func (q *Queries) SearchHubSpotDeals(ctx context.Context, arg SearchHubSpotDealsParams) ([]HubspotDeal, error) {
	rows, err := q.db.Query(ctx, searchHubSpotDeals, arg.UserID, arg.DealName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubspotDeal{}
	for rows.Next() {
		var i HubspotDeal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HubspotID,
			&i.DealName,
			&i.Amount,
			&i.Pipeline,
			&i.DealStage,
			&i.CloseDate,
			&i.OwnerID,
			&i.AssociatedCompanyIds,
			&i.AssociatedContactIds,
			&i.Properties,
			&i.CreatedAtHubspot,
			&i.UpdatedAtHubspot,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHubSpotCompany = `-- name: UpsertHubSpotCompany :one

INSERT INTO hubspot_companies (
    user_id, hubspot_id, name, domain, industry, number_of_employees,
    annual_revenue, city, state, country, owner_id, properties,
    created_at_hubspot, updated_at_hubspot, synced_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NOW())
ON CONFLICT (user_id, hubspot_id) DO UPDATE SET
    name = EXCLUDED.name,
    domain = EXCLUDED.domain,
    industry = EXCLUDED.industry,
    number_of_employees = EXCLUDED.number_of_employees,
    annual_revenue = EXCLUDED.annual_revenue,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    country = EXCLUDED.country,
    owner_id = EXCLUDED.owner_id,
    properties = EXCLUDED.properties,
    updated_at_hubspot = EXCLUDED.updated_at_hubspot,
    synced_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, hubspot_id, name, domain, industry, number_of_employees, annual_revenue, city, state, country, owner_id, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at
`

type UpsertHubSpotCompanyParams struct {
	UserID            string             `json:"user_id"`
	HubspotID         string             `json:"hubspot_id"`
	Name              *string            `json:"name"`
	Domain            *string            `json:"domain"`
	Industry          *string            `json:"industry"`
	NumberOfEmployees *int32             `json:"number_of_employees"`
	AnnualRevenue     pgtype.Numeric     `json:"annual_revenue"`
	City              *string            `json:"city"`
	State             *string            `json:"state"`
	Country           *string            `json:"country"`
	OwnerID           *string            `json:"owner_id"`
	Properties        []byte             `json:"properties"`
	CreatedAtHubspot  pgtype.Timestamptz `json:"created_at_hubspot"`
	UpdatedAtHubspot  pgtype.Timestamptz `json:"updated_at_hubspot"`
}

// ============================================================================
// HubSpot Companies
// ============================================================================
func (q *Queries) UpsertHubSpotCompany(ctx context.Context, arg UpsertHubSpotCompanyParams) (HubspotCompany, error) {
	row := q.db.QueryRow(ctx, upsertHubSpotCompany,
		arg.UserID,
		arg.HubspotID,
		arg.Name,
		arg.Domain,
		arg.Industry,
		arg.NumberOfEmployees,
		arg.AnnualRevenue,
		arg.City,
		arg.State,
		arg.Country,
		arg.OwnerID,
		arg.Properties,
		arg.CreatedAtHubspot,
		arg.UpdatedAtHubspot,
	)
	var i HubspotCompany
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HubspotID,
		&i.Name,
		&i.Domain,
		&i.Industry,
		&i.NumberOfEmployees,
		&i.AnnualRevenue,
		&i.City,
		&i.State,
		&i.Country,
		&i.OwnerID,
		&i.Properties,
		&i.CreatedAtHubspot,
		&i.UpdatedAtHubspot,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHubSpotContact = `-- name: UpsertHubSpotContact :one


INSERT INTO hubspot_contacts (
    user_id, hubspot_id, email, first_name, last_name, phone,
    company, job_title, lifecycle_stage, lead_status, owner_id,
    properties, created_at_hubspot, updated_at_hubspot, synced_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NOW())
ON CONFLICT (user_id, hubspot_id) DO UPDATE SET
    email = EXCLUDED.email,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    phone = EXCLUDED.phone,
    company = EXCLUDED.company,
    job_title = EXCLUDED.job_title,
    lifecycle_stage = EXCLUDED.lifecycle_stage,
    lead_status = EXCLUDED.lead_status,
    owner_id = EXCLUDED.owner_id,
    properties = EXCLUDED.properties,
    updated_at_hubspot = EXCLUDED.updated_at_hubspot,
    synced_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, hubspot_id, email, first_name, last_name, phone, company, job_title, lifecycle_stage, lead_status, owner_id, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at
`

type UpsertHubSpotContactParams struct {
	UserID           string             `json:"user_id"`
	HubspotID        string             `json:"hubspot_id"`
	Email            *string            `json:"email"`
	FirstName        *string            `json:"first_name"`
	LastName         *string            `json:"last_name"`
	Phone            *string            `json:"phone"`
	Company          *string            `json:"company"`
	JobTitle         *string            `json:"job_title"`
	LifecycleStage   *string            `json:"lifecycle_stage"`
	LeadStatus       *string            `json:"lead_status"`
	OwnerID          *string            `json:"owner_id"`
	Properties       []byte             `json:"properties"`
	CreatedAtHubspot pgtype.Timestamptz `json:"created_at_hubspot"`
	UpdatedAtHubspot pgtype.Timestamptz `json:"updated_at_hubspot"`
}

// HubSpot CRM Queries
// SQLC queries for HubSpot CRM integration
// ============================================================================
// HubSpot Contacts
// ============================================================================
func (q *Queries) UpsertHubSpotContact(ctx context.Context, arg UpsertHubSpotContactParams) (HubspotContact, error) {
	row := q.db.QueryRow(ctx, upsertHubSpotContact,
		arg.UserID,
		arg.HubspotID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Company,
		arg.JobTitle,
		arg.LifecycleStage,
		arg.LeadStatus,
		arg.OwnerID,
		arg.Properties,
		arg.CreatedAtHubspot,
		arg.UpdatedAtHubspot,
	)
	var i HubspotContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HubspotID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Company,
		&i.JobTitle,
		&i.LifecycleStage,
		&i.LeadStatus,
		&i.OwnerID,
		&i.Properties,
		&i.CreatedAtHubspot,
		&i.UpdatedAtHubspot,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHubSpotDeal = `-- name: UpsertHubSpotDeal :one

INSERT INTO hubspot_deals (
    user_id, hubspot_id, deal_name, amount, pipeline, deal_stage,
    close_date, owner_id, associated_company_ids, associated_contact_ids,
    properties, created_at_hubspot, updated_at_hubspot, synced_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW())
ON CONFLICT (user_id, hubspot_id) DO UPDATE SET
    deal_name = EXCLUDED.deal_name,
    amount = EXCLUDED.amount,
    pipeline = EXCLUDED.pipeline,
    deal_stage = EXCLUDED.deal_stage,
    close_date = EXCLUDED.close_date,
    owner_id = EXCLUDED.owner_id,
    associated_company_ids = EXCLUDED.associated_company_ids,
    associated_contact_ids = EXCLUDED.associated_contact_ids,
    properties = EXCLUDED.properties,
    updated_at_hubspot = EXCLUDED.updated_at_hubspot,
    synced_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, hubspot_id, deal_name, amount, pipeline, deal_stage, close_date, owner_id, associated_company_ids, associated_contact_ids, properties, created_at_hubspot, updated_at_hubspot, synced_at, created_at, updated_at
`

type UpsertHubSpotDealParams struct {
	UserID               string             `json:"user_id"`
	HubspotID            string             `json:"hubspot_id"`
	DealName             *string            `json:"deal_name"`
	Amount               pgtype.Numeric     `json:"amount"`
	Pipeline             *string            `json:"pipeline"`
	DealStage            *string            `json:"deal_stage"`
	CloseDate            pgtype.Date        `json:"close_date"`
	OwnerID              *string            `json:"owner_id"`
	AssociatedCompanyIds []byte             `json:"associated_company_ids"`
	AssociatedContactIds []byte             `json:"associated_contact_ids"`
	Properties           []byte             `json:"properties"`
	CreatedAtHubspot     pgtype.Timestamptz `json:"created_at_hubspot"`
	UpdatedAtHubspot     pgtype.Timestamptz `json:"updated_at_hubspot"`
}

// ============================================================================
// HubSpot Deals
// ============================================================================
func (q *Queries) UpsertHubSpotDeal(ctx context.Context, arg UpsertHubSpotDealParams) (HubspotDeal, error) {
	row := q.db.QueryRow(ctx, upsertHubSpotDeal,
		arg.UserID,
		arg.HubspotID,
		arg.DealName,
		arg.Amount,
		arg.Pipeline,
		arg.DealStage,
		arg.CloseDate,
		arg.OwnerID,
		arg.AssociatedCompanyIds,
		arg.AssociatedContactIds,
		arg.Properties,
		arg.CreatedAtHubspot,
		arg.UpdatedAtHubspot,
	)
	var i HubspotDeal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HubspotID,
		&i.DealName,
		&i.Amount,
		&i.Pipeline,
		&i.DealStage,
		&i.CloseDate,
		&i.OwnerID,
		&i.AssociatedCompanyIds,
		&i.AssociatedContactIds,
		&i.Properties,
		&i.CreatedAtHubspot,
		&i.UpdatedAtHubspot,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
