// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: osa.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOSAWorkspaceModule = `-- name: AddOSAWorkspaceModule :one
UPDATE osa_workspaces
SET active_modules = array_append(active_modules, $2),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, mode, layout, active_modules, template_type, settings, created_at, updated_at, last_accessed_at
`

type AddOSAWorkspaceModuleParams struct {
	ID          pgtype.UUID `json:"id"`
	ArrayAppend interface{} `json:"array_append"`
}

func (q *Queries) AddOSAWorkspaceModule(ctx context.Context, arg AddOSAWorkspaceModuleParams) (OsaWorkspace, error) {
	row := q.db.QueryRow(ctx, addOSAWorkspaceModule, arg.ID, arg.ArrayAppend)
	var i OsaWorkspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Mode,
		&i.Layout,
		&i.ActiveModules,
		&i.TemplateType,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const countOSAGeneratedAppsByUser = `-- name: CountOSAGeneratedAppsByUser :one
SELECT COUNT(DISTINCT a.id)
FROM osa_generated_apps a
JOIN osa_workspaces w ON a.workspace_id = w.id
WHERE w.user_id = $1
    AND ($2::UUID IS NULL OR a.workspace_id = $2)
    AND ($3::TEXT = '' OR a.status = $3)
`

type CountOSAGeneratedAppsByUserParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 pgtype.UUID `json:"column_2"`
	Column3 string      `json:"column_3"`
}

func (q *Queries) CountOSAGeneratedAppsByUser(ctx context.Context, arg CountOSAGeneratedAppsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOSAGeneratedAppsByUser, arg.UserID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOSABuildEvent = `-- name: CreateOSABuildEvent :one

INSERT INTO osa_build_events (
    app_id,
    workspace_id,
    event_type,
    event_data,
    build_id,
    phase,
    progress_percent,
    status_message
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, app_id, workspace_id, event_type, event_data, build_id, phase, progress_percent, status_message, created_at
`

type CreateOSABuildEventParams struct {
	AppID           pgtype.UUID `json:"app_id"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	EventType       string      `json:"event_type"`
	EventData       []byte      `json:"event_data"`
	BuildID         *string     `json:"build_id"`
	Phase           *string     `json:"phase"`
	ProgressPercent *int32      `json:"progress_percent"`
	StatusMessage   *string     `json:"status_message"`
}

// ============================================================================
// OSA BUILD EVENTS
// ============================================================================
func (q *Queries) CreateOSABuildEvent(ctx context.Context, arg CreateOSABuildEventParams) (OsaBuildEvent, error) {
	row := q.db.QueryRow(ctx, createOSABuildEvent,
		arg.AppID,
		arg.WorkspaceID,
		arg.EventType,
		arg.EventData,
		arg.BuildID,
		arg.Phase,
		arg.ProgressPercent,
		arg.StatusMessage,
	)
	var i OsaBuildEvent
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.WorkspaceID,
		&i.EventType,
		&i.EventData,
		&i.BuildID,
		&i.Phase,
		&i.ProgressPercent,
		&i.StatusMessage,
		&i.CreatedAt,
	)
	return i, err
}

const createOSAExecutionHistory = `-- name: CreateOSAExecutionHistory :one

INSERT INTO osa_execution_history (
    user_id,
    app_id,
    workspace_id,
    command,
    working_directory,
    environment_vars,
    output,
    error_output,
    exit_code,
    duration_ms,
    triggered_by,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, user_id, app_id, workspace_id, command, working_directory, environment_vars, output, error_output, exit_code, duration_ms, triggered_by, metadata, created_at
`

type CreateOSAExecutionHistoryParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	AppID            pgtype.UUID `json:"app_id"`
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	Command          string      `json:"command"`
	WorkingDirectory *string     `json:"working_directory"`
	EnvironmentVars  []byte      `json:"environment_vars"`
	Output           *string     `json:"output"`
	ErrorOutput      *string     `json:"error_output"`
	ExitCode         *int32      `json:"exit_code"`
	DurationMs       *int32      `json:"duration_ms"`
	TriggeredBy      *string     `json:"triggered_by"`
	Metadata         []byte      `json:"metadata"`
}

// ============================================================================
// OSA EXECUTION HISTORY
// ============================================================================
func (q *Queries) CreateOSAExecutionHistory(ctx context.Context, arg CreateOSAExecutionHistoryParams) (OsaExecutionHistory, error) {
	row := q.db.QueryRow(ctx, createOSAExecutionHistory,
		arg.UserID,
		arg.AppID,
		arg.WorkspaceID,
		arg.Command,
		arg.WorkingDirectory,
		arg.EnvironmentVars,
		arg.Output,
		arg.ErrorOutput,
		arg.ExitCode,
		arg.DurationMs,
		arg.TriggeredBy,
		arg.Metadata,
	)
	var i OsaExecutionHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppID,
		&i.WorkspaceID,
		&i.Command,
		&i.WorkingDirectory,
		&i.EnvironmentVars,
		&i.Output,
		&i.ErrorOutput,
		&i.ExitCode,
		&i.DurationMs,
		&i.TriggeredBy,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createOSAGeneratedApp = `-- name: CreateOSAGeneratedApp :one

INSERT INTO osa_generated_apps (
    workspace_id,
    module_id,
    name,
    display_name,
    description,
    osa_workflow_id,
    osa_sandbox_id,
    code_repository,
    deployment_url,
    status,
    files_created,
    tests_passed,
    build_status,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, workspace_id, module_id, name, display_name, description, osa_workflow_id, osa_sandbox_id, code_repository, deployment_url, status, files_created, tests_passed, build_status, metadata, error_message, error_stack, created_at, updated_at, generated_at, deployed_at, last_build_at, deployment_port, app_name, category, icon_type, app_description, container_id, sandbox_port, sandbox_url, sandbox_status, container_image, app_type, last_health_check, health_status
`

type CreateOSAGeneratedAppParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	ModuleID       pgtype.UUID `json:"module_id"`
	Name           string      `json:"name"`
	DisplayName    string      `json:"display_name"`
	Description    *string     `json:"description"`
	OsaWorkflowID  *string     `json:"osa_workflow_id"`
	OsaSandboxID   *string     `json:"osa_sandbox_id"`
	CodeRepository *string     `json:"code_repository"`
	DeploymentUrl  *string     `json:"deployment_url"`
	Status         *string     `json:"status"`
	FilesCreated   *int32      `json:"files_created"`
	TestsPassed    *bool       `json:"tests_passed"`
	BuildStatus    *string     `json:"build_status"`
	Metadata       []byte      `json:"metadata"`
}

// ============================================================================
// OSA GENERATED APPS
// ============================================================================
func (q *Queries) CreateOSAGeneratedApp(ctx context.Context, arg CreateOSAGeneratedAppParams) (OsaGeneratedApp, error) {
	row := q.db.QueryRow(ctx, createOSAGeneratedApp,
		arg.WorkspaceID,
		arg.ModuleID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.OsaWorkflowID,
		arg.OsaSandboxID,
		arg.CodeRepository,
		arg.DeploymentUrl,
		arg.Status,
		arg.FilesCreated,
		arg.TestsPassed,
		arg.BuildStatus,
		arg.Metadata,
	)
	var i OsaGeneratedApp
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ModuleID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.OsaWorkflowID,
		&i.OsaSandboxID,
		&i.CodeRepository,
		&i.DeploymentUrl,
		&i.Status,
		&i.FilesCreated,
		&i.TestsPassed,
		&i.BuildStatus,
		&i.Metadata,
		&i.ErrorMessage,
		&i.ErrorStack,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedAt,
		&i.DeployedAt,
		&i.LastBuildAt,
		&i.DeploymentPort,
		&i.AppName,
		&i.Category,
		&i.IconType,
		&i.AppDescription,
		&i.ContainerID,
		&i.SandboxPort,
		&i.SandboxUrl,
		&i.SandboxStatus,
		&i.ContainerImage,
		&i.AppType,
		&i.LastHealthCheck,
		&i.HealthStatus,
	)
	return i, err
}

const createOSAModule = `-- name: CreateOSAModule :one
INSERT INTO osa_modules (
    name,
    display_name,
    description,
    module_type,
    schema_definition,
    api_definition,
    ui_definition,
    created_by,
    workspace_id,
    status,
    version,
    metadata,
    tags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, name, display_name, description, module_type, schema_definition, api_definition, ui_definition, created_by, workspace_id, status, version, metadata, tags, created_at, updated_at, deployed_at
`

type CreateOSAModuleParams struct {
	Name             string      `json:"name"`
	DisplayName      string      `json:"display_name"`
	Description      *string     `json:"description"`
	ModuleType       string      `json:"module_type"`
	SchemaDefinition []byte      `json:"schema_definition"`
	ApiDefinition    []byte      `json:"api_definition"`
	UiDefinition     []byte      `json:"ui_definition"`
	CreatedBy        pgtype.UUID `json:"created_by"`
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	Status           *string     `json:"status"`
	Version          *string     `json:"version"`
	Metadata         []byte      `json:"metadata"`
	Tags             []string    `json:"tags"`
}

func (q *Queries) CreateOSAModule(ctx context.Context, arg CreateOSAModuleParams) (OsaModule, error) {
	row := q.db.QueryRow(ctx, createOSAModule,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.ModuleType,
		arg.SchemaDefinition,
		arg.ApiDefinition,
		arg.UiDefinition,
		arg.CreatedBy,
		arg.WorkspaceID,
		arg.Status,
		arg.Version,
		arg.Metadata,
		arg.Tags,
	)
	var i OsaModule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.ModuleType,
		&i.SchemaDefinition,
		&i.ApiDefinition,
		&i.UiDefinition,
		&i.CreatedBy,
		&i.WorkspaceID,
		&i.Status,
		&i.Version,
		&i.Metadata,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
	)
	return i, err
}

const createOSASyncStatus = `-- name: CreateOSASyncStatus :one

INSERT INTO osa_sync_status (
    entity_type,
    entity_id,
    osa_entity_id,
    osa_entity_type,
    sync_status,
    sync_direction,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (entity_type, entity_id)
DO UPDATE SET
    osa_entity_id = EXCLUDED.osa_entity_id,
    osa_entity_type = EXCLUDED.osa_entity_type,
    sync_status = EXCLUDED.sync_status,
    updated_at = NOW()
RETURNING id, entity_type, entity_id, osa_entity_id, osa_entity_type, sync_status, last_sync_at, next_sync_at, sync_direction, error_count, last_error, local_snapshot, remote_snapshot, metadata, created_at, updated_at
`

type CreateOSASyncStatusParams struct {
	EntityType    string      `json:"entity_type"`
	EntityID      pgtype.UUID `json:"entity_id"`
	OsaEntityID   *string     `json:"osa_entity_id"`
	OsaEntityType *string     `json:"osa_entity_type"`
	SyncStatus    *string     `json:"sync_status"`
	SyncDirection *string     `json:"sync_direction"`
	Metadata      []byte      `json:"metadata"`
}

// ============================================================================
// OSA SYNC STATUS
// ============================================================================
func (q *Queries) CreateOSASyncStatus(ctx context.Context, arg CreateOSASyncStatusParams) (OsaSyncStatus, error) {
	row := q.db.QueryRow(ctx, createOSASyncStatus,
		arg.EntityType,
		arg.EntityID,
		arg.OsaEntityID,
		arg.OsaEntityType,
		arg.SyncStatus,
		arg.SyncDirection,
		arg.Metadata,
	)
	var i OsaSyncStatus
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.OsaEntityID,
		&i.OsaEntityType,
		&i.SyncStatus,
		&i.LastSyncAt,
		&i.NextSyncAt,
		&i.SyncDirection,
		&i.ErrorCount,
		&i.LastError,
		&i.LocalSnapshot,
		&i.RemoteSnapshot,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOSAWebhook = `-- name: CreateOSAWebhook :one

INSERT INTO osa_webhooks (
    workspace_id,
    app_id,
    event_type,
    webhook_url,
    secret_key,
    enabled,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, workspace_id, app_id, event_type, webhook_url, secret_key, enabled, last_triggered_at, success_count, failure_count, metadata, created_at, updated_at
`

type CreateOSAWebhookParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AppID       pgtype.UUID `json:"app_id"`
	EventType   string      `json:"event_type"`
	WebhookUrl  string      `json:"webhook_url"`
	SecretKey   *string     `json:"secret_key"`
	Enabled     *bool       `json:"enabled"`
	Metadata    []byte      `json:"metadata"`
}

// ============================================================================
// OSA WEBHOOKS
// ============================================================================
func (q *Queries) CreateOSAWebhook(ctx context.Context, arg CreateOSAWebhookParams) (OsaWebhook, error) {
	row := q.db.QueryRow(ctx, createOSAWebhook,
		arg.WorkspaceID,
		arg.AppID,
		arg.EventType,
		arg.WebhookUrl,
		arg.SecretKey,
		arg.Enabled,
		arg.Metadata,
	)
	var i OsaWebhook
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AppID,
		&i.EventType,
		&i.WebhookUrl,
		&i.SecretKey,
		&i.Enabled,
		&i.LastTriggeredAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOSAWorkspace = `-- name: CreateOSAWorkspace :one

INSERT INTO osa_workspaces (
    user_id,
    name,
    mode,
    layout,
    active_modules,
    template_type,
    settings
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, name, mode, layout, active_modules, template_type, settings, created_at, updated_at, last_accessed_at
`

type CreateOSAWorkspaceParams struct {
	UserID        pgtype.UUID   `json:"user_id"`
	Name          string        `json:"name"`
	Mode          *string       `json:"mode"`
	Layout        []byte        `json:"layout"`
	ActiveModules []pgtype.UUID `json:"active_modules"`
	TemplateType  *string       `json:"template_type"`
	Settings      []byte        `json:"settings"`
}

// ============================================================================
// OSA WORKSPACES
// ============================================================================
func (q *Queries) CreateOSAWorkspace(ctx context.Context, arg CreateOSAWorkspaceParams) (OsaWorkspace, error) {
	row := q.db.QueryRow(ctx, createOSAWorkspace,
		arg.UserID,
		arg.Name,
		arg.Mode,
		arg.Layout,
		arg.ActiveModules,
		arg.TemplateType,
		arg.Settings,
	)
	var i OsaWorkspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Mode,
		&i.Layout,
		&i.ActiveModules,
		&i.TemplateType,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const deleteOSAGeneratedApp = `-- name: DeleteOSAGeneratedApp :exec
DELETE FROM osa_generated_apps
WHERE id = $1
`

func (q *Queries) DeleteOSAGeneratedApp(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOSAGeneratedApp, id)
	return err
}

const deleteOSAModule = `-- name: DeleteOSAModule :exec
DELETE FROM osa_modules
WHERE id = $1
`

func (q *Queries) DeleteOSAModule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOSAModule, id)
	return err
}

const deleteOSAWebhook = `-- name: DeleteOSAWebhook :exec
DELETE FROM osa_webhooks
WHERE id = $1
`

func (q *Queries) DeleteOSAWebhook(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOSAWebhook, id)
	return err
}

const deleteOSAWorkspace = `-- name: DeleteOSAWorkspace :exec
DELETE FROM osa_workspaces
WHERE id = $1
`

func (q *Queries) DeleteOSAWorkspace(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOSAWorkspace, id)
	return err
}

const getLatestOSABuildEvent = `-- name: GetLatestOSABuildEvent :one
SELECT id, app_id, workspace_id, event_type, event_data, build_id, phase, progress_percent, status_message, created_at FROM osa_build_events
WHERE app_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestOSABuildEvent(ctx context.Context, appID pgtype.UUID) (OsaBuildEvent, error) {
	row := q.db.QueryRow(ctx, getLatestOSABuildEvent, appID)
	var i OsaBuildEvent
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.WorkspaceID,
		&i.EventType,
		&i.EventData,
		&i.BuildID,
		&i.Phase,
		&i.ProgressPercent,
		&i.StatusMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getOSAAppLogs = `-- name: GetOSAAppLogs :many
SELECT id, app_id, workspace_id, event_type, event_data, build_id, phase, progress_percent, status_message, created_at
FROM osa_build_events
WHERE app_id = $1
    AND ($2::TEXT = '' OR event_type = $2)
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type GetOSAAppLogsParams struct {
	AppID   pgtype.UUID `json:"app_id"`
	Column2 string      `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) GetOSAAppLogs(ctx context.Context, arg GetOSAAppLogsParams) ([]OsaBuildEvent, error) {
	rows, err := q.db.Query(ctx, getOSAAppLogs,
		arg.AppID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OsaBuildEvent{}
	for rows.Next() {
		var i OsaBuildEvent
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.WorkspaceID,
			&i.EventType,
			&i.EventData,
			&i.BuildID,
			&i.Phase,
			&i.ProgressPercent,
			&i.StatusMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOSAGeneratedApp = `-- name: GetOSAGeneratedApp :one
SELECT id, workspace_id, module_id, name, display_name, description, osa_workflow_id, osa_sandbox_id, code_repository, deployment_url, status, files_created, tests_passed, build_status, metadata, error_message, error_stack, created_at, updated_at, generated_at, deployed_at, last_build_at, deployment_port, app_name, category, icon_type, app_description, container_id, sandbox_port, sandbox_url, sandbox_status, container_image, app_type, last_health_check, health_status FROM osa_generated_apps
WHERE id = $1
`

func (q *Queries) GetOSAGeneratedApp(ctx context.Context, id pgtype.UUID) (OsaGeneratedApp, error) {
	row := q.db.QueryRow(ctx, getOSAGeneratedApp, id)
	var i OsaGeneratedApp
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ModuleID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.OsaWorkflowID,
		&i.OsaSandboxID,
		&i.CodeRepository,
		&i.DeploymentUrl,
		&i.Status,
		&i.FilesCreated,
		&i.TestsPassed,
		&i.BuildStatus,
		&i.Metadata,
		&i.ErrorMessage,
		&i.ErrorStack,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedAt,
		&i.DeployedAt,
		&i.LastBuildAt,
		&i.DeploymentPort,
		&i.AppName,
		&i.Category,
		&i.IconType,
		&i.AppDescription,
		&i.ContainerID,
		&i.SandboxPort,
		&i.SandboxUrl,
		&i.SandboxStatus,
		&i.ContainerImage,
		&i.AppType,
		&i.LastHealthCheck,
		&i.HealthStatus,
	)
	return i, err
}

const getOSAGeneratedAppByID = `-- name: GetOSAGeneratedAppByID :one
SELECT
    a.id, a.workspace_id, a.module_id, a.name, a.display_name, a.description, a.osa_workflow_id, a.osa_sandbox_id, a.code_repository, a.deployment_url, a.status, a.files_created, a.tests_passed, a.build_status, a.metadata, a.error_message, a.error_stack, a.created_at, a.updated_at, a.generated_at, a.deployed_at, a.last_build_at, a.deployment_port, a.app_name, a.category, a.icon_type, a.app_description, a.container_id, a.sandbox_port, a.sandbox_url, a.sandbox_status, a.container_image, a.app_type, a.last_health_check, a.health_status,
    w.user_id,
    (SELECT COUNT(*) FROM osa_build_events WHERE app_id = a.id) as build_events_count
FROM osa_generated_apps a
JOIN osa_workspaces w ON a.workspace_id = w.id
WHERE a.id = $1
`

type GetOSAGeneratedAppByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ModuleID         pgtype.UUID        `json:"module_id"`
	Name             string             `json:"name"`
	DisplayName      string             `json:"display_name"`
	Description      *string            `json:"description"`
	OsaWorkflowID    *string            `json:"osa_workflow_id"`
	OsaSandboxID     *string            `json:"osa_sandbox_id"`
	CodeRepository   *string            `json:"code_repository"`
	DeploymentUrl    *string            `json:"deployment_url"`
	Status           *string            `json:"status"`
	FilesCreated     *int32             `json:"files_created"`
	TestsPassed      *bool              `json:"tests_passed"`
	BuildStatus      *string            `json:"build_status"`
	Metadata         []byte             `json:"metadata"`
	ErrorMessage     *string            `json:"error_message"`
	ErrorStack       *string            `json:"error_stack"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	GeneratedAt      pgtype.Timestamptz `json:"generated_at"`
	DeployedAt       pgtype.Timestamptz `json:"deployed_at"`
	LastBuildAt      pgtype.Timestamptz `json:"last_build_at"`
	DeploymentPort   *int32             `json:"deployment_port"`
	AppName          *string            `json:"app_name"`
	Category         *string            `json:"category"`
	IconType         *string            `json:"icon_type"`
	AppDescription   *string            `json:"app_description"`
	ContainerID      *string            `json:"container_id"`
	SandboxPort      *int32             `json:"sandbox_port"`
	SandboxUrl       *string            `json:"sandbox_url"`
	SandboxStatus    *string            `json:"sandbox_status"`
	ContainerImage   *string            `json:"container_image"`
	AppType          *string            `json:"app_type"`
	LastHealthCheck  pgtype.Timestamptz `json:"last_health_check"`
	HealthStatus     *string            `json:"health_status"`
	UserID           pgtype.UUID        `json:"user_id"`
	BuildEventsCount int64              `json:"build_events_count"`
}

func (q *Queries) GetOSAGeneratedAppByID(ctx context.Context, id pgtype.UUID) (GetOSAGeneratedAppByIDRow, error) {
	row := q.db.QueryRow(ctx, getOSAGeneratedAppByID, id)
	var i GetOSAGeneratedAppByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ModuleID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.OsaWorkflowID,
		&i.OsaSandboxID,
		&i.CodeRepository,
		&i.DeploymentUrl,
		&i.Status,
		&i.FilesCreated,
		&i.TestsPassed,
		&i.BuildStatus,
		&i.Metadata,
		&i.ErrorMessage,
		&i.ErrorStack,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedAt,
		&i.DeployedAt,
		&i.LastBuildAt,
		&i.DeploymentPort,
		&i.AppName,
		&i.Category,
		&i.IconType,
		&i.AppDescription,
		&i.ContainerID,
		&i.SandboxPort,
		&i.SandboxUrl,
		&i.SandboxStatus,
		&i.ContainerImage,
		&i.AppType,
		&i.LastHealthCheck,
		&i.HealthStatus,
		&i.UserID,
		&i.BuildEventsCount,
	)
	return i, err
}

const getOSAGeneratedAppByIDWithAuth = `-- name: GetOSAGeneratedAppByIDWithAuth :one
SELECT
    a.id, a.workspace_id, a.module_id, a.name, a.display_name, a.description, a.osa_workflow_id, a.osa_sandbox_id, a.code_repository, a.deployment_url, a.status, a.files_created, a.tests_passed, a.build_status, a.metadata, a.error_message, a.error_stack, a.created_at, a.updated_at, a.generated_at, a.deployed_at, a.last_build_at, a.deployment_port, a.app_name, a.category, a.icon_type, a.app_description, a.container_id, a.sandbox_port, a.sandbox_url, a.sandbox_status, a.container_image, a.app_type, a.last_health_check, a.health_status,
    w.user_id
FROM osa_generated_apps a
JOIN osa_workspaces w ON a.workspace_id = w.id
WHERE a.id = $1 AND w.user_id = $2
`

type GetOSAGeneratedAppByIDWithAuthParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetOSAGeneratedAppByIDWithAuthRow struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	ModuleID        pgtype.UUID        `json:"module_id"`
	Name            string             `json:"name"`
	DisplayName     string             `json:"display_name"`
	Description     *string            `json:"description"`
	OsaWorkflowID   *string            `json:"osa_workflow_id"`
	OsaSandboxID    *string            `json:"osa_sandbox_id"`
	CodeRepository  *string            `json:"code_repository"`
	DeploymentUrl   *string            `json:"deployment_url"`
	Status          *string            `json:"status"`
	FilesCreated    *int32             `json:"files_created"`
	TestsPassed     *bool              `json:"tests_passed"`
	BuildStatus     *string            `json:"build_status"`
	Metadata        []byte             `json:"metadata"`
	ErrorMessage    *string            `json:"error_message"`
	ErrorStack      *string            `json:"error_stack"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	GeneratedAt     pgtype.Timestamptz `json:"generated_at"`
	DeployedAt      pgtype.Timestamptz `json:"deployed_at"`
	LastBuildAt     pgtype.Timestamptz `json:"last_build_at"`
	DeploymentPort  *int32             `json:"deployment_port"`
	AppName         *string            `json:"app_name"`
	Category        *string            `json:"category"`
	IconType        *string            `json:"icon_type"`
	AppDescription  *string            `json:"app_description"`
	ContainerID     *string            `json:"container_id"`
	SandboxPort     *int32             `json:"sandbox_port"`
	SandboxUrl      *string            `json:"sandbox_url"`
	SandboxStatus   *string            `json:"sandbox_status"`
	ContainerImage  *string            `json:"container_image"`
	AppType         *string            `json:"app_type"`
	LastHealthCheck pgtype.Timestamptz `json:"last_health_check"`
	HealthStatus    *string            `json:"health_status"`
	UserID          pgtype.UUID        `json:"user_id"`
}

func (q *Queries) GetOSAGeneratedAppByIDWithAuth(ctx context.Context, arg GetOSAGeneratedAppByIDWithAuthParams) (GetOSAGeneratedAppByIDWithAuthRow, error) {
	row := q.db.QueryRow(ctx, getOSAGeneratedAppByIDWithAuth, arg.ID, arg.UserID)
	var i GetOSAGeneratedAppByIDWithAuthRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ModuleID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.OsaWorkflowID,
		&i.OsaSandboxID,
		&i.CodeRepository,
		&i.DeploymentUrl,
		&i.Status,
		&i.FilesCreated,
		&i.TestsPassed,
		&i.BuildStatus,
		&i.Metadata,
		&i.ErrorMessage,
		&i.ErrorStack,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedAt,
		&i.DeployedAt,
		&i.LastBuildAt,
		&i.DeploymentPort,
		&i.AppName,
		&i.Category,
		&i.IconType,
		&i.AppDescription,
		&i.ContainerID,
		&i.SandboxPort,
		&i.SandboxUrl,
		&i.SandboxStatus,
		&i.ContainerImage,
		&i.AppType,
		&i.LastHealthCheck,
		&i.HealthStatus,
		&i.UserID,
	)
	return i, err
}

const getOSAGeneratedAppByWorkflowID = `-- name: GetOSAGeneratedAppByWorkflowID :one
SELECT id, workspace_id, module_id, name, display_name, description, osa_workflow_id, osa_sandbox_id, code_repository, deployment_url, status, files_created, tests_passed, build_status, metadata, error_message, error_stack, created_at, updated_at, generated_at, deployed_at, last_build_at, deployment_port, app_name, category, icon_type, app_description, container_id, sandbox_port, sandbox_url, sandbox_status, container_image, app_type, last_health_check, health_status FROM osa_generated_apps
WHERE osa_workflow_id = $1
`

func (q *Queries) GetOSAGeneratedAppByWorkflowID(ctx context.Context, osaWorkflowID *string) (OsaGeneratedApp, error) {
	row := q.db.QueryRow(ctx, getOSAGeneratedAppByWorkflowID, osaWorkflowID)
	var i OsaGeneratedApp
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ModuleID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.OsaWorkflowID,
		&i.OsaSandboxID,
		&i.CodeRepository,
		&i.DeploymentUrl,
		&i.Status,
		&i.FilesCreated,
		&i.TestsPassed,
		&i.BuildStatus,
		&i.Metadata,
		&i.ErrorMessage,
		&i.ErrorStack,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedAt,
		&i.DeployedAt,
		&i.LastBuildAt,
		&i.DeploymentPort,
		&i.AppName,
		&i.Category,
		&i.IconType,
		&i.AppDescription,
		&i.ContainerID,
		&i.SandboxPort,
		&i.SandboxUrl,
		&i.SandboxStatus,
		&i.ContainerImage,
		&i.AppType,
		&i.LastHealthCheck,
		&i.HealthStatus,
	)
	return i, err
}

const getOSAModule = `-- name: GetOSAModule :one
SELECT id, name, display_name, description, module_type, schema_definition, api_definition, ui_definition, created_by, workspace_id, status, version, metadata, tags, created_at, updated_at, deployed_at FROM osa_modules
WHERE id = $1
`

func (q *Queries) GetOSAModule(ctx context.Context, id pgtype.UUID) (OsaModule, error) {
	row := q.db.QueryRow(ctx, getOSAModule, id)
	var i OsaModule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.ModuleType,
		&i.SchemaDefinition,
		&i.ApiDefinition,
		&i.UiDefinition,
		&i.CreatedBy,
		&i.WorkspaceID,
		&i.Status,
		&i.Version,
		&i.Metadata,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
	)
	return i, err
}

const getOSAModuleByName = `-- name: GetOSAModuleByName :one
SELECT id, name, display_name, description, module_type, schema_definition, api_definition, ui_definition, created_by, workspace_id, status, version, metadata, tags, created_at, updated_at, deployed_at FROM osa_modules
WHERE name = $1 AND workspace_id = $2
`

type GetOSAModuleByNameParams struct {
	Name        string      `json:"name"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetOSAModuleByName(ctx context.Context, arg GetOSAModuleByNameParams) (OsaModule, error) {
	row := q.db.QueryRow(ctx, getOSAModuleByName, arg.Name, arg.WorkspaceID)
	var i OsaModule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.ModuleType,
		&i.SchemaDefinition,
		&i.ApiDefinition,
		&i.UiDefinition,
		&i.CreatedBy,
		&i.WorkspaceID,
		&i.Status,
		&i.Version,
		&i.Metadata,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
	)
	return i, err
}

const getOSASyncStatus = `-- name: GetOSASyncStatus :one
SELECT id, entity_type, entity_id, osa_entity_id, osa_entity_type, sync_status, last_sync_at, next_sync_at, sync_direction, error_count, last_error, local_snapshot, remote_snapshot, metadata, created_at, updated_at FROM osa_sync_status
WHERE entity_type = $1 AND entity_id = $2
`

type GetOSASyncStatusParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

func (q *Queries) GetOSASyncStatus(ctx context.Context, arg GetOSASyncStatusParams) (OsaSyncStatus, error) {
	row := q.db.QueryRow(ctx, getOSASyncStatus, arg.EntityType, arg.EntityID)
	var i OsaSyncStatus
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.OsaEntityID,
		&i.OsaEntityType,
		&i.SyncStatus,
		&i.LastSyncAt,
		&i.NextSyncAt,
		&i.SyncDirection,
		&i.ErrorCount,
		&i.LastError,
		&i.LocalSnapshot,
		&i.RemoteSnapshot,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOSAWebhook = `-- name: GetOSAWebhook :one
SELECT id, workspace_id, app_id, event_type, webhook_url, secret_key, enabled, last_triggered_at, success_count, failure_count, metadata, created_at, updated_at FROM osa_webhooks
WHERE id = $1
`

func (q *Queries) GetOSAWebhook(ctx context.Context, id pgtype.UUID) (OsaWebhook, error) {
	row := q.db.QueryRow(ctx, getOSAWebhook, id)
	var i OsaWebhook
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AppID,
		&i.EventType,
		&i.WebhookUrl,
		&i.SecretKey,
		&i.Enabled,
		&i.LastTriggeredAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOSAWorkspace = `-- name: GetOSAWorkspace :one
SELECT id, user_id, name, mode, layout, active_modules, template_type, settings, created_at, updated_at, last_accessed_at FROM osa_workspaces
WHERE id = $1
`

func (q *Queries) GetOSAWorkspace(ctx context.Context, id pgtype.UUID) (OsaWorkspace, error) {
	row := q.db.QueryRow(ctx, getOSAWorkspace, id)
	var i OsaWorkspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Mode,
		&i.Layout,
		&i.ActiveModules,
		&i.TemplateType,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const getOSAWorkspaceByUserAndName = `-- name: GetOSAWorkspaceByUserAndName :one
SELECT id, user_id, name, mode, layout, active_modules, template_type, settings, created_at, updated_at, last_accessed_at FROM osa_workspaces
WHERE user_id = $1 AND name = $2
`

type GetOSAWorkspaceByUserAndNameParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) GetOSAWorkspaceByUserAndName(ctx context.Context, arg GetOSAWorkspaceByUserAndNameParams) (OsaWorkspace, error) {
	row := q.db.QueryRow(ctx, getOSAWorkspaceByUserAndName, arg.UserID, arg.Name)
	var i OsaWorkspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Mode,
		&i.Layout,
		&i.ActiveModules,
		&i.TemplateType,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const incrementOSAWebhookFailure = `-- name: IncrementOSAWebhookFailure :exec
UPDATE osa_webhooks
SET failure_count = failure_count + 1,
    last_triggered_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementOSAWebhookFailure(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOSAWebhookFailure, id)
	return err
}

const incrementOSAWebhookSuccess = `-- name: IncrementOSAWebhookSuccess :exec
UPDATE osa_webhooks
SET success_count = success_count + 1,
    last_triggered_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementOSAWebhookSuccess(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOSAWebhookSuccess, id)
	return err
}

const listActiveOSAWebhooksByEvent = `-- name: ListActiveOSAWebhooksByEvent :many
SELECT id, workspace_id, app_id, event_type, webhook_url, secret_key, enabled, last_triggered_at, success_count, failure_count, metadata, created_at, updated_at FROM osa_webhooks
WHERE event_type = $1 AND enabled = true
`

func (q *Queries) ListActiveOSAWebhooksByEvent(ctx context.Context, eventType string) ([]OsaWebhook, error) {
	rows, err := q.db.Query(ctx, listActiveOSAWebhooksByEvent, eventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OsaWebhook{}
	for rows.Next() {
		var i OsaWebhook
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AppID,
			&i.EventType,
			&i.WebhookUrl,
			&i.SecretKey,
			&i.Enabled,
			&i.LastTriggeredAt,
			&i.SuccessCount,
			&i.FailureCount,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOSAAppSnapshots = `-- name: ListOSAAppSnapshots :many
SELECT a.id, a.name, a.display_name, a.status, a.files_created,
       a.created_at, a.generated_at,
       (SELECT COUNT(*) FROM osa_generated_files f WHERE f.app_id = a.id) as file_count
FROM osa_generated_apps a
WHERE a.workspace_id = (SELECT ws.workspace_id FROM osa_generated_apps ws WHERE ws.id = $1)
  AND a.name = (SELECT n.name FROM osa_generated_apps n WHERE n.id = $1)
ORDER BY a.created_at DESC
`

type ListOSAAppSnapshotsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	DisplayName  string             `json:"display_name"`
	Status       *string            `json:"status"`
	FilesCreated *int32             `json:"files_created"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	GeneratedAt  pgtype.Timestamptz `json:"generated_at"`
	FileCount    int64              `json:"file_count"`
}

// Returns all generation snapshots for apps with the same name in the same workspace
func (q *Queries) ListOSAAppSnapshots(ctx context.Context, id pgtype.UUID) ([]ListOSAAppSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listOSAAppSnapshots, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOSAAppSnapshotsRow{}
	for rows.Next() {
		var i ListOSAAppSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Status,
			&i.FilesCreated,
			&i.CreatedAt,
			&i.GeneratedAt,
			&i.FileCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOSABuildEvents = `-- name: ListOSABuildEvents :many
SELECT id, app_id, workspace_id, event_type, event_data, build_id, phase, progress_percent, status_message, created_at FROM osa_build_events
WHERE app_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListOSABuildEventsParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Limit int32       `json:"limit"`
}

func (q *Queries) ListOSABuildEvents(ctx context.Context, arg ListOSABuildEventsParams) ([]OsaBuildEvent, error) {
	rows, err := q.db.Query(ctx, listOSABuildEvents, arg.AppID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OsaBuildEvent{}
	for rows.Next() {
		var i OsaBuildEvent
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.WorkspaceID,
			&i.EventType,
			&i.EventData,
			&i.BuildID,
			&i.Phase,
			&i.ProgressPercent,
			&i.StatusMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOSABuildEventsByBuildID = `-- name: ListOSABuildEventsByBuildID :many
SELECT id, app_id, workspace_id, event_type, event_data, build_id, phase, progress_percent, status_message, created_at FROM osa_build_events
WHERE build_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOSABuildEventsByBuildID(ctx context.Context, buildID *string) ([]OsaBuildEvent, error) {
	rows, err := q.db.Query(ctx, listOSABuildEventsByBuildID, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OsaBuildEvent{}
	for rows.Next() {
		var i OsaBuildEvent
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.WorkspaceID,
			&i.EventType,
			&i.EventData,
			&i.BuildID,
			&i.Phase,
			&i.ProgressPercent,
			&i.StatusMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOSAExecutionHistory = `-- name: ListOSAExecutionHistory :many
SELECT id, user_id, app_id, workspace_id, command, working_directory, environment_vars, output, error_output, exit_code, duration_ms, triggered_by, metadata, created_at FROM osa_execution_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListOSAExecutionHistoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListOSAExecutionHistory(ctx context.Context, arg ListOSAExecutionHistoryParams) ([]OsaExecutionHistory, error) {
	rows, err := q.db.Query(ctx, listOSAExecutionHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OsaExecutionHistory{}
	for rows.Next() {
		var i OsaExecutionHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppID,
			&i.WorkspaceID,
			&i.Command,
			&i.WorkingDirectory,
			&i.EnvironmentVars,
			&i.Output,
			&i.ErrorOutput,
			&i.ExitCode,
			&i.DurationMs,
			&i.TriggeredBy,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOSAExecutionHistoryByApp = `-- name: ListOSAExecutionHistoryByApp :many
SELECT id, user_id, app_id, workspace_id, command, working_directory, environment_vars, output, error_output, exit_code, duration_ms, triggered_by, metadata, created_at FROM osa_execution_history
WHERE app_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListOSAExecutionHistoryByAppParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Limit int32       `json:"limit"`
}

func (q *Queries) ListOSAExecutionHistoryByApp(ctx context.Context, arg ListOSAExecutionHistoryByAppParams) ([]OsaExecutionHistory, error) {
	rows, err := q.db.Query(ctx, listOSAExecutionHistoryByApp, arg.AppID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OsaExecutionHistory{}
	for rows.Next() {
		var i OsaExecutionHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppID,
			&i.WorkspaceID,
			&i.Command,
			&i.WorkingDirectory,
			&i.EnvironmentVars,
			&i.Output,
			&i.ErrorOutput,
			&i.ExitCode,
			&i.DurationMs,
			&i.TriggeredBy,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOSAGeneratedAppsByUser = `-- name: ListOSAGeneratedAppsByUser :many

SELECT
    a.id, a.workspace_id, a.module_id, a.name, a.display_name, a.description, a.osa_workflow_id, a.osa_sandbox_id, a.code_repository, a.deployment_url, a.status, a.files_created, a.tests_passed, a.build_status, a.metadata, a.error_message, a.error_stack, a.created_at, a.updated_at, a.generated_at, a.deployed_at, a.last_build_at, a.deployment_port, a.app_name, a.category, a.icon_type, a.app_description, a.container_id, a.sandbox_port, a.sandbox_url, a.sandbox_status, a.container_image, a.app_type, a.last_health_check, a.health_status,
    w.user_id,
    (SELECT COUNT(*) FROM osa_build_events WHERE app_id = a.id) as build_events_count
FROM osa_generated_apps a
JOIN osa_workspaces w ON a.workspace_id = w.id
WHERE w.user_id = $1
    AND ($2::UUID IS NULL OR a.workspace_id = $2)
    AND ($3::TEXT = '' OR a.status = $3)
ORDER BY a.created_at DESC
LIMIT $4
OFFSET $5
`

type ListOSAGeneratedAppsByUserParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 pgtype.UUID `json:"column_2"`
	Column3 string      `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListOSAGeneratedAppsByUserRow struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ModuleID         pgtype.UUID        `json:"module_id"`
	Name             string             `json:"name"`
	DisplayName      string             `json:"display_name"`
	Description      *string            `json:"description"`
	OsaWorkflowID    *string            `json:"osa_workflow_id"`
	OsaSandboxID     *string            `json:"osa_sandbox_id"`
	CodeRepository   *string            `json:"code_repository"`
	DeploymentUrl    *string            `json:"deployment_url"`
	Status           *string            `json:"status"`
	FilesCreated     *int32             `json:"files_created"`
	TestsPassed      *bool              `json:"tests_passed"`
	BuildStatus      *string            `json:"build_status"`
	Metadata         []byte             `json:"metadata"`
	ErrorMessage     *string            `json:"error_message"`
	ErrorStack       *string            `json:"error_stack"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	GeneratedAt      pgtype.Timestamptz `json:"generated_at"`
	DeployedAt       pgtype.Timestamptz `json:"deployed_at"`
	LastBuildAt      pgtype.Timestamptz `json:"last_build_at"`
	DeploymentPort   *int32             `json:"deployment_port"`
	AppName          *string            `json:"app_name"`
	Category         *string            `json:"category"`
	IconType         *string            `json:"icon_type"`
	AppDescription   *string            `json:"app_description"`
	ContainerID      *string            `json:"container_id"`
	SandboxPort      *int32             `json:"sandbox_port"`
	SandboxUrl       *string            `json:"sandbox_url"`
	SandboxStatus    *string            `json:"sandbox_status"`
	ContainerImage   *string            `json:"container_image"`
	AppType          *string            `json:"app_type"`
	LastHealthCheck  pgtype.Timestamptz `json:"last_health_check"`
	HealthStatus     *string            `json:"health_status"`
	UserID           pgtype.UUID        `json:"user_id"`
	BuildEventsCount int64              `json:"build_events_count"`
}

// ============================================================================
// OSA APP MANAGEMENT (ISR-4)
// ============================================================================
func (q *Queries) ListOSAGeneratedAppsByUser(ctx context.Context, arg ListOSAGeneratedAppsByUserParams) ([]ListOSAGeneratedAppsByUserRow, error) {
	rows, err := q.db.Query(ctx, listOSAGeneratedAppsByUser,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOSAGeneratedAppsByUserRow{}
	for rows.Next() {
		var i ListOSAGeneratedAppsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ModuleID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.OsaWorkflowID,
			&i.OsaSandboxID,
			&i.CodeRepository,
			&i.DeploymentUrl,
			&i.Status,
			&i.FilesCreated,
			&i.TestsPassed,
			&i.BuildStatus,
			&i.Metadata,
			&i.ErrorMessage,
			&i.ErrorStack,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GeneratedAt,
			&i.DeployedAt,
			&i.LastBuildAt,
			&i.DeploymentPort,
			&i.AppName,
			&i.Category,
			&i.IconType,
			&i.AppDescription,
			&i.ContainerID,
			&i.SandboxPort,
			&i.SandboxUrl,
			&i.SandboxStatus,
			&i.ContainerImage,
			&i.AppType,
			&i.LastHealthCheck,
			&i.HealthStatus,
			&i.UserID,
			&i.BuildEventsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOSAGeneratedAppsByWorkspace = `-- name: ListOSAGeneratedAppsByWorkspace :many
SELECT id, workspace_id, module_id, name, display_name, description, osa_workflow_id, osa_sandbox_id, code_repository, deployment_url, status, files_created, tests_passed, build_status, metadata, error_message, error_stack, created_at, updated_at, generated_at, deployed_at, last_build_at, deployment_port, app_name, category, icon_type, app_description, container_id, sandbox_port, sandbox_url, sandbox_status, container_image, app_type, last_health_check, health_status FROM osa_generated_apps
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOSAGeneratedAppsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]OsaGeneratedApp, error) {
	rows, err := q.db.Query(ctx, listOSAGeneratedAppsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OsaGeneratedApp{}
	for rows.Next() {
		var i OsaGeneratedApp
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ModuleID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.OsaWorkflowID,
			&i.OsaSandboxID,
			&i.CodeRepository,
			&i.DeploymentUrl,
			&i.Status,
			&i.FilesCreated,
			&i.TestsPassed,
			&i.BuildStatus,
			&i.Metadata,
			&i.ErrorMessage,
			&i.ErrorStack,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GeneratedAt,
			&i.DeployedAt,
			&i.LastBuildAt,
			&i.DeploymentPort,
			&i.AppName,
			&i.Category,
			&i.IconType,
			&i.AppDescription,
			&i.ContainerID,
			&i.SandboxPort,
			&i.SandboxUrl,
			&i.SandboxStatus,
			&i.ContainerImage,
			&i.AppType,
			&i.LastHealthCheck,
			&i.HealthStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOSAModules = `-- name: ListOSAModules :many
SELECT id, name, display_name, description, module_type, schema_definition, api_definition, ui_definition, created_by, workspace_id, status, version, metadata, tags, created_at, updated_at, deployed_at FROM osa_modules
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOSAModules(ctx context.Context, workspaceID pgtype.UUID) ([]OsaModule, error) {
	rows, err := q.db.Query(ctx, listOSAModules, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OsaModule{}
	for rows.Next() {
		var i OsaModule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.ModuleType,
			&i.SchemaDefinition,
			&i.ApiDefinition,
			&i.UiDefinition,
			&i.CreatedBy,
			&i.WorkspaceID,
			&i.Status,
			&i.Version,
			&i.Metadata,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeployedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOSAModulesByUser = `-- name: ListOSAModulesByUser :many
SELECT id, name, display_name, description, module_type, schema_definition, api_definition, ui_definition, created_by, workspace_id, status, version, metadata, tags, created_at, updated_at, deployed_at FROM osa_modules
WHERE created_by = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOSAModulesByUser(ctx context.Context, createdBy pgtype.UUID) ([]OsaModule, error) {
	rows, err := q.db.Query(ctx, listOSAModulesByUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OsaModule{}
	for rows.Next() {
		var i OsaModule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.ModuleType,
			&i.SchemaDefinition,
			&i.ApiDefinition,
			&i.UiDefinition,
			&i.CreatedBy,
			&i.WorkspaceID,
			&i.Status,
			&i.Version,
			&i.Metadata,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeployedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOSAWebhooksByWorkspace = `-- name: ListOSAWebhooksByWorkspace :many
SELECT id, workspace_id, app_id, event_type, webhook_url, secret_key, enabled, last_triggered_at, success_count, failure_count, metadata, created_at, updated_at FROM osa_webhooks
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOSAWebhooksByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]OsaWebhook, error) {
	rows, err := q.db.Query(ctx, listOSAWebhooksByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OsaWebhook{}
	for rows.Next() {
		var i OsaWebhook
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AppID,
			&i.EventType,
			&i.WebhookUrl,
			&i.SecretKey,
			&i.Enabled,
			&i.LastTriggeredAt,
			&i.SuccessCount,
			&i.FailureCount,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOSAWorkspacesByUser = `-- name: ListOSAWorkspacesByUser :many
SELECT id, user_id, name, mode, layout, active_modules, template_type, settings, created_at, updated_at, last_accessed_at FROM osa_workspaces
WHERE user_id = $1
ORDER BY last_accessed_at DESC
`

func (q *Queries) ListOSAWorkspacesByUser(ctx context.Context, userID pgtype.UUID) ([]OsaWorkspace, error) {
	rows, err := q.db.Query(ctx, listOSAWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OsaWorkspace{}
	for rows.Next() {
		var i OsaWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Mode,
			&i.Layout,
			&i.ActiveModules,
			&i.TemplateType,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOSASyncs = `-- name: ListPendingOSASyncs :many
SELECT id, entity_type, entity_id, osa_entity_id, osa_entity_type, sync_status, last_sync_at, next_sync_at, sync_direction, error_count, last_error, local_snapshot, remote_snapshot, metadata, created_at, updated_at FROM osa_sync_status
WHERE sync_status IN ('pending', 'failed')
  AND (next_sync_at IS NULL OR next_sync_at <= NOW())
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingOSASyncs(ctx context.Context, limit int32) ([]OsaSyncStatus, error) {
	rows, err := q.db.Query(ctx, listPendingOSASyncs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OsaSyncStatus{}
	for rows.Next() {
		var i OsaSyncStatus
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.OsaEntityID,
			&i.OsaEntityType,
			&i.SyncStatus,
			&i.LastSyncAt,
			&i.NextSyncAt,
			&i.SyncDirection,
			&i.ErrorCount,
			&i.LastError,
			&i.LocalSnapshot,
			&i.RemoteSnapshot,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOSAGeneratedAppBuildStatus = `-- name: UpdateOSAGeneratedAppBuildStatus :one
UPDATE osa_generated_apps
SET build_status = $2,
    tests_passed = $3,
    files_created = $4,
    last_build_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, module_id, name, display_name, description, osa_workflow_id, osa_sandbox_id, code_repository, deployment_url, status, files_created, tests_passed, build_status, metadata, error_message, error_stack, created_at, updated_at, generated_at, deployed_at, last_build_at, deployment_port, app_name, category, icon_type, app_description, container_id, sandbox_port, sandbox_url, sandbox_status, container_image, app_type, last_health_check, health_status
`

type UpdateOSAGeneratedAppBuildStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	BuildStatus  *string     `json:"build_status"`
	TestsPassed  *bool       `json:"tests_passed"`
	FilesCreated *int32      `json:"files_created"`
}

func (q *Queries) UpdateOSAGeneratedAppBuildStatus(ctx context.Context, arg UpdateOSAGeneratedAppBuildStatusParams) (OsaGeneratedApp, error) {
	row := q.db.QueryRow(ctx, updateOSAGeneratedAppBuildStatus,
		arg.ID,
		arg.BuildStatus,
		arg.TestsPassed,
		arg.FilesCreated,
	)
	var i OsaGeneratedApp
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ModuleID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.OsaWorkflowID,
		&i.OsaSandboxID,
		&i.CodeRepository,
		&i.DeploymentUrl,
		&i.Status,
		&i.FilesCreated,
		&i.TestsPassed,
		&i.BuildStatus,
		&i.Metadata,
		&i.ErrorMessage,
		&i.ErrorStack,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedAt,
		&i.DeployedAt,
		&i.LastBuildAt,
		&i.DeploymentPort,
		&i.AppName,
		&i.Category,
		&i.IconType,
		&i.AppDescription,
		&i.ContainerID,
		&i.SandboxPort,
		&i.SandboxUrl,
		&i.SandboxStatus,
		&i.ContainerImage,
		&i.AppType,
		&i.LastHealthCheck,
		&i.HealthStatus,
	)
	return i, err
}

const updateOSAGeneratedAppMetadata = `-- name: UpdateOSAGeneratedAppMetadata :one
UPDATE osa_generated_apps
SET
    display_name = COALESCE($2, display_name),
    description = COALESCE($3, description),
    metadata = COALESCE($4, metadata),
    updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, module_id, name, display_name, description, osa_workflow_id, osa_sandbox_id, code_repository, deployment_url, status, files_created, tests_passed, build_status, metadata, error_message, error_stack, created_at, updated_at, generated_at, deployed_at, last_build_at, deployment_port, app_name, category, icon_type, app_description, container_id, sandbox_port, sandbox_url, sandbox_status, container_image, app_type, last_health_check, health_status
`

type UpdateOSAGeneratedAppMetadataParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	Description *string     `json:"description"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpdateOSAGeneratedAppMetadata(ctx context.Context, arg UpdateOSAGeneratedAppMetadataParams) (OsaGeneratedApp, error) {
	row := q.db.QueryRow(ctx, updateOSAGeneratedAppMetadata,
		arg.ID,
		arg.DisplayName,
		arg.Description,
		arg.Metadata,
	)
	var i OsaGeneratedApp
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ModuleID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.OsaWorkflowID,
		&i.OsaSandboxID,
		&i.CodeRepository,
		&i.DeploymentUrl,
		&i.Status,
		&i.FilesCreated,
		&i.TestsPassed,
		&i.BuildStatus,
		&i.Metadata,
		&i.ErrorMessage,
		&i.ErrorStack,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedAt,
		&i.DeployedAt,
		&i.LastBuildAt,
		&i.DeploymentPort,
		&i.AppName,
		&i.Category,
		&i.IconType,
		&i.AppDescription,
		&i.ContainerID,
		&i.SandboxPort,
		&i.SandboxUrl,
		&i.SandboxStatus,
		&i.ContainerImage,
		&i.AppType,
		&i.LastHealthCheck,
		&i.HealthStatus,
	)
	return i, err
}

const updateOSAGeneratedAppStatus = `-- name: UpdateOSAGeneratedAppStatus :one
UPDATE osa_generated_apps
SET status = $2,
    error_message = $3,
    deployment_url = COALESCE($4, deployment_url),
    generated_at = CASE WHEN $2 = 'generated' THEN NOW() ELSE generated_at END,
    deployed_at = CASE WHEN $2 = 'deployed' THEN NOW() ELSE deployed_at END
WHERE id = $1
RETURNING id, workspace_id, module_id, name, display_name, description, osa_workflow_id, osa_sandbox_id, code_repository, deployment_url, status, files_created, tests_passed, build_status, metadata, error_message, error_stack, created_at, updated_at, generated_at, deployed_at, last_build_at, deployment_port, app_name, category, icon_type, app_description, container_id, sandbox_port, sandbox_url, sandbox_status, container_image, app_type, last_health_check, health_status
`

type UpdateOSAGeneratedAppStatusParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        *string     `json:"status"`
	ErrorMessage  *string     `json:"error_message"`
	DeploymentUrl *string     `json:"deployment_url"`
}

func (q *Queries) UpdateOSAGeneratedAppStatus(ctx context.Context, arg UpdateOSAGeneratedAppStatusParams) (OsaGeneratedApp, error) {
	row := q.db.QueryRow(ctx, updateOSAGeneratedAppStatus,
		arg.ID,
		arg.Status,
		arg.ErrorMessage,
		arg.DeploymentUrl,
	)
	var i OsaGeneratedApp
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ModuleID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.OsaWorkflowID,
		&i.OsaSandboxID,
		&i.CodeRepository,
		&i.DeploymentUrl,
		&i.Status,
		&i.FilesCreated,
		&i.TestsPassed,
		&i.BuildStatus,
		&i.Metadata,
		&i.ErrorMessage,
		&i.ErrorStack,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedAt,
		&i.DeployedAt,
		&i.LastBuildAt,
		&i.DeploymentPort,
		&i.AppName,
		&i.Category,
		&i.IconType,
		&i.AppDescription,
		&i.ContainerID,
		&i.SandboxPort,
		&i.SandboxUrl,
		&i.SandboxStatus,
		&i.ContainerImage,
		&i.AppType,
		&i.LastHealthCheck,
		&i.HealthStatus,
	)
	return i, err
}

const updateOSAModuleStatus = `-- name: UpdateOSAModuleStatus :one
UPDATE osa_modules
SET status = $2,
    deployed_at = CASE WHEN $2 = 'active' THEN NOW() ELSE deployed_at END
WHERE id = $1
RETURNING id, name, display_name, description, module_type, schema_definition, api_definition, ui_definition, created_by, workspace_id, status, version, metadata, tags, created_at, updated_at, deployed_at
`

type UpdateOSAModuleStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status *string     `json:"status"`
}

func (q *Queries) UpdateOSAModuleStatus(ctx context.Context, arg UpdateOSAModuleStatusParams) (OsaModule, error) {
	row := q.db.QueryRow(ctx, updateOSAModuleStatus, arg.ID, arg.Status)
	var i OsaModule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.ModuleType,
		&i.SchemaDefinition,
		&i.ApiDefinition,
		&i.UiDefinition,
		&i.CreatedBy,
		&i.WorkspaceID,
		&i.Status,
		&i.Version,
		&i.Metadata,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
	)
	return i, err
}

const updateOSASyncStatus = `-- name: UpdateOSASyncStatus :one
UPDATE osa_sync_status
SET sync_status = $2,
    last_sync_at = NOW(),
    error_count = CASE WHEN $2 = 'failed' THEN error_count + 1 ELSE 0 END,
    last_error = $3
WHERE entity_type = $1 AND entity_id = $4
RETURNING id, entity_type, entity_id, osa_entity_id, osa_entity_type, sync_status, last_sync_at, next_sync_at, sync_direction, error_count, last_error, local_snapshot, remote_snapshot, metadata, created_at, updated_at
`

type UpdateOSASyncStatusParams struct {
	EntityType string      `json:"entity_type"`
	SyncStatus *string     `json:"sync_status"`
	LastError  *string     `json:"last_error"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

func (q *Queries) UpdateOSASyncStatus(ctx context.Context, arg UpdateOSASyncStatusParams) (OsaSyncStatus, error) {
	row := q.db.QueryRow(ctx, updateOSASyncStatus,
		arg.EntityType,
		arg.SyncStatus,
		arg.LastError,
		arg.EntityID,
	)
	var i OsaSyncStatus
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.OsaEntityID,
		&i.OsaEntityType,
		&i.SyncStatus,
		&i.LastSyncAt,
		&i.NextSyncAt,
		&i.SyncDirection,
		&i.ErrorCount,
		&i.LastError,
		&i.LocalSnapshot,
		&i.RemoteSnapshot,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOSAWebhookStatus = `-- name: UpdateOSAWebhookStatus :one
UPDATE osa_webhooks
SET enabled = $2
WHERE id = $1
RETURNING id, workspace_id, app_id, event_type, webhook_url, secret_key, enabled, last_triggered_at, success_count, failure_count, metadata, created_at, updated_at
`

type UpdateOSAWebhookStatusParams struct {
	ID      pgtype.UUID `json:"id"`
	Enabled *bool       `json:"enabled"`
}

func (q *Queries) UpdateOSAWebhookStatus(ctx context.Context, arg UpdateOSAWebhookStatusParams) (OsaWebhook, error) {
	row := q.db.QueryRow(ctx, updateOSAWebhookStatus, arg.ID, arg.Enabled)
	var i OsaWebhook
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AppID,
		&i.EventType,
		&i.WebhookUrl,
		&i.SecretKey,
		&i.Enabled,
		&i.LastTriggeredAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOSAWorkspaceLayout = `-- name: UpdateOSAWorkspaceLayout :one
UPDATE osa_workspaces
SET layout = $2,
    active_modules = $3,
    last_accessed_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, mode, layout, active_modules, template_type, settings, created_at, updated_at, last_accessed_at
`

type UpdateOSAWorkspaceLayoutParams struct {
	ID            pgtype.UUID   `json:"id"`
	Layout        []byte        `json:"layout"`
	ActiveModules []pgtype.UUID `json:"active_modules"`
}

func (q *Queries) UpdateOSAWorkspaceLayout(ctx context.Context, arg UpdateOSAWorkspaceLayoutParams) (OsaWorkspace, error) {
	row := q.db.QueryRow(ctx, updateOSAWorkspaceLayout, arg.ID, arg.Layout, arg.ActiveModules)
	var i OsaWorkspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Mode,
		&i.Layout,
		&i.ActiveModules,
		&i.TemplateType,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const updateOSAWorkspaceMode = `-- name: UpdateOSAWorkspaceMode :one
UPDATE osa_workspaces
SET mode = $2,
    last_accessed_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, mode, layout, active_modules, template_type, settings, created_at, updated_at, last_accessed_at
`

type UpdateOSAWorkspaceModeParams struct {
	ID   pgtype.UUID `json:"id"`
	Mode *string     `json:"mode"`
}

func (q *Queries) UpdateOSAWorkspaceMode(ctx context.Context, arg UpdateOSAWorkspaceModeParams) (OsaWorkspace, error) {
	row := q.db.QueryRow(ctx, updateOSAWorkspaceMode, arg.ID, arg.Mode)
	var i OsaWorkspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Mode,
		&i.Layout,
		&i.ActiveModules,
		&i.TemplateType,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}
