// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_statuses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTasksByProjectStatus = `-- name: CountTasksByProjectStatus :many
SELECT ps.id, ps.name, ps.color, ps.position, ps.is_done_state, ps.is_default,
  COUNT(t.id)::int AS task_count
FROM project_statuses ps
LEFT JOIN tasks t ON t.custom_status_id = ps.id
WHERE ps.project_id = $1
GROUP BY ps.id, ps.name, ps.color, ps.position, ps.is_done_state, ps.is_default
ORDER BY ps.position ASC
`

type CountTasksByProjectStatusRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Color       *string     `json:"color"`
	Position    *int32      `json:"position"`
	IsDoneState *bool       `json:"is_done_state"`
	IsDefault   *bool       `json:"is_default"`
	TaskCount   int32       `json:"task_count"`
}

// Returns task counts for each status in a project
func (q *Queries) CountTasksByProjectStatus(ctx context.Context, projectID pgtype.UUID) ([]CountTasksByProjectStatusRow, error) {
	rows, err := q.db.Query(ctx, countTasksByProjectStatus, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTasksByProjectStatusRow{}
	for rows.Next() {
		var i CountTasksByProjectStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.IsDoneState,
			&i.IsDefault,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDefaultStatusesForProject = `-- name: CreateDefaultStatusesForProject :exec
INSERT INTO project_statuses (project_id, name, color, position, is_done_state, is_default)
VALUES
    ($1, 'To Do', '#6B7280', 0, FALSE, TRUE),
    ($1, 'In Progress', '#3B82F6', 1, FALSE, FALSE),
    ($1, 'In Review', '#8B5CF6', 2, FALSE, FALSE),
    ($1, 'Done', '#10B981', 3, TRUE, FALSE),
    ($1, 'Blocked', '#F59E0B', 4, FALSE, FALSE)
ON CONFLICT (project_id, name) DO NOTHING
`

// Creates the default set of statuses for a project
func (q *Queries) CreateDefaultStatusesForProject(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, createDefaultStatusesForProject, projectID)
	return err
}

const createProjectStatus = `-- name: CreateProjectStatus :one
INSERT INTO project_statuses (project_id, name, color, position, is_done_state, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, color, position, is_done_state, is_default, created_at, updated_at
`

type CreateProjectStatusParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Name        string      `json:"name"`
	Color       *string     `json:"color"`
	Position    *int32      `json:"position"`
	IsDoneState *bool       `json:"is_done_state"`
	IsDefault   *bool       `json:"is_default"`
}

func (q *Queries) CreateProjectStatus(ctx context.Context, arg CreateProjectStatusParams) (ProjectStatus, error) {
	row := q.db.QueryRow(ctx, createProjectStatus,
		arg.ProjectID,
		arg.Name,
		arg.Color,
		arg.Position,
		arg.IsDoneState,
		arg.IsDefault,
	)
	var i ProjectStatus
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDoneState,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectStatusAutoPosition = `-- name: CreateProjectStatusAutoPosition :one
INSERT INTO project_statuses (project_id, name, color, is_done_state, is_default, position)
SELECT $1, $2, $3, $4, $5,
  COALESCE((SELECT MAX(position) + 1 FROM project_statuses WHERE project_id = $1), 0)
RETURNING id, project_id, name, color, position, is_done_state, is_default, created_at, updated_at
`

type CreateProjectStatusAutoPositionParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Name        string      `json:"name"`
	Color       *string     `json:"color"`
	IsDoneState *bool       `json:"is_done_state"`
	IsDefault   *bool       `json:"is_default"`
}

// Creates a status with automatic position assignment
func (q *Queries) CreateProjectStatusAutoPosition(ctx context.Context, arg CreateProjectStatusAutoPositionParams) (ProjectStatus, error) {
	row := q.db.QueryRow(ctx, createProjectStatusAutoPosition,
		arg.ProjectID,
		arg.Name,
		arg.Color,
		arg.IsDoneState,
		arg.IsDefault,
	)
	var i ProjectStatus
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDoneState,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectStatus = `-- name: DeleteProjectStatus :exec
DELETE FROM project_statuses
WHERE id = $1
`

func (q *Queries) DeleteProjectStatus(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectStatus, id)
	return err
}

const deleteProjectStatusWithFallback = `-- name: DeleteProjectStatusWithFallback :exec
WITH default_status AS (
  SELECT ps.id FROM project_statuses ps
  WHERE ps.project_id = (SELECT sub.project_id FROM project_statuses sub WHERE sub.id = $1)
    AND ps.is_default = TRUE
  LIMIT 1
)
UPDATE tasks
SET custom_status_id = (SELECT ds.id FROM default_status ds), updated_at = NOW()
WHERE custom_status_id = $1
`

// Deletes a status and moves tasks to the default status
// First, update any tasks using this status to use the default status
func (q *Queries) DeleteProjectStatusWithFallback(ctx context.Context, customStatusID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectStatusWithFallback, customStatusID)
	return err
}

const getDefaultProjectStatus = `-- name: GetDefaultProjectStatus :one
SELECT id, project_id, name, color, position, is_done_state, is_default, created_at, updated_at FROM project_statuses
WHERE project_id = $1 AND is_default = TRUE
LIMIT 1
`

func (q *Queries) GetDefaultProjectStatus(ctx context.Context, projectID pgtype.UUID) (ProjectStatus, error) {
	row := q.db.QueryRow(ctx, getDefaultProjectStatus, projectID)
	var i ProjectStatus
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDoneState,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDoneProjectStatus = `-- name: GetDoneProjectStatus :one
SELECT id, project_id, name, color, position, is_done_state, is_default, created_at, updated_at FROM project_statuses
WHERE project_id = $1 AND is_done_state = TRUE
LIMIT 1
`

func (q *Queries) GetDoneProjectStatus(ctx context.Context, projectID pgtype.UUID) (ProjectStatus, error) {
	row := q.db.QueryRow(ctx, getDoneProjectStatus, projectID)
	var i ProjectStatus
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDoneState,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectStatus = `-- name: GetProjectStatus :one
SELECT id, project_id, name, color, position, is_done_state, is_default, created_at, updated_at FROM project_statuses
WHERE id = $1
`

func (q *Queries) GetProjectStatus(ctx context.Context, id pgtype.UUID) (ProjectStatus, error) {
	row := q.db.QueryRow(ctx, getProjectStatus, id)
	var i ProjectStatus
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDoneState,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectStatusByName = `-- name: GetProjectStatusByName :one
SELECT id, project_id, name, color, position, is_done_state, is_default, created_at, updated_at FROM project_statuses
WHERE project_id = $1 AND name = $2
`

type GetProjectStatusByNameParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

func (q *Queries) GetProjectStatusByName(ctx context.Context, arg GetProjectStatusByNameParams) (ProjectStatus, error) {
	row := q.db.QueryRow(ctx, getProjectStatusByName, arg.ProjectID, arg.Name)
	var i ProjectStatus
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDoneState,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectStatusesWithTaskCounts = `-- name: GetProjectStatusesWithTaskCounts :many
SELECT ps.id, ps.project_id, ps.name, ps.color, ps.position, ps.is_done_state, ps.is_default, ps.created_at, ps.updated_at,
  COALESCE((SELECT COUNT(*)::int FROM tasks t WHERE t.custom_status_id = ps.id), 0) AS task_count
FROM project_statuses ps
WHERE ps.project_id = $1
ORDER BY ps.position ASC
`

type GetProjectStatusesWithTaskCountsRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Name        string             `json:"name"`
	Color       *string            `json:"color"`
	Position    *int32             `json:"position"`
	IsDoneState *bool              `json:"is_done_state"`
	IsDefault   *bool              `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	TaskCount   interface{}        `json:"task_count"`
}

// Returns all statuses for a project with task counts
func (q *Queries) GetProjectStatusesWithTaskCounts(ctx context.Context, projectID pgtype.UUID) ([]GetProjectStatusesWithTaskCountsRow, error) {
	rows, err := q.db.Query(ctx, getProjectStatusesWithTaskCounts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectStatusesWithTaskCountsRow{}
	for rows.Next() {
		var i GetProjectStatusesWithTaskCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.IsDoneState,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectStatuses = `-- name: ListProjectStatuses :many
SELECT id, project_id, name, color, position, is_done_state, is_default, created_at, updated_at FROM project_statuses
WHERE project_id = $1
ORDER BY position ASC
`

// Lists all statuses for a project ordered by position
func (q *Queries) ListProjectStatuses(ctx context.Context, projectID pgtype.UUID) ([]ProjectStatus, error) {
	rows, err := q.db.Query(ctx, listProjectStatuses, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectStatus{}
	for rows.Next() {
		var i ProjectStatus
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.IsDoneState,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderProjectStatuses = `-- name: ReorderProjectStatuses :exec
UPDATE project_statuses AS ps
SET position = new_positions.new_position, updated_at = NOW()
FROM (
  SELECT s.id AS status_id, ROW_NUMBER() OVER (ORDER BY s.position) - 1 AS new_position
  FROM project_statuses s
  WHERE s.project_id = $1
) AS new_positions
WHERE ps.id = new_positions.status_id
`

// Updates positions for all statuses after reorder
func (q *Queries) ReorderProjectStatuses(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, reorderProjectStatuses, projectID)
	return err
}

const setDefaultProjectStatus = `-- name: SetDefaultProjectStatus :exec
UPDATE project_statuses ps
SET is_default = (ps.id = $1), updated_at = NOW()
WHERE ps.project_id = (SELECT sub.project_id FROM project_statuses sub WHERE sub.id = $1)
`

// Sets a status as the default and unsets any other default for the project
func (q *Queries) SetDefaultProjectStatus(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setDefaultProjectStatus, id)
	return err
}

const updateProjectCustomStatus = `-- name: UpdateProjectCustomStatus :one
UPDATE project_statuses
SET name = $2, color = $3, is_done_state = $4, is_default = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, name, color, position, is_done_state, is_default, created_at, updated_at
`

type UpdateProjectCustomStatusParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Color       *string     `json:"color"`
	IsDoneState *bool       `json:"is_done_state"`
	IsDefault   *bool       `json:"is_default"`
}

func (q *Queries) UpdateProjectCustomStatus(ctx context.Context, arg UpdateProjectCustomStatusParams) (ProjectStatus, error) {
	row := q.db.QueryRow(ctx, updateProjectCustomStatus,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.IsDoneState,
		arg.IsDefault,
	)
	var i ProjectStatus
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDoneState,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectStatusPosition = `-- name: UpdateProjectStatusPosition :exec
UPDATE project_statuses
SET position = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateProjectStatusPositionParams struct {
	ID       pgtype.UUID `json:"id"`
	Position *int32      `json:"position"`
}

func (q *Queries) UpdateProjectStatusPosition(ctx context.Context, arg UpdateProjectStatusPositionParams) error {
	_, err := q.db.Exec(ctx, updateProjectStatusPosition, arg.ID, arg.Position)
	return err
}
