// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reasoning_templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultTemplate = `-- name: ClearDefaultTemplate :exec
UPDATE reasoning_templates
SET is_default = false, updated_at = NOW()
WHERE user_id = $1 AND is_default = true
`

func (q *Queries) ClearDefaultTemplate(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearDefaultTemplate, userID)
	return err
}

const createReasoningTemplate = `-- name: CreateReasoningTemplate :one
INSERT INTO reasoning_templates (
    user_id, name, description, system_prompt, thinking_instruction,
    output_format, show_thinking, save_thinking, max_thinking_tokens, is_default
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, name, description, system_prompt, thinking_instruction, output_format, show_thinking, save_thinking, max_thinking_tokens, times_used, is_default, created_at, updated_at
`

type CreateReasoningTemplateParams struct {
	UserID              string  `json:"user_id"`
	Name                string  `json:"name"`
	Description         *string `json:"description"`
	SystemPrompt        *string `json:"system_prompt"`
	ThinkingInstruction *string `json:"thinking_instruction"`
	OutputFormat        *string `json:"output_format"`
	ShowThinking        *bool   `json:"show_thinking"`
	SaveThinking        *bool   `json:"save_thinking"`
	MaxThinkingTokens   *int32  `json:"max_thinking_tokens"`
	IsDefault           *bool   `json:"is_default"`
}

func (q *Queries) CreateReasoningTemplate(ctx context.Context, arg CreateReasoningTemplateParams) (ReasoningTemplate, error) {
	row := q.db.QueryRow(ctx, createReasoningTemplate,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.ThinkingInstruction,
		arg.OutputFormat,
		arg.ShowThinking,
		arg.SaveThinking,
		arg.MaxThinkingTokens,
		arg.IsDefault,
	)
	var i ReasoningTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ThinkingInstruction,
		&i.OutputFormat,
		&i.ShowThinking,
		&i.SaveThinking,
		&i.MaxThinkingTokens,
		&i.TimesUsed,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReasoningTemplate = `-- name: DeleteReasoningTemplate :exec
DELETE FROM reasoning_templates
WHERE id = $1 AND user_id = $2
`

type DeleteReasoningTemplateParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteReasoningTemplate(ctx context.Context, arg DeleteReasoningTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteReasoningTemplate, arg.ID, arg.UserID)
	return err
}

const getDefaultReasoningTemplate = `-- name: GetDefaultReasoningTemplate :one
SELECT id, user_id, name, description, system_prompt, thinking_instruction, output_format, show_thinking, save_thinking, max_thinking_tokens, times_used, is_default, created_at, updated_at FROM reasoning_templates
WHERE user_id = $1 AND is_default = true
LIMIT 1
`

func (q *Queries) GetDefaultReasoningTemplate(ctx context.Context, userID string) (ReasoningTemplate, error) {
	row := q.db.QueryRow(ctx, getDefaultReasoningTemplate, userID)
	var i ReasoningTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ThinkingInstruction,
		&i.OutputFormat,
		&i.ShowThinking,
		&i.SaveThinking,
		&i.MaxThinkingTokens,
		&i.TimesUsed,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReasoningTemplate = `-- name: GetReasoningTemplate :one
SELECT id, user_id, name, description, system_prompt, thinking_instruction, output_format, show_thinking, save_thinking, max_thinking_tokens, times_used, is_default, created_at, updated_at FROM reasoning_templates
WHERE id = $1 AND user_id = $2
`

type GetReasoningTemplateParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetReasoningTemplate(ctx context.Context, arg GetReasoningTemplateParams) (ReasoningTemplate, error) {
	row := q.db.QueryRow(ctx, getReasoningTemplate, arg.ID, arg.UserID)
	var i ReasoningTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ThinkingInstruction,
		&i.OutputFormat,
		&i.ShowThinking,
		&i.SaveThinking,
		&i.MaxThinkingTokens,
		&i.TimesUsed,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementTemplateUsage = `-- name: IncrementTemplateUsage :exec
UPDATE reasoning_templates
SET times_used = times_used + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementTemplateUsage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementTemplateUsage, id)
	return err
}

const listReasoningTemplates = `-- name: ListReasoningTemplates :many
SELECT id, user_id, name, description, system_prompt, thinking_instruction, output_format, show_thinking, save_thinking, max_thinking_tokens, times_used, is_default, created_at, updated_at FROM reasoning_templates
WHERE user_id = $1
ORDER BY is_default DESC, times_used DESC, created_at DESC
`

func (q *Queries) ListReasoningTemplates(ctx context.Context, userID string) ([]ReasoningTemplate, error) {
	rows, err := q.db.Query(ctx, listReasoningTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReasoningTemplate{}
	for rows.Next() {
		var i ReasoningTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.SystemPrompt,
			&i.ThinkingInstruction,
			&i.OutputFormat,
			&i.ShowThinking,
			&i.SaveThinking,
			&i.MaxThinkingTokens,
			&i.TimesUsed,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultReasoningTemplate = `-- name: SetDefaultReasoningTemplate :exec
UPDATE reasoning_templates
SET is_default = CASE WHEN id = $2 THEN true ELSE false END,
    updated_at = NOW()
WHERE user_id = $1
`

type SetDefaultReasoningTemplateParams struct {
	UserID string      `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SetDefaultReasoningTemplate(ctx context.Context, arg SetDefaultReasoningTemplateParams) error {
	_, err := q.db.Exec(ctx, setDefaultReasoningTemplate, arg.UserID, arg.ID)
	return err
}

const updateReasoningTemplate = `-- name: UpdateReasoningTemplate :one
UPDATE reasoning_templates
SET name = $2, description = $3, system_prompt = $4, thinking_instruction = $5,
    output_format = $6, show_thinking = $7, save_thinking = $8,
    max_thinking_tokens = $9, updated_at = NOW()
WHERE id = $1 AND user_id = $10
RETURNING id, user_id, name, description, system_prompt, thinking_instruction, output_format, show_thinking, save_thinking, max_thinking_tokens, times_used, is_default, created_at, updated_at
`

type UpdateReasoningTemplateParams struct {
	ID                  pgtype.UUID `json:"id"`
	Name                string      `json:"name"`
	Description         *string     `json:"description"`
	SystemPrompt        *string     `json:"system_prompt"`
	ThinkingInstruction *string     `json:"thinking_instruction"`
	OutputFormat        *string     `json:"output_format"`
	ShowThinking        *bool       `json:"show_thinking"`
	SaveThinking        *bool       `json:"save_thinking"`
	MaxThinkingTokens   *int32      `json:"max_thinking_tokens"`
	UserID              string      `json:"user_id"`
}

func (q *Queries) UpdateReasoningTemplate(ctx context.Context, arg UpdateReasoningTemplateParams) (ReasoningTemplate, error) {
	row := q.db.QueryRow(ctx, updateReasoningTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.ThinkingInstruction,
		arg.OutputFormat,
		arg.ShowThinking,
		arg.SaveThinking,
		arg.MaxThinkingTokens,
		arg.UserID,
	)
	var i ReasoningTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ThinkingInstruction,
		&i.OutputFormat,
		&i.ShowThinking,
		&i.SaveThinking,
		&i.MaxThinkingTokens,
		&i.TimesUsed,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
