// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFocusItem = `-- name: CreateFocusItem :one
INSERT INTO focus_items (user_id, text, focus_date)
VALUES ($1, $2, $3)
RETURNING id, user_id, text, completed, focus_date, created_at, updated_at
`

type CreateFocusItemParams struct {
	UserID    string           `json:"user_id"`
	Text      string           `json:"text"`
	FocusDate pgtype.Timestamp `json:"focus_date"`
}

func (q *Queries) CreateFocusItem(ctx context.Context, arg CreateFocusItemParams) (FocusItem, error) {
	row := q.db.QueryRow(ctx, createFocusItem, arg.UserID, arg.Text, arg.FocusDate)
	var i FocusItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.Completed,
		&i.FocusDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, title, description, status, priority, due_date, project_id, assignee_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, title, description, status, priority, due_date, start_date, completed_at, project_id, assignee_id, parent_task_id, custom_status_id, position, created_at, updated_at
`

type CreateTaskParams struct {
	UserID      string           `json:"user_id"`
	Title       string           `json:"title"`
	Description *string          `json:"description"`
	Status      NullTaskstatus   `json:"status"`
	Priority    NullTaskpriority `json:"priority"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	ProjectID   pgtype.UUID      `json:"project_id"`
	AssigneeID  pgtype.UUID      `json:"assignee_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.ProjectID,
		arg.AssigneeID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.StartDate,
		&i.CompletedAt,
		&i.ProjectID,
		&i.AssigneeID,
		&i.ParentTaskID,
		&i.CustomStatusID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFocusItem = `-- name: DeleteFocusItem :exec
DELETE FROM focus_items
WHERE id = $1 AND user_id = $2
`

type DeleteFocusItemParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteFocusItem(ctx context.Context, arg DeleteFocusItemParams) error {
	_, err := q.db.Exec(ctx, deleteFocusItem, arg.ID, arg.UserID)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1 AND user_id = $2
`

type DeleteTaskParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, title, description, status, priority, due_date, start_date, completed_at, project_id, assignee_id, parent_task_id, custom_status_id, position, created_at, updated_at FROM tasks
WHERE id = $1 AND user_id = $2
`

type GetTaskParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.StartDate,
		&i.CompletedAt,
		&i.ProjectID,
		&i.AssigneeID,
		&i.ParentTaskID,
		&i.CustomStatusID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFocusItems = `-- name: ListFocusItems :many
SELECT id, user_id, text, completed, focus_date, created_at, updated_at FROM focus_items
WHERE user_id = $1
  AND DATE(focus_date) = $2::date
ORDER BY created_at ASC
`

type ListFocusItemsParams struct {
	UserID    string      `json:"user_id"`
	FocusDate pgtype.Date `json:"focus_date"`
}

func (q *Queries) ListFocusItems(ctx context.Context, arg ListFocusItemsParams) ([]FocusItem, error) {
	rows, err := q.db.Query(ctx, listFocusItems, arg.UserID, arg.FocusDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FocusItem{}
	for rows.Next() {
		var i FocusItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Text,
			&i.Completed,
			&i.FocusDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, user_id, title, description, status, priority, due_date, start_date, completed_at, project_id, assignee_id, parent_task_id, custom_status_id, position, created_at, updated_at FROM tasks
WHERE user_id = $1
  AND ($2::taskstatus IS NULL OR status = $2)
  AND ($3::taskpriority IS NULL OR priority = $3)
  AND ($4::uuid IS NULL OR project_id = $4)
ORDER BY
  CASE priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 WHEN 'low' THEN 4 END,
  due_date ASC NULLS LAST,
  created_at DESC
`

type ListTasksParams struct {
	UserID    string           `json:"user_id"`
	Status    NullTaskstatus   `json:"status"`
	Priority  NullTaskpriority `json:"priority"`
	ProjectID pgtype.UUID      `json:"project_id"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.UserID,
		arg.Status,
		arg.Priority,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.StartDate,
			&i.CompletedAt,
			&i.ProjectID,
			&i.AssigneeID,
			&i.ParentTaskID,
			&i.CustomStatusID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleTaskStatus = `-- name: ToggleTaskStatus :one
UPDATE tasks
SET status = CASE WHEN status = 'done' THEN 'todo'::taskstatus ELSE 'done'::taskstatus END,
    completed_at = CASE WHEN status = 'done' THEN NULL ELSE NOW() END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, description, status, priority, due_date, start_date, completed_at, project_id, assignee_id, parent_task_id, custom_status_id, position, created_at, updated_at
`

func (q *Queries) ToggleTaskStatus(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, toggleTaskStatus, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.StartDate,
		&i.CompletedAt,
		&i.ProjectID,
		&i.AssigneeID,
		&i.ParentTaskID,
		&i.CustomStatusID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFocusItem = `-- name: UpdateFocusItem :one
UPDATE focus_items
SET text = $2, completed = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, text, completed, focus_date, created_at, updated_at
`

type UpdateFocusItemParams struct {
	ID        pgtype.UUID `json:"id"`
	Text      string      `json:"text"`
	Completed *bool       `json:"completed"`
}

func (q *Queries) UpdateFocusItem(ctx context.Context, arg UpdateFocusItemParams) (FocusItem, error) {
	row := q.db.QueryRow(ctx, updateFocusItem, arg.ID, arg.Text, arg.Completed)
	var i FocusItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.Completed,
		&i.FocusDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
  title = COALESCE($1, title),
  description = COALESCE($2, description),
  status = COALESCE($3, status),
  priority = COALESCE($4, priority),
  due_date = COALESCE($5, due_date),
  project_id = COALESCE($6, project_id),
  assignee_id = COALESCE($7, assignee_id),
  position = COALESCE($8, position),
  updated_at = NOW()
WHERE id = $9
RETURNING id, user_id, title, description, status, priority, due_date, start_date, completed_at, project_id, assignee_id, parent_task_id, custom_status_id, position, created_at, updated_at
`

type UpdateTaskParams struct {
	Title       *string          `json:"title"`
	Description *string          `json:"description"`
	Status      NullTaskstatus   `json:"status"`
	Priority    NullTaskpriority `json:"priority"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	ProjectID   pgtype.UUID      `json:"project_id"`
	AssigneeID  pgtype.UUID      `json:"assignee_id"`
	Position    *int32           `json:"position"`
	ID          pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.ProjectID,
		arg.AssigneeID,
		arg.Position,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.StartDate,
		&i.CompletedAt,
		&i.ProjectID,
		&i.AssigneeID,
		&i.ParentTaskID,
		&i.CustomStatusID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
